/* Chapters add connected explanation, worked reasoning and discriminating comparisons. */
(function(){
const C=(title,paragraphs)=>({title,paragraphs});
const W=(title,context,steps,conclusion)=>({title,context,steps,conclusion});
const D=(intro,objectives,concept,worked,comparison,trap)=>({intro,objectives,concept,worked,comparison,trap});
window.CQChapterContent={
'design:0':D('Um elemento visual não comunica sozinho: seu tamanho, posição e relação com os demais determinam sua função. Nesta aula, você vai aprender a justificar uma composição.', ['Identificar a função de ponto, linha, forma e textura','Usar espaço e escala para organizar informação','Justificar uma decisão visual pela tarefa do leitor'],C('Da aparência à função',[
'Ponto é uma unidade de atenção; uma sequência de pontos pode sugerir uma linha. A linha estabelece direção, conexão ou separação. A forma delimita uma área e pode ser geométrica ou orgânica. Textura descreve uma qualidade de superfície, real ou simulada. Esses elementos podem desempenhar mais de uma função conforme o contexto.',
'Uma linha horizontal abaixo de um título pode separar seções. A mesma linha, terminando em uma seta, pode indicar direção. Portanto, identificar o elemento é só o início: é preciso explicar o papel que ele desempenha naquela composição.',
'O espaço negativo é a área entre e ao redor dos elementos. Ele cria intervalos, isola focos e ajuda a formar grupos. Preencher todo espaço disponível pode eliminar essas relações. Por outro lado, espaço excessivo entre um título e sua descrição pode desfazer a associação entre eles.',
'Escala é relativa: um título se destaca em relação aos outros elementos. Aumentar todos os textos na mesma proporção não muda necessariamente a hierarquia. Para analisar uma peça, pergunte o que o leitor deve encontrar primeiro, o que precisa relacionar e qual ação deve conseguir realizar.'
]),W('Organize um aviso de atendimento','Você tem quatro informações: “Atendimento especial”, sábado, 8h às 12h e endereço.', ['Defina a tarefa: a pessoa precisa reconhecer o serviço e descobrir quando e onde será atendida.','Dê prioridade ao assunto; reúna dia e horário, porque respondem à mesma necessidade.','Use um intervalo maior antes do endereço, sem afastá-lo tanto que pareça outra mensagem.','Verifique se linhas, cores e textura ajudam essas relações ou apenas disputam atenção.'],'A justificativa não é “ficou bonito”: a organização facilita localizar e associar informações.'),[['Elemento','Função possível','Cuidado'],['Linha','Separar ou conduzir','Uma divisão pode sugerir grupos que não existem'],['Espaço','Agrupar ou isolar','Distância excessiva pode romper uma relação'],['Textura','Sugerir superfície ou caráter','Pode competir com o texto']],'Não associe cada elemento a uma função única. Leia a relação e a finalidade no contexto.'),
'design:1':D('Proximidade e semelhança explicam por que percebemos conjuntos antes de examinar cada elemento. Você vai observar a pista visual e depois aplicá-la a uma interface.', ['Distinguir distância de característica compartilhada','Reconhecer quando pistas cooperam ou competem','Agrupar conteúdo de acordo com sua relação de sentido'],C('O grupo é uma interpretação',[
'Na proximidade, a distância relativa é decisiva: elementos mais próximos entre si tendem a ser percebidos como um conjunto. Não existe uma medida universal que torne algo “próximo”. O intervalo interno precisa ser comparado ao intervalo que separa grupos.',
'Na semelhança, a associação vem de atributos compartilhados: cor, forma, tamanho, orientação ou estilo. Dois botões distantes podem parecer ter a mesma função se compartilham aparência. Isso é útil para consistência, mas também pode confundir quando ações diferentes recebem o mesmo tratamento.',
'Os princípios podem atuar ao mesmo tempo. Em um formulário, rótulo e campo ficam próximos; todos os rótulos compartilham estilo. A proximidade associa cada par e a semelhança indica a categoria dos rótulos. Não é necessário escolher apenas um princípio para descrever toda a tela.',
'Quando as pistas entram em conflito, avalie o que deve ser entendido. Se itens de assuntos diferentes ficam muito próximos, o usuário pode agrupá-los apesar das diferenças de cor. Em uma questão, procure a variável que foi alterada entre as versões: distância, cor, forma ou contorno.'
]),W('Corrija a associação de um menu','Um menu tem títulos e descrições com intervalos iguais entre todas as linhas.', ['Identifique quais elementos pertencem ao mesmo assunto: cada título e sua descrição.','Reduza o intervalo dentro desses pares e amplie o intervalo entre assuntos.','Mantenha o estilo dos títulos consistente para que também sejam reconhecidos como categoria.','Teste sem caixas ou linhas: os grupos continuam perceptíveis?'],'A proximidade organiza cada assunto; a semelhança ajuda a reconhecer o papel dos títulos.'),[['Pista que muda','Princípio em destaque','Como verificar'],['Intervalo entre elementos','Proximidade','Compare distâncias internas e externas'],['Cor, forma ou estilo','Semelhança','Procure o atributo compartilhado'],['As duas pistas','Atuação conjunta','Explique o papel de cada uma']],'Elementos da mesma cor não deixam de sofrer influência da distância. Evite explicações absolutas.'),
'design:2':D('Reconhecer uma forma incompleta e seguir uma trajetória são processos diferentes. A distinção fica clara quando você observa o que o olhar está reconstruindo.', ['Identificar fechamento em contornos incompletos','Seguir uma trajetória de boa continuidade','Distinguir completar uma borda de acompanhar uma direção'],C('Duas maneiras de organizar a forma',[
'Fechamento é a tendência de perceber uma forma completa quando o arranjo das partes sugere uma borda ausente. Um quadrado feito de segmentos separados pode continuar reconhecível. A interpretação depende da organização dos fragmentos, não apenas da existência de lacunas.',
'Boa continuidade é a tendência de organizar elementos ao longo de uma trajetória suave. Quando duas linhas se cruzam, costumamos acompanhar a direção que dá continuidade ao caminho, em vez de interpretar a figura como linhas que mudam bruscamente de rota.',
'Uma peça pode explorar os dois fenômenos. Um símbolo pode ter bordas interrompidas e ao mesmo tempo uma direção visual clara. Na análise, identifique o mecanismo pedido: completar uma forma ou seguir um percurso.',
'Em design, a simplificação precisa preservar pistas suficientes. Omitir partes demais pode impedir o reconhecimento. Uma linha de leitura também pode falhar se a direção visual conduz para fora da informação principal. O princípio descreve uma tendência perceptiva, não garante o sucesso de qualquer composição.'
]),W('Analise um símbolo com bordas ausentes','Um círculo é desenhado com três arcos separados, mas continua reconhecível.', ['Observe se os fragmentos sugerem uma forma global identificável.','Localize as lacunas: a borda completa não foi desenhada.','Explique que o olhar completa o contorno sugerido, caracterizando fechamento.','Se a questão mostrar linhas cruzadas e pedir para acompanhar um caminho, mude o critério para continuidade.'],'Descreva a operação percebida antes de nomear o princípio.'),[['Pergunta visual','Mecanismo','Exemplo'],['Que forma completa é sugerida?','Fechamento','Contorno circular interrompido'],['Qual caminho continua suavemente?','Boa continuidade','Curvas que se cruzam'],['Quais elementos estão próximos?','Proximidade','Grupos separados por espaço']],'Nem toda imagem simplificada exemplifica fechamento. Precisa existir uma forma completada pelas pistas visuais.'),
'design:3':D('Uma imagem não é apenas um conjunto de objetos desenhados. O olhar decide o que se destaca como figura e como organizar o restante.', ['Alternar figura e fundo em uma imagem ambígua','Analisar a função do espaço negativo','Distinguir pregnância de uma regra de minimalismo'],C('A borda pode pertencer a duas leituras',[
'Figura é a região percebida como objeto de atenção; fundo é o campo contra o qual ela se destaca. Essa separação depende de relações de forma, contraste, contorno e contexto. Fundo não significa irrelevância: sua configuração participa da leitura.',
'Na imagem ambígua do vaso e dos perfis, o mesmo limite pode definir o vaso branco ou dois rostos escuros. A geometria não se altera; muda a organização perceptiva. Esse exemplo evidencia que reconhecer figura e fundo não é simplesmente identificar a cor mais clara.',
'O espaço negativo pode conter uma segunda forma intencional. Em símbolos, isso permite significados construídos pela relação entre áreas preenchidas e vazias. Para avaliar uma proposta, examine ambas as regiões e verifique se a leitura permanece clara no tamanho de uso.',
'Pregnância se relaciona à tendência de organizar o campo de maneira simples, regular e estável. Três círculos sobrepostos costumam ser percebidos como círculos, e não como vários arcos independentes. Isso não determina que toda peça deva ser minimalista: uma composição complexa pode apresentar boa organização.'
]),W('Recupere o título de um cartaz','Uma fotografia muito detalhada passa por trás de um texto e dificulta sua leitura.', ['Identifique a figura desejada: a mensagem deve ser reconhecida com facilidade.','Observe onde a fotografia cria variações que competem com as bordas das letras.','Teste reposicionamento, área de respiro ou um suporte com contraste consistente.','Confira a mensagem no tamanho real, preservando a função da fotografia.'],'O objetivo é separar perceptivamente a mensagem do fundo, não apagar qualquer detalhe.'),[['Conceito','Pergunta de análise'],['Figura/fundo','O que se destaca e contra qual campo?'],['Espaço negativo','Que forma o vazio também sugere?'],['Pregnância','Como as partes se organizam de modo estável?']],'Não confunda pregnância com “menos elementos sempre é melhor” nem figura com “a região branca”.'),
'design:4':D('Hierarquia visual é uma decisão sobre prioridade de informação. Vamos analisar o mesmo conteúdo em duas peças e justificar uma ordem de leitura.', ['Relacionar prioridade visual à tarefa do leitor','Combinar escala, contraste, posição e proximidade','Diagnosticar disputa de atenção e informação essencial escondida'],C('Escolha o que merece atenção primeiro',[
'Hierarquia é a diferença de importância percebida entre elementos. Ela pode ser construída por tamanho, peso, contraste, posição, isolamento e agrupamento. Não depende de uma única propriedade nem de uma sequência rígida aplicável a toda peça.',
'Em um cartaz de evento, o assunto identifica a oferta; data e local permitem participar; a chamada orienta uma ação. A composição deve tornar essas funções reconhecíveis. Uma fotografia pode contextualizar o tema, mas não deve tornar o prazo ilegível.',
'Destaque é relativo. Se título, endereço, data e chamada têm a mesma escala, peso e cor, passam a disputar o mesmo nível de atenção. Para criar prioridade, pode ser mais útil reduzir a ênfase de informações secundárias do que aumentar tudo.',
'Hierarquia também depende da situação. Em um aviso urgente, a data de interrupção pode precisar de mais evidência que o nome institucional. Leia o objetivo e o público antes de aplicar receitas como “o título sempre precisa ser o maior”.'
]),W('Reorganize um cartaz cultural','O cartaz contém tema, dia, horário, local e inscrição gratuita.', ['Escreva a ordem desejada: identificar a oficina, localizar quando e onde, descobrir como participar.','Faça o título dominar sem competir com todas as outras linhas.','Agrupe dia, horário e local; separe a chamada de inscrição com contraste suficiente.','Compare as versões por tempo de localização da informação, não apenas por preferência estética.'],'Uma boa justificativa liga cada escolha a uma tarefa de leitura.'),[['Decisão','Efeito esperado','Risco'],['Maior escala no assunto','Identificação rápida','O restante ficar pequeno demais'],['Proximidade nos detalhes','Associação entre dia e local','Agrupar informações sem relação'],['Contraste na ação','Orientar o próximo passo','Criar competição com a mensagem principal']],'Uma peça pode ter um título forte e ainda falhar por esconder data, condição ou prazo essenciais.'),
'design:5':D('O grid funciona como uma estrutura de relações. Ele ajuda a manter consistência sem transformar todas as páginas em composições idênticas.', ['Distinguir margem, coluna e entrecoluna','Combinar elementos em diferentes extensões','Adaptar a estrutura sem perder ordem de leitura'],C('Construa relações compartilhadas',[
'Margens definem a área de respiro em torno do conteúdo. Colunas dividem a largura utilizável. Entrecolunas, ou gutters, separam essas faixas. Um grid modular acrescenta divisões horizontais; um grid de linha de base pode organizar o alinhamento de linhas de texto.',
'Um título pode ocupar quatro colunas, uma fotografia ocupar duas e um texto ocupar as outras duas. Compartilhar alinhamentos cria relações entre elementos de tamanhos diferentes. O grid é uma referência para posicionamento, não uma exigência de colocar um objeto dentro de cada faixa.',
'Consistência facilita orientação: o leitor reconhece onde começam os conteúdos e como os níveis se relacionam. Variações podem ser intencionais, por exemplo para destacar a abertura de uma seção. Romper o grid exige propósito e cuidado para não destruir a coerência.',
'Em telas menores, uma composição de duas colunas pode virar uma. A ordem de leitura deve permanecer compreensível. Simplesmente reduzir toda a página pode produzir textos pequenos, áreas de toque insuficientes e imagens sem função perceptível.'
]),W('Adapte uma publicação para o celular','Uma página tem fotografia à esquerda e explicação à direita.', ['Identifique a relação: a foto apresenta o assunto e o texto explica o que foi mostrado.','No celular, coloque os blocos em uma coluna mantendo essa sequência.','Preserve margens e intervalos que indiquem a relação entre a foto e sua explicação.','Teste títulos longos e conteúdos reais, não apenas caixas vazias.'],'A adaptação preserva relações e acesso à informação; não é uma miniatura da página maior.'),[['Elemento','Onde atua'],['Margem','Entre o conteúdo e a borda da área'],['Entrecoluna','Entre colunas'],['Linha de base','No alinhamento vertical das linhas de texto']],'Grid, margem de segurança e sangria não são nomes para a mesma área.'),
'design:6':D('Conhecer a anatomia das letras ajuda a diagnosticar problemas de leitura e espaçamento, além de reconhecer famílias tipográficas.', ['Identificar altura-x, ascendentes e descendentes','Distinguir família, peso e estilo','Escolher entre kerning, tracking e entrelinha'],C('Leia o desenho da letra',[
'A linha de base é a referência em que a maior parte das letras se apoia. Altura-x descreve a altura do corpo de minúsculas como x, sem ascendentes e descendentes. No b, a haste ultrapassa essa altura; no g, uma parte pode descer abaixo da base. O desenho varia entre fontes.',
'Duas fontes no mesmo tamanho nominal podem parecer diferentes em escala por causa de suas proporções. Por isso, comparar apenas o número de pontos não basta. Altura-x, largura, contraste entre traços e abertura dos espaços internos afetam a aparência e a leitura.',
'Famílias podem oferecer pesos e estilos, como regular, negrito e itálico. Serifada e sem serifa são classificações de características do desenho, não garantias de adequação. Uma fonte monoespaçada usa avanços regulares para os caracteres, o que costuma ser útil em código e alinhamento técnico.',
'Kerning ajusta o espaço entre pares específicos. Tracking altera o espaçamento de uma sequência. Entrelinha regula a distância vertical entre linhas. São controles diferentes: corrigir um par AV com entrelinha não atua no problema.'
]),W('Corrija uma palavra e um parágrafo','No título, AV parece separado demais. No parágrafo, as linhas parecem encostadas.', ['Localize o problema do título em um par específico de caracteres.','Ajuste o kerning desse par e compare com o ritmo dos demais espaços.','No parágrafo, avalie a entrelinha e o tamanho do texto no suporte final.','Se toda a palavra estiver excessivamente aberta, examine o tracking, em vez de corrigir cada par isoladamente.'],'O diagnóstico define o controle tipográfico apropriado.'),[['Controle','Unidade afetada','Exemplo'],['Kerning','Par de caracteres','Ajustar AV'],['Tracking','Sequência de caracteres','Aproximar um título inteiro'],['Entrelinha','Linhas de texto','Aumentar o respiro de um parágrafo']],'Não confunda tamanho nominal com altura visual percebida nem categoria da fonte com legibilidade garantida.'),
'design:7':D('A escolha tipográfica só pode ser avaliada nas condições de leitura. Uma mensagem precisa ser reconhecida e percorrida com esforço adequado.', ['Relacionar desenho e contexto de leitura','Diagnosticar escala, contraste e espaçamento','Testar a mensagem no suporte final'],C('A leitura depende de um conjunto',[
'Legibilidade envolve reconhecer os caracteres e distingui-los uns dos outros. A facilidade de percorrer um texto também depende de organização, extensão de linhas, entrelinha e linguagem. Os termos usados para essas dimensões podem variar; o importante é identificar o problema concreto.',
'Fonte, tamanho, contraste e espaço interagem. Um desenho tipográfico adequado pode falhar se for pequeno demais. Um tamanho grande pode não resolver baixo contraste. Espaçamento apertado pode aproximar caracteres e linhas a ponto de dificultar a distinção.',
'Distância e suporte importam: uma placa não é lida como uma legenda de celular. Considere iluminação, tamanho final, resolução e condições do público. Testar somente a tela de edição, ampliada, pode ocultar dificuldades presentes na aplicação real.',
'Caixa-alta pode funcionar em rótulos curtos, mas seu uso contínuo em parágrafos altera o desenho das palavras e pode tornar a leitura menos confortável. Evite converter tendências em proibições universais. A decisão precisa ser avaliada no uso.'
]),W('Revise um aviso que ficou apertado','Um texto longo foi comprimido para caber em uma área pequena.', ['Identifique o que precisa permanecer para preservar a informação.','Reorganize o espaço e a hierarquia antes de deformar caracteres.','Ajuste escala, extensão da linha e entrelinha em conjunto.','Leia no tamanho final e verifique se a informação essencial continua acessível.'],'Fazer caber não é o mesmo que tornar legível.'),[['Problema','Verificação útil'],['Letras se confundem','Desenho, escala e espaçamento'],['Leitor perde a linha','Extensão de linha e entrelinha'],['Texto desaparece no fundo','Contraste e variação do fundo']],'Contorno, sombra e negrito não compensam automaticamente texto pequeno ou fundo visualmente instável.'),
'design:8':D('RGB e CMYK representam modos diferentes de produzir cor. Entender o processo ajuda a explicar resultados, não apenas a memorizar tela e impressão.', ['Prever misturas aditivas básicas','Distinguir luz emitida de luz refletida','Relacionar conversão a perfil e gama'],C('Cor depende de um processo de reprodução',[
'Em RGB, a cor é construída pela combinação de canais de luz vermelha, verde e azul. No exemplo digital de 8 bits por canal, os valores vão de 0 a 255. Os três em zero produzem preto; os três no máximo produzem branco no modelo. Vermelho e verde no máximo produzem amarelo.',
'Na impressão, a luz ilumina o suporte e parte dela é absorvida pelas tintas. O modelo CMY descreve componentes subtrativos ideais. O preto K é usado no processo CMYK para melhorar reprodução e controle. Tinta real, papel e condições de impressão não são uma simulação perfeita da mistura ideal.',
'Modelo de cor, perfil e gama são ideias relacionadas, mas diferentes. O modelo organiza componentes; o perfil caracteriza uma condição de reprodução; gama é o conjunto de cores reproduzíveis naquela condição. Nem toda cor de uma tela pode ser reproduzida por um processo de impressão.',
'Por isso, a conversão não é apenas trocar um nome. Um azul intenso pode mudar quando não cabe na gama de destino. O fluxo deve considerar especificações do fornecedor, perfis adequados e avaliação do resultado, inclusive prova quando pertinente.'
]),W('Prepare uma arte de tela para impressão','Uma peça contém um azul intenso e será impressa em um papel definido pela gráfica.', ['Confirme formato de entrega, perfil e condições solicitadas.','Preserve o arquivo de trabalho e gerencie a conversão para o destino.','Avalie as regiões mais saturadas e os detalhes de sombra, que podem mudar.','Confira a prova ou a simulação disponível com consciência de seus limites.'],'O resultado depende da condição de reprodução, não apenas de selecionar CMYK.'),[['Termo','Pergunta que responde'],['Modelo','Quais componentes representam a cor?'],['Perfil','Como uma condição de reprodução é caracterizada?'],['Gama','Quais cores essa condição consegue reproduzir?']],'Aumentar saturação para compensar uma conversão pode perder detalhes e não garante correspondência.'),
'design:9':D('Harmonia organiza relações entre matizes. A escolha da paleta precisa ser combinada com função, contraste e contexto de uso.', ['Distinguir relações complementar, análoga e triádica','Identificar o círculo cromático adotado','Separar harmonia de contraste de leitura'],C('O modelo vem antes dos nomes',[
'No círculo RGB/HSV, matizes complementares se opõem a 180 graus. Vermelho e ciano são um exemplo. Uma tríade usa três posições separadas por 120 graus; análogas ocupam regiões próximas. O círculo artístico RYB apresenta outras relações tradicionais, como vermelho e verde.',
'Matiz corresponde à família cromática. Saturação se relaciona à intensidade cromática e luminosidade ou valor descrevem dimensões de claro e escuro conforme o modelo utilizado. Alterar essas dimensões produz variações dentro de uma relação de matizes.',
'Uma paleta complementar pode criar diferenciação e, ainda assim, não oferecer contraste suficiente para texto. Matizes diferentes podem ter luminâncias próximas. Portanto, uma relação harmoniosa não equivale a uma aprovação de acessibilidade.',
'No projeto, atribua papéis: fundo, texto, ação principal, avisos e elementos de apoio. Teste combinações específicas, incluindo estados de foco, seleção e erro. Uma paleta deve sustentar a comunicação em diferentes situações, e não apenas parecer agradável em amostras isoladas.'
]),W('Use uma paleta em um formulário','Você escolheu azul e laranja para uma interface.', ['Defina qual cor será dominante e qual será usada para destaque.','Escolha pares concretos de texto e fundo, incluindo variações claras e escuras.','Verifique contraste e garanta que mensagens de erro não dependam apenas da cor.','Teste as cores nas áreas e proporções reais da interface.'],'A relação entre matizes é o começo da decisão, não sua validação completa.'),[['Relação','Estrutura','Cuidado'],['Complementar','Oposição no círculo','Identificar qual círculo está sendo usado'],['Análoga','Matizes próximos','Manter diferenciação funcional'],['Triádica','Três intervalos iguais','Controlar proporção e prioridade']],'Não misture modelos cromáticos ao responder qual cor é complementar de outra.'),
'design:16':D('Um arquivo de impressão precisa considerar o que será cortado e o que deve permanecer protegido. Sangria e segurança resolvem problemas diferentes.', ['Distinguir formato final, sangria e área segura','Relacionar tolerância de corte à extensão do fundo','Conferir especificações sem supor medidas universais'],C('A página final não é toda a área de produção',[
'A linha de corte delimita o formato final. Se uma imagem ou fundo chega a essa borda, normalmente precisa continuar além dela, na sangria. Essa extensão reduz o risco de aparecer um filete sem impressão quando houver pequena variação de corte.',
'A margem de segurança é interna ao formato final. Ela mantém informações essenciais, como texto e números, afastadas do corte. Estender o fundo para fora e afastar o texto para dentro são decisões complementares, não a mesma operação.',
'Marcas de corte indicam referências ao processo, mas não criam sangria nem corrigem um fundo que termina cedo. O arquivo deve conter efetivamente a imagem ou cor na extensão necessária.',
'A medida de sangria depende do produto e das especificações de produção. Uma solicitação de 3 mm é possível, mas não deve ser transformada em regra universal. Também confira formato, imagens, fontes e gerenciamento de cor.'
]),W('Detecte o erro antes de exportar','Um cartaz tem marcas de corte, mas o fundo termina exatamente na borda final.', ['Localize o formato final e visualize a área externa de sangria.','Estenda o fundo para essa área conforme a medida solicitada.','Mantenha telefone, data e demais textos dentro da área segura.','Revise o PDF exportado para conferir se as configurações foram mantidas.'],'Marcas orientam o corte; a extensão real do conteúdo evita a borda indesejada.'),[['Área','Posição','Função'],['Formato final','Dentro do corte','Dimensão do produto pronto'],['Sangria','Além do corte','Acomodar variações nas bordas'],['Segurança','Afastada do corte, por dentro','Proteger informação importante']],'Uma borda decorativa fina próxima ao corte pode evidenciar variações. Avalie a tolerância do processo.'),
'design:18':D('Resolução relaciona quantidade de amostras e tamanho de reprodução. A conta permite prever o que acontece ao ampliar uma imagem.', ['Distinguir dimensão em pixels e tamanho físico','Calcular ppi no tamanho final','Explicar os limites de interpolação e conversão de formato'],C('Quantidade de pixels e densidade não são a mesma coisa',[
'Uma imagem raster contém uma grade de pixels. Sua largura em pixels indica quantas amostras existem nessa direção. Ppi relaciona essa quantidade a polegadas na reprodução. A mesma imagem pode ter tamanhos físicos diferentes sem alterar o número de pixels.',
'A relação básica é tamanho em polegadas = pixels ÷ ppi. Com 1800 pixels a 300 ppi, a largura é 6 polegadas. Se a largura física dobrar mantendo os mesmos pixels, a densidade cai pela metade.',
'Interpolação calcula novas amostras com base nas existentes. Ela pode suavizar a ampliação, mas não garante recuperar o detalhe que não foi registrado. Alterar apenas o valor de ppi, sem reamostrar, muda a relação com o tamanho físico.',
'Vetores descrevem geometria e podem ser redesenhados em outras escalas. Contudo, SVG e PDF podem conter imagens raster incorporadas. A extensão do arquivo não comprova que todos os elementos sejam vetoriais nem que tenham resolução suficiente.'
]),W('Calcule o tamanho de uma foto','Uma foto possui 2400 pixels de largura e será usada a 300 ppi.', ['Divida 2400 por 300: a largura é 8 polegadas.','Para converter, multiplique 8 por 2,54: 20,32 cm.','Se usar a foto com 16 polegadas sem reamostrar, calcule 2400 ÷ 16 = 150 ppi.','Avalie se essa condição atende ao destino, considerando processo e distância de leitura.'],'A adequação depende do uso; a conta revela a densidade real.'),[['Mudança','O que acontece'],['Dobrar o tamanho físico sem reamostrar','Ppi cai pela metade'],['Mudar só o número de ppi','Não surgem detalhes novos'],['Colocar JPG dentro de SVG','A foto continua sendo raster']],'Não confunda ppi da imagem com dpi de um dispositivo de saída. Eles descrevem aspectos distintos.'),
'pt:0':D('Interpretar é sustentar uma leitura com o texto. A análise precisa distinguir o que foi afirmado, o que pode ser concluído e o que foi acrescentado sem apoio.', ['Localizar informação explícita','Construir uma inferência apoiada em pistas','Reconhecer extrapolação e mudanças de alcance'],C('Controle a força da afirmação',[
'Informação explícita está apresentada no trecho. Inferência resulta de conectar pistas e relações que o texto oferece. Extrapolação acrescenta algo sem apoio suficiente, ainda que a hipótese pareça plausível no mundo real.',
'Observe palavras que delimitam alcance: alguns, todos, pode, deve, somente, sempre. Uma alternativa pode repetir quase todo o texto e alterar apenas uma dessas palavras, produzindo uma conclusão mais forte ou diferente.',
'Considere referente, contexto e relação entre frases. Uma palavra pode retomar uma informação anterior; um conectivo pode introduzir oposição, condição ou conclusão. Ler isoladamente uma frase pode apagar essas relações.',
'Um procedimento útil é justificar a alternativa com uma passagem ou conexão específica. Se a justificativa depende apenas de “normalmente acontece assim”, verifique se você trouxe uma suposição externa.'
]),W('Analise a continuidade do serviço','“O atendimento presencial foi suspenso nesta sexta-feira. Os pedidos continuam disponíveis pelo portal.”', ['Marque o que foi suspenso: o atendimento presencial, naquele dia.','Marque o que continua: disponibilidade de pedidos pelo portal.','Conclua que a suspensão presencial não eliminou toda possibilidade de pedir o serviço.','Não conclua que a causa foi reforma nem que o portal é o único canal: essas informações não foram dadas.'],'A interpretação respeita tanto o conteúdo quanto o alcance das expressões.'),[['Leitura','Classificação'],['O presencial foi suspenso naquela sexta','Informação explícita'],['Ainda é possível fazer pedidos','Conclusão apoiada nas duas frases'],['A causa foi uma reforma','Extrapolação sem apoio no trecho']],'Plausibilidade não substitui evidência textual.'),
'pt:5':D('Crase exige analisar a construção. A palavra seguinte ser feminina é uma pista insuficiente: você precisa identificar os elementos que se fundem.', ['Verificar preposição e artigo no caso básico','Aplicar um teste de substituição compatível','Reconhecer situações em que falta um dos elementos'],C('Faça duas verificações',[
'No caso básico de “ir à Câmara”, há a preposição a, exigida pela relação de regência, e o artigo a que acompanha Câmara. A contração é indicada pelo acento grave. O acento marca o fenômeno; não deve ser confundido com o nome de qualquer som forte.',
'Primeiro investigue o termo anterior: ele exige preposição a nessa construção? Depois examine o termo seguinte: ele admite artigo a nesse uso? Sem essa análise, a regra falsa de “crase antes de feminino” produz erros.',
'A substituição por uma expressão masculina de estrutura equivalente pode ajudar. “Fui ao plenário” evidencia a + o e apoia “fui à Câmara”. O teste precisa manter a relação sintática; trocar a frase inteira por outra construção não prova o caso original.',
'Antes de infinitivo, como em “começou a estudar”, não há artigo feminino. Em “entreguei a ela”, o pronome pessoal não recebe esse artigo. Há ainda locuções e outras construções que exigem estudo específico; o mecanismo básico não esgota o tema.'
]),W('Compare três lacunas','Fui ___ Câmara. Começou ___ estudar. Entreguei o formulário ___ ela.', ['Na primeira, identifique a regência e o artigo: a + a, portanto à.','Na segunda, estudar é infinitivo e não recebe artigo feminino: fica a.','Na terceira, ela não recebe artigo nesse uso: fica apenas a preposição a.','Explique a presença ou ausência dos elementos, em vez de decidir só pela aparência da palavra.'],'O mesmo a escrito pode ter composição diferente conforme a construção.'),[['Construção','O que verificar','Resultado do exemplo'],['Ir à Câmara','Preposição e artigo','à'],['Começar a estudar','Não existe artigo antes do infinitivo','a'],['Entregar a ela','Pronome pessoal sem artigo','a']],'O teste do masculino é auxiliar. Não o use como substituto de toda a análise de regência e contexto.'),
'math:3':D('Porcentagem é uma proporção aplicada a uma base. O ponto mais importante é identificar sobre qual quantidade cada taxa atua.', ['Converter percentual em fator','Distinguir variação e valor final','Resolver alterações sucessivas sem somar taxas indevidamente'],C('Identifique a base antes da conta',[
'20% significa 20 por 100, ou 0,20. Para encontrar 20% de 200, calcule 0,20 × 200 = 40. Esse resultado é a parcela correspondente à taxa, não o valor final após um desconto.',
'Com desconto de 20%, permanece 80% da base: o fator é 1 − 0,20 = 0,80. Com aumento de 20%, o fator é 1 + 0,20 = 1,20. Multiplicar pelo fator final evita confundir a parcela com o total resultante.',
'Em alterações sucessivas, cada taxa atua sobre o resultado anterior. Um aumento de 20% seguido de desconto de 20% corresponde a 1,20 × 0,80 = 0,96. O resultado é 96% da base inicial, portanto uma redução total de 4%.',
'Porcentagem também se distingue de ponto percentual. Passar de 20% para 25% representa aumento de 5 pontos percentuais. Em relação à taxa inicial de 20%, a variação relativa é 5 ÷ 20 = 25%.'
]),W('Acompanhe a mudança de base','Um produto de R$ 100 sofre aumento de 20% e depois desconto de 20%.', ['Primeira base: 100. Aumento: 20. Novo preço: 120.','Segunda base: 120. Desconto: 0,20 × 120 = 24.','Preço final: 120 − 24 = 96.','Compare com a base original: 96 − 100 = −4, uma redução de 4%.'],'As taxas iguais não se anulam porque atuam sobre bases diferentes.'),[['Pergunta','Cálculo'],['Quanto é a parcela de 20%?','Base × 0,20'],['Quanto resta após descontar 20%?','Base × 0,80'],['Quanto resulta de aumentar 20%?','Base × 1,20']],'Para descobrir o valor anterior a um aumento, divida pelo fator. Descontar a mesma taxa do valor final não inverte a operação.'),
'math:11':D('A primeira tarefa em contagem é definir o que constitui um resultado diferente. Só depois escolha a fórmula.', ['Decidir se a ordem importa','Verificar repetição e quantidade selecionada','Interpretar a divisão pelas ordens de um mesmo grupo'],C('Conte escolhas sem duplicar resultados',[
'Quando decisões sucessivas têm quantidades de opções determinadas, o princípio multiplicativo combina essas possibilidades. Para presidente e secretário entre cinco pessoas, sem acumular cargos, há 5 opções para o primeiro cargo e 4 para o segundo: 20 resultados.',
'A ordem importa porque trocar as pessoas de cargo muda a composição dos cargos. Já numa comissão de duas pessoas sem funções distintas, Ana–Bia e Bia–Ana representam o mesmo grupo. A contagem ordenada deve ser dividida pelas 2! ordens de cada dupla.',
'Arranjo simples escolhe e ordena parte dos elementos distintos, sem repetição: A(n,k)=n!/(n−k)!. Combinação simples escolhe sem distinguir ordens internas: C(n,k)=n!/[k!(n−k)!]. Permutação simples organiza todos os n elementos distintos: n!.',
'Essas expressões têm hipóteses. Se repetições forem permitidas ou existirem elementos indistinguíveis, o modelo muda. Leia se alguém pode ocupar mais de uma posição e se trocar a ordem realmente cria um resultado novo.'
]),W('Duas perguntas com os mesmos cinco candidatos','Escolha dois cargos diferentes e depois compare com uma comissão de duas pessoas.', ['Para os cargos, conte 5 × 4 = 20.','Para a comissão, observe que cada dupla aparece em duas ordens na conta anterior.','Divida por 2: 20 ÷ 2 = 10 comissões.','Explique a diferença sem apelar só ao nome da fórmula: os cargos distinguem a ordem; a comissão não.'],'O significado do resultado decide o modelo de contagem.'),[['Situação','Ordem relevante?','Modelo simples'],['Presidente e secretário','Sim','Arranjo'],['Comissão sem cargos','Não','Combinação'],['Fila com todos os candidatos','Sim','Permutação']],'Os mesmos números podem aparecer em problemas que exigem contagens diferentes.'),
'info:1':D('Rastrear um algoritmo significa acompanhar o estado das variáveis. O computador executa a ordem escrita, não a intenção que você imagina.', ['Registrar valores após cada atribuição','Testar a condição de um laço na ordem correta','Distinguir operadores conforme a linguagem'],C('O valor atual é o que entra na próxima etapa',[
'Uma atribuição calcula a expressão e guarda o resultado na variável. Em x ← x + 2, o x à direita representa o valor anterior; o x à esquerda recebe o novo valor. Não é uma afirmação algébrica de que x sempre equivale a x + 2.',
'Num laço enquanto, a condição é testada antes de cada execução do corpo. Se começar falsa, o corpo pode não executar nenhuma vez. Após uma iteração, a condição deve ser testada novamente com o estado atualizado.',
'Os operadores de comparação importam. x < 6 e x ≤ 6 diferem quando x é exatamente 6. Esse pequeno detalhe pode mudar o número de repetições e o valor final. Uma tabela com “valor antes, condição, valor depois” ajuda a evitar uma volta extra.',
'A linguagem também importa. Em JavaScript, === faz comparação estrita, sem a conversão de tipos da igualdade não estrita. Em Python, // realiza divisão pelo piso e len obtém o comprimento de uma coleção. Não transfira automaticamente a sintaxe de uma linguagem para outra.'
]),W('Rastreie um laço até a condição ficar falsa','x começa em 2. Enquanto x < 6, execute x ← x + 2.', ['Teste 2 < 6: verdadeiro. Execute a soma: x passa a 4.','Teste 4 < 6: verdadeiro. Execute a soma: x passa a 6.','Teste 6 < 6: falso. Não execute outra soma.','O valor final é 6. Se a condição fosse x ≤ 6, ainda ocorreria uma soma e o resultado seria 8.'],'A condição é avaliada em cada estado, inclusive no que encerra o laço.'),[['Operação','Pergunta'],['Atribuição','Qual valor será guardado?'],['Comparação','A relação é verdadeira ou falsa?'],['Repetição','O bloco deve executar novamente?']],'Não use o valor inicial em todas as iterações: cada execução pode atualizar o estado.'),
'info:7':D('Copiar uma fórmula exige distinguir o que acompanha o deslocamento e o que deve continuar apontando para a mesma célula.', ['Interpretar referências relativas, absolutas e mistas','Prever uma fórmula copiada para baixo ou para o lado','Distinguir referência fixa de valor bloqueado'],C('Cada cifrão protege uma coordenada',[
'Uma referência como B2 possui coluna B e linha 2. Sem cifrão, ambas são relativas: podem se ajustar ao deslocamento da fórmula. Em $B$2, coluna e linha são absolutas. Em $B2, só a coluna está fixa; em B$2, só a linha.',
'Imagine a fórmula =A2*$B$2. A2 é o valor de cada linha; B2 guarda uma taxa compartilhada. Ao copiar uma linha abaixo, A2 vira A3 e $B$2 permanece igual. Ao copiar uma coluna à direita, A2 vira B2, mas a referência absoluta continua $B$2.',
'O cifrão controla a referência durante a cópia, não a edição do conteúdo da célula. Se a taxa em B2 mudar, as fórmulas que a utilizam podem recalcular. Proteção de planilha e bloqueio de células são outros recursos.',
'Funções, separadores e formatos podem depender da localização do software. SOMA e SUM são exemplos de nomes localizados. Em questões, observe qual programa e configuração foram declarados, sem presumir que todo ambiente usa a mesma grafia.'
]),W('Copie a taxa para várias linhas','A fórmula em C2 é =A2*$B$2. Você a copia para C3.', ['A fórmula se deslocou uma linha para baixo e nenhuma coluna.','A2 é relativa: sua linha aumenta para 3.','Em $B$2, as duas coordenadas estão fixas: a referência permanece.','A nova fórmula é =A3*$B$2.'],'Analise cada referência separadamente, mantendo o mesmo deslocamento.'),[['Referência','Coluna','Linha'],['B2','Relativa','Relativa'],['$B$2','Fixa','Fixa'],['$B2','Fixa','Relativa'],['B$2','Relativa','Fixa']],'Referência absoluta não torna o conteúdo da célula imutável.'),
'direito:0':D('Os princípios precisam ser reconhecidos em situações concretas. Para o cargo de designer, a finalidade da comunicação pública é um ponto especialmente importante.', ['Relacionar a publicidade à finalidade pública','Identificar indícios de promoção pessoal','Analisar os princípios em conjunto'],C('A mensagem deve servir ao cidadão',[
'A Constituição enumera no art. 37, caput, legalidade, impessoalidade, moralidade, publicidade e eficiência. Memorizar os nomes ajuda a reconhecer o dispositivo, mas a aplicação exige examinar o que foi feito e qual finalidade a atuação atende.',
'Uma peça que informa serviço, local e horário orienta o cidadão. Uma mensagem que usa a divulgação para exaltar pessoalmente uma autoridade apresenta outro foco. O art. 37, §1º trata do caráter da publicidade pública e veda elementos que caracterizem promoção pessoal.',
'Isso exige análise do conjunto e do contexto. A existência de alguma informação útil não legitima automaticamente uma parte promocional da mensagem. Na questão, separe o serviço divulgado da forma como uma autoridade é apresentada.',
'Eficiência também não deve ser isolada dos demais princípios. A justificativa de rapidez ou economia não afasta a legalidade. Uma decisão deve buscar finalidade pública dentro dos limites aplicáveis, em vez de escolher um princípio como autorização para ignorar os outros.'
]),W('Revise uma campanha de serviço','Um aviso informa vacinação, mas destaca uma frase de exaltação do gestor.', ['Identifique a informação necessária ao cidadão: serviço, data, local e condições.','Localize o elemento que promove a pessoa da autoridade.','Avalie esse elemento à luz da impessoalidade e da regra de publicidade do art. 37, §1º.','Reoriente a mensagem para a finalidade pública, preservando a informação de utilidade.'],'Qualidade visual e informação útil não dispensam a análise da finalidade da publicidade.'),[['Situação','Ponto central'],['Informar serviço e acesso','Finalidade de orientação ao cidadão'],['Exaltar pessoalmente uma autoridade','Risco de promoção pessoal'],['Justificar descumprimento pela rapidez','Eficiência não afasta legalidade']],'Consulte a redação constitucional completa. O exemplo ensina uma aplicação, não esgota todas as hipóteses jurídicas.'),
'municipio:3':D('Estudar a história administrativa exige ligar cada data a um acontecimento. Criação do distrito, criação do Município e instalação não são o mesmo marco.', ['Associar 1953, 1988 e 1989 aos acontecimentos','Distinguir vínculo distrital e condição municipal','Recuperar a cronologia sem trocar os nomes dos eventos'],C('A cronologia organiza etapas diferentes',[
'O histórico do IBGE registra a criação do distrito de Senador Canedo em 31/03/1953, pela Lei Municipal nº 239, subordinado a Goiânia. Esse marco não deve ser descrito como a instalação do Município.',
'A Lei Estadual nº 10.435, de 09/01/1988, elevou Senador Canedo à categoria de município. O mesmo histórico registra suspensão da execução da lei por medida cautelar em 15/07/1988. Essa informação impede reduzir a trajetória a uma data única sem contexto.',
'A instalação ocorreu em 01/06/1989. A distinção central para estudar é entre o ato legal e a etapa de instalação. Uma questão pode oferecer o ano correto ligado ao evento errado, exigindo atenção à combinação completa.',
'A leitura deve ser acompanhada da fonte. Use uma âncora inicial com três marcos e depois acrescente as datas completas, os atos e o contexto. Não substitua tudo por um rótulo genérico como “fundação”, porque ele pode ocultar a diferença que a questão pretende cobrar.'
]),W('Elimine uma alternativa que troca os marcos','Uma alternativa afirma: “o distrito foi criado em 1989 e o Município instalado em 1953”.', ['Localize os eventos citados, antes de avaliar apenas os números.','Associe distrito a 1953 e instalação a 1989.','Perceba que a alternativa usa datas presentes na história, mas inverte seus significados.','Reconstrua também o marco intermediário: lei de criação municipal em janeiro de 1988.'],'Memorizar pares evento–data é mais seguro que uma lista isolada de anos.'),[['Marco','Data','Identificação'],['Distrito','31/03/1953','Subordinado a Goiânia'],['Lei de criação municipal','09/01/1988','Lei Estadual 10.435'],['Instalação','01/06/1989','Etapa distinta da lei de criação']],'A presença de um ano verdadeiro não torna uma alternativa correta se o acontecimento estiver trocado.')
};
})();
