(function(){
'use strict';
const B=[
{id:'boost001',s:'pt',t:'Fonologia',d:'hard',q:'Na palavra “guerra”, quantos dígrafos consonantais aparecem na escrita?',o:['2','1','3','4'],a:0,e:'“gu” e “rr” representam dois dígrafos consonantais.',uid:'q482',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost002',s:'pt',t:'Tempos verbais',d:'hard',q:'Na frase “Se estudasse mais, conseguiria resolver a questão”, a forma “estudasse” está no:',o:['pretérito imperfeito do subjuntivo','pretérito perfeito do indicativo','futuro do subjuntivo','presente do subjuntivo'],a:0,e:'A forma “estudasse” é típica do pretérito imperfeito do subjuntivo.',uid:'q483',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost003',s:'pt',t:'Intertextualidade',d:'hard',q:'Quando uma campanha publicitária retoma deliberadamente um verso, uma obra ou uma frase conhecida para produzir novo sentido, há:',o:['intertextualidade','pleonasmo','metonímia','ambiguidade'],a:0,e:'Intertextualidade é a relação de um texto com outro texto ou conjunto de textos reconhecível.',uid:'q484',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost004',s:'pt',t:'Figurativização',d:'expert',q:'Em “A notícia caiu como uma bomba sobre a equipe”, a construção destaca principalmente:',o:['linguagem figurada por comparação/metáfora de impacto','uso literal de um explosivo','neutralidade denotativa','erro de regência'],a:0,e:'“Como uma bomba” cria sentido figurado para intensidade e impacto da notícia.',uid:'q485',source_type:'autoral',difficulty_label:'DESAFIO'},
{id:'boost005',s:'info',t:'Redes',d:'hard',q:'Qual serviço traduz nomes de domínio, como exemplo.gov.br, para endereços IP?',o:['DNS','DHCP','HTTP','SMTP'],a:0,e:'O DNS associa nomes de domínio a endereços IP e outros registros.',uid:'q486',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost006',s:'info',t:'Office',d:'hard',q:'Em uma planilha, a referência =$B$2 é classificada como:',o:['referência absoluta','referência relativa','referência mista de linha','nome definido obrigatório'],a:0,e:'Os cifrões fixam coluna e linha, caracterizando referência absoluta.',uid:'q487',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost007',s:'math',t:'Conjuntos',d:'hard',q:'Se A={1,2,3,4} e B={3,4,5}, então A∩B é:',o:['{3,4}','{1,2,3,4,5}','{1,2,5}','{3}'],a:0,e:'A interseção reúne os elementos que pertencem aos dois conjuntos: 3 e 4.',uid:'q488',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost008',s:'math',t:'Trigonometria',d:'hard',q:'Em um cálculo trigonométrico, qual é o valor de sen 30°?',o:['1/2','√3/2','1','0'],a:0,e:'O seno de 30° é igual a 1/2.',uid:'q489',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost009',s:'math',t:'Combinatória',d:'expert',q:'De quantas formas distintas é possível escolher 2 pessoas entre 5, sem importar a ordem?',o:['10','20','5','25'],a:0,e:'É uma combinação: C(5,2)=5!/(2!3!)=10.',uid:'q490',source_type:'autoral',difficulty_label:'DESAFIO'},
{id:'boost010',s:'direito',t:'Administração art 37',d:'hard',q:'Qual princípio do art. 37 da Constituição exige que a atuação administrativa não seja orientada por favorecimento pessoal?',o:['impessoalidade','publicidade','eficiência','continuidade'],a:0,e:'A impessoalidade impede tratamento voltado a interesses pessoais ou favorecimentos indevidos.',uid:'q491',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost011',s:'direito',t:'Lei 14.133',d:'hard',q:'Pela Lei 14.133/2021, a inexigibilidade de licitação ocorre quando:',o:['a competição é inviável','o valor é sempre inferior ao limite legal','há qualquer urgência administrativa','o objeto é necessariamente uma obra'],a:0,e:'A inexigibilidade pressupõe inviabilidade de competição.',uid:'q492',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost012',s:'direito',t:'Lei 14.133',d:'expert',q:'Qual das alternativas é modalidade de licitação prevista na Lei 14.133/2021?',o:['diálogo competitivo','credenciamento','dispensa','inexigibilidade'],a:0,e:'Diálogo competitivo é modalidade de licitação; credenciamento é procedimento auxiliar e dispensa/inexigibilidade são hipóteses de contratação direta.',uid:'q493',source_type:'autoral',difficulty_label:'DESAFIO'},
{id:'boost013',s:'direito',t:'Lei 14.133',d:'hard',q:'Na Lei 14.133/2021, o pregão é modalidade obrigatória para contratação de:',o:['bens e serviços comuns','qualquer obra de engenharia','bens imóveis','trabalhos artísticos premiados'],a:0,e:'A lei caracteriza o pregão como modalidade obrigatória para bens e serviços comuns.',uid:'q494',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost014',s:'municipio',t:'Câmara',d:'hard',q:'Segundo a Lei Orgânica de Senador Canedo, uma matéria sobre tributos municipais integra a competência da Câmara:',o:['com sanção do Prefeito','sempre sem participação do Executivo','apenas do Tribunal de Contas','somente por decreto legislativo'],a:0,e:'O art. 24 atribui à Câmara, com sanção do Prefeito, competência para dispor sobre matérias municipais, incluindo tributos.',uid:'q495',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost015',s:'municipio',t:'Câmara',d:'expert',q:'Segundo a Lei Orgânica de Senador Canedo, a Comissão Especial de Inquérito pode ser criada sobre fato determinado, a requerimento de pelo menos:',o:['um terço dos membros, com aprovação por maioria simples','metade dos membros, por unanimidade','um quinto dos membros, por dois terços','todos os membros, por maioria absoluta'],a:0,e:'O art. 25, VIII, prevê requerimento de pelo menos um terço e aprovação por maioria simples.',uid:'q496',source_type:'autoral',difficulty_label:'DESAFIO'},
{id:'boost016',s:'municipio',t:'Câmara',d:'expert',q:'Na apreciação das contas do Prefeito, a Lei Orgânica de Senador Canedo estabelece que o parecer prévio do Tribunal de Contas dos Municípios somente pode ser alterado por:',o:['dois terços dos membros da Câmara','maioria simples','maioria absoluta','unanimidade'],a:0,e:'O art. 25, XIV, estabelece a exigência de dois terços para alterar o parecer prévio.',uid:'q497',source_type:'autoral',difficulty_label:'DESAFIO'},
{id:'boost017',s:'municipio',t:'Estatuto',d:'hard',q:'Qual lei municipal é identificada em atos oficiais de 2026 como o Estatuto dos Servidores Públicos do Município de Senador Canedo?',o:['Lei Municipal nº 1.488/2010','Lei Municipal nº 1.435/2009','Lei Municipal nº 2.921/2025','Lei Municipal nº 1.489/2010'],a:0,e:'Atos oficiais municipais de 2026 identificam a Lei Municipal nº 1.488/2010 como o Estatuto dos Servidores Públicos Municipais.',uid:'q498',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost018',s:'municipio',t:'Vizinhança',d:'hard',q:'Segundo a caracterização municipal oficial, qual conjunto reúne municípios limítrofes de Senador Canedo?',o:['Bonfinópolis, Goiânia, Bela Vista, Aparecida de Goiânia e Caldazinha','Trindade, Nerópolis, Goianira, Guapó e Hidrolândia','Silvânia, Leopoldo de Bulhões, Anápolis e Goiânia','Cristianópolis, Piracanjuba, Hidrolândia e Aragoiânia'],a:0,e:'A caracterização municipal informa limites com Bonfinópolis, Goiânia, Bela Vista, Aparecida de Goiânia e Caldazinha.',uid:'q499',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost019',s:'municipio',t:'História',d:'hard',q:'Segundo o IBGE, Senador Canedo foi instalado como município em:',o:['1º de junho de 1989','31 de março de 1953','9 de janeiro de 1988','15 de julho de 1988'],a:0,e:'O IBGE registra a instalação do município em 1º de junho de 1989; a emancipação legal ocorreu em 1988.',uid:'q500',source_type:'autoral',difficulty_label:'Difícil'},
{id:'boost020',s:'municipio',t:'História',d:'hard',q:'Segundo o IBGE, em 31 de março de 1953 o povoado que originou Senador Canedo foi elevado à condição de:',o:['distrito, pertencendo a Goiânia','município autônomo','capital regional','comarca independente'],a:0,e:'O IBGE registra a elevação à condição de distrito, subordinado ao município de Goiânia, em 31 de março de 1953.',uid:'q501',source_type:'autoral',difficulty_label:'Difícil'}
];
QUESTIONS.push(...B);
EXTRA_FLASHCARDS.push(
{front:'Qual é o papel do DNS?',back:'Traduz nomes de domínio em registros como endereços IP.',hint:'Pense no “telefone” da Internet.'},
{front:'O que fixa uma referência =$B$2?',back:'Coluna e linha ficam absolutas porque ambas têm cifrão.',hint:'$ = não mover.'},
{front:'Quando há inexigibilidade?',back:'Quando a competição é inviável.',hint:'Não confunda com dispensa.'},
{front:'Qual lei é o Estatuto dos Servidores de Senador Canedo?',back:'Lei Municipal nº 1.488/2010.',hint:'Número local importante.'},
{front:'Quando Senador Canedo foi instalado?',back:'1º de junho de 1989.',hint:'Emancipação e instalação não são a mesma data.'}
);
render();
})();