/* Curriculum reviewed against Annex III (superior level), 30 September 2026.
 * Append modules to preserve existing localStorage module keys. */
(function(){
'use strict';
const cf='https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm';
const ibge='https://www.ibge.gov.br/biblioteca/visualizacao/dtb/goias/senadorcanedo.pdf';
const addLesson=(s,title,desc,sections,trap,check)=>{
 const i=MODULES[s].length;
 MODULES[s].push([title,desc]);
 LESSONS[s].push({title,module:i,summary:sections[0].split('\n').slice(1).join('\n'),sections,trap,check,minutes:9});
 ['explicar','aplicar','alerta'].forEach((kind,j)=>REVIEW_ACTIVITIES.push({uid:`RA-${s}-${i}-${j}`,s,m:i,title,kind,prompt:[`Explique a diferença central em ${title}, sem consultar.`,`Resolva ou analise o exemplo da aula de ${title}, justificando cada etapa.`,`Crie um contraexemplo à principal confusão em ${title}.`][j],answer:[sections[0],sections[2],trap][j],tip:'Compare o raciocínio e corrija o ponto específico; acertar o nome sozinho não basta.'}));
 EXTRA_FLASHCARDS.push({s,front:`${title}: qual confusão evitar?`,back:trap,hint:desc});
 return i;
};
addLesson('pt','Fonologia e divisão silábica','fonema × letra, dígrafos, encontros vocálicos/consonantais e sílabas',[
 'Som e escrita são camadas diferentes\nLetra é uma representação escrita; fonema é uma unidade sonora distintiva. Em “chave”, c+h representam um único som: 5 letras e 4 fonemas. Dígrafo é um par de letras representando um fonema; encontro consonantal preserva sons consonantais distintos, como pr em “prato”.',
 'Vogais na mesma sílaba ou em sílabas diferentes?\nDitongo reúne vogal e semivogal na mesma sílaba: pai. Tritongo reúne semivogal + vogal + semivogal: U-ru-guai. Hiato coloca vogais em sílabas distintas: sa-ú-de. Conte sons, depois separe sílabas. Não chame qualquer sequência de duas vogais de ditongo.',
 'Análise anotada\n“Guerra”: 6 letras; gu, com u não pronunciado, representa /g/; rr representa um som consonantal. Há dois dígrafos consonantais e 4 fonemas. Divisão: guer-ra. “Prato”: pra-to, pr é encontro consonantal. Em “linguiça”, o u é pronunciado: gu não funciona como dígrafo.',
 'Divisão silábica — aplicação\nSepare rr e ss entre sílabas: car-ro, pas-so. Mantenha ch, lh e nh: cha-ve, fi-lho, ni-nho. Uma sílaba tem núcleo vocálico. Compare sa-í-da (hiato) com cai-xa (ditongo); use a pronúncia, não só o aspecto da palavra.',
 'Fonemas e dígrafos — recuperação\nQuantas letras e quantos fonemas há em “chave”? Por que gu pode ser dígrafo em “guerra” mas não em “linguiça”? Explique o papel da pronúncia.'
], 'Gu/qu só são dígrafos consonantais quando o u não é pronunciado. Não confunda letra, fonema e sílaba.', ['Distinguir fonema e letra','Diferenciar dígrafo e encontro consonantal','Separar ditongo, hiato e tritongo','Justificar a divisão silábica'] );
addLesson('pt','Tempos, modos e flexão verbal','indicativo, subjuntivo, imperativo, tempos e valores no contexto',[
 'Modo expressa a atitude do enunciador\nIndicativo apresenta o fato como situado na realidade: “A equipe revisou”. Subjuntivo aparece em hipótese, desejo, dúvida ou condição: “Se a equipe revisasse”. Imperativo exprime ordem, pedido ou orientação: “Revise”. O valor temporal depende da forma e do contexto.',
 'Linha temporal com nuances\nPretérito perfeito: “publicou”, evento concluído. Imperfeito: “publicava”, hábito ou ação em curso no passado. Mais-que-perfeito: “publicara” ou “havia publicado”, anterior a outra ação passada. Presente pode expressar hábito ou verdade geral. Futuro do pretérito: “publicaria”, hipótese ou futuro visto de um passado.',
 'Compare construções\n“Se estudasse, conseguiria”: estudasse = imperfeito do subjuntivo; conseguiria = futuro do pretérito do indicativo. “Quando chegar, avisarei”: chegar = futuro do subjuntivo. Em “Quero chegar cedo”, chegar = infinitivo. A mesma aparência gráfica não assegura o mesmo modo.',
 'Flexão precisa acompanhar a construção\nPessoa e número ligam o verbo ao sujeito: eu reviso / nós revisamos. Em reescrita, mantenha a relação temporal: “Depois que terminou, enviou” não equivale a “Antes que terminasse, enviou”. O nome do tempo sozinho não explica todo o sentido.',
 'Subjuntivo e infinitivo — aplicação\nPor que “chegar” pode ser futuro do subjuntivo ou infinitivo? Dê dois contextos e identifique a relação temporal.'
], 'Não classifique uma forma verbal isolada. “Quando chegar” e “quero chegar” apresentam funções diferentes.', ['Distinguir os três modos','Comparar perfeito e imperfeito','Reconhecer hipótese no subjuntivo','Preservar tempo e sentido em reescrita']);
addLesson('math','Conjuntos e operações','pertinência, inclusão, igualdade, união, interseção e diferença',[
 'Elemento não é conjunto\nEm A={1,2,3}, 2∈A significa que o elemento 2 pertence a A. {2}⊆A significa que o conjunto unitário {2} está contido em A. A⊆B permite que sejam iguais; inclusão estrita exige A≠B. Conjuntos iguais têm os mesmos elementos, independentemente da ordem.',
 'Operações com significado\nA∪B reúne elementos de A ou B, incluindo os de ambos. A∩B contém apenas elementos comuns. A−B contém os que estão em A e não em B. ∅ é o conjunto sem elementos; {∅} possui um elemento. Complemento exige um universo U definido.',
 'Exemplo reconstruído\nA={1,2,3}; B={3,4}. Região só A: 1,2; região comum: 3; só B: 4. Assim A∪B={1,2,3,4}, A∩B={3}, A−B={1,2}, B−A={4}. União não repete o 3. Diferença não é simétrica.',
 'Contagem sem duplicar\nSe 18 servidores usam ferramenta A, 12 usam B e 5 usam ambas, 18+12−5=25 usam ao menos uma. Os cinco foram contados duas vezes na soma. A fórmula é |A∪B|=|A|+|B|−|A∩B|.',
 'Conjuntos — aplicação\nCom U={1,2,3,4,5}, A={1,2,3}, qual é o complemento de A? Explique por que ∅ e {∅} não são iguais.'
], '∈ liga elemento a conjunto; ⊆ liga conjunto a conjunto. Não troque união por interseção nem A−B por B−A.', ['Usar ∈ e ⊆','Calcular união e interseção','Calcular diferenças','Contar união sem duplicar']);
addLesson('math','Trigonometria no triângulo retângulo','hipotenusa, catetos, seno, cosseno, tangente e Pitágoras',[
 'Primeiro escolha o ângulo\nA hipotenusa é o lado oposto ao ângulo reto e o maior lado. Cateto oposto e adjacente dependem do ângulo agudo escolhido. Girar o desenho não muda relações: o que importa é o ângulo de referência.',
 'Razões, não nomes de lados\nsen θ = oposto/hipotenusa; cos θ = adjacente/hipotenusa; tan θ = oposto/adjacente. As razões são sem unidade. Pitágoras: h²=a²+b² permite achar um lado ausente. Triângulos semelhantes mantêm as razões mesmo mudando de tamanho.',
 'Exemplo 3–4–5\nPara θ com cateto oposto 3 e adjacente 4: h=√(3²+4²)=5. Portanto sen θ=3/5, cos θ=4/5 e tan θ=3/4. Se escolher o outro ângulo agudo, os catetos trocam de papel: seno passa a 4/5.',
 'Ângulos notáveis\n30°: seno 1/2, cosseno √3/2, tangente √3/3. 45°: seno e cosseno √2/2, tangente 1. 60°: seno √3/2, cosseno 1/2, tangente √3. Uma escada de 10 m formando 30° com o chão alcança 10×sen30°=5 m de altura.',
 'Trigonometria — aplicação\nDesenhe a escada, marque a hipotenusa e a altura. Qual razão usa altura e escada? Resolva primeiro sem consultar a tabela.'
], 'Cateto adjacente é relativo ao ângulo; hipotenusa é relativa ao ângulo reto. Não aplique seno sem marcar os lados.', ['Marcar lados pelo ângulo','Calcular três razões','Usar Pitágoras','Resolver problema de altura']);
addLesson('direito','CF — organização político-administrativa','arts. 18–19: entes autônomos, territórios, capital e vedações',[
 'Autonomia e soberania\nA República Federativa do Brasil é soberana; União, Estados, Distrito Federal e Municípios são autônomos, nos termos constitucionais. Autonomia não significa poder ilimitado nem independência internacional. Município não é subordinado hierarquicamente ao Estado como se fosse órgão estadual.',
 'Organize o art. 18\nO caput enumera os quatro tipos de entes. Brasília é a Capital Federal. Territórios federais integram a União e não entram nessa lista de entes autônomos. A organização de novos entes depende dos requisitos constitucionais e legais; não decorre de decisão isolada do prefeito.',
 'Caso de comparação\nPergunta: Brasília e Distrito Federal são sinônimos jurídicos? Não: Brasília é a capital; DF é ente federativo. Uma secretaria municipal é órgão do Município, não um quinto tipo de ente federativo.',
 'Art. 19: três vedações\nOs entes não podem estabelecer cultos/igrejas, subvencioná-los, embaraçar seu funcionamento ou manter dependência/aliança, ressalvada a colaboração de interesse público na forma da lei; não podem recusar fé a documentos públicos; nem criar distinções entre brasileiros ou preferências entre si. A ressalva não equivale a autorização geral para aliança religiosa.',
 'Leia com foco\nFonte: Constituição, arts. 18 e 19. Distinga capital, ente autônomo, território e órgão. Regras de criação/fusão de municípios exigem leitura da redação vigente e legislação complementar indicada na fonte oficial.'
], 'Soberania é da República; autonomia é dos entes. Território federal integra a União; Brasília é capital, não um ente adicional.', ['Enumerar os entes','Distinguir autonomia e soberania','Identificar capital e território','Explicar as vedações do art. 19']);
LESSONS.direito[16].source=cf;
addLesson('design','Softwares, raster, vetor e editoração','Illustrator/CorelDRAW/Inkscape; Photoshop/GIMP; InDesign/Scribus; fluxo e exportação',[
 'A tarefa decide a ferramenta\nVetor descreve formas por curvas e coordenadas: é adequado a símbolos escaláveis. Raster organiza pixels: é apropriado a fotografias e pintura. Editoração organiza páginas e estilos de publicações. Uma ferramenta pode ter recursos de outra categoria; classifique pelo uso principal, sem afirmar exclusividade.',
 'Mapa por finalidade\nIllustrator, CorelDRAW e Inkscape: criação e edição vetorial. Photoshop e GIMP: tratamento raster. InDesign e Scribus: diagramação/editoração. Inkscape usa SVG como formato nativo; exportar um vetor para PNG rasteriza a saída. A existência de texto/vetor em Photoshop não o transforma em editor vetorial principal.',
 'Fluxo de uma cartilha\n1. Prepare foto com máscara e ajustes preservando o original. 2. Crie/valide símbolos vetoriais. 3. Monte páginas com estilos, margens, links de imagens e hierarquia. 4. Revise e faça preflight. 5. Exporte conforme gráfica ou distribuição digital. Arquivo editável e arquivo de entrega têm finalidades diferentes.',
 'Resolução e edição não destrutiva\nUma foto de 1800 pixels de largura a 300 ppi permite 6 polegadas, aproximadamente 15,24 cm, sem interpolação. Dobrar o tamanho físico cai para 150 ppi. Mudar apenas o número de ppi não inventa detalhe. Camadas de ajuste e máscaras permitem revisar alterações sem destruir o original.',
 'Contraexemplo e decisão\nUm brasão só existe como miniatura PNG: salvar em SVG não reconstrói curvas automaticamente. Procure a versão oficial vetorial; um arquivo pode conter raster dentro de SVG/PDF. PDF não garante, por si só, vetor nem qualidade de impressão.'
], 'Extensão não garante a natureza do conteúdo. Escolha ferramenta e exportação pelo destino; preserve editáveis e fontes/licenças.', ['Relacionar sete ferramentas à finalidade','Distinguir vetor/raster/editoração','Planejar fluxo de cartilha','Calcular resolução no tamanho final']);
addLesson('design','Apresentações institucionais','hierarquia, síntese, contraste, gráficos, leitura e consistência',[
 'Slide orienta uma exposição\nDefina a ideia principal e a ação/compreensão esperada. Título informativo, informação de apoio e evidência precisam de hierarquia. Uma apresentação pode ser projetada para exposição oral ou leitura autônoma; a densidade deve respeitar esse destino.',
 'Composição que ensina\nMantenha estilos consistentes, margens, alinhamentos e contraste. Ajuste o tamanho à distância de leitura, não a um número universal. Diagramas e gráficos devem permitir entender relações. Efeitos só ajudam quando revelam a sequência de raciocínio; movimentos decorativos disputam atenção.',
 'Antes e depois\nAntes: título “Dados”, 12 linhas e tabela ilegível. Depois: título “Tempo de atendimento caiu 18%”, dois indicadores com o período e fonte, gráfico comparável e nota metodológica. A síntese não pode ocultar ressalvas, recortes ou denominadores.',
 'Revisão da peça pública\nConfira números, datas, unidades, fonte dos dados, identidade institucional, contraste, ordem de leitura e acessibilidade. Para compartilhar, verifique PDF ou arquivo editável, se animações eram essenciais e se a exportação mantém textos/descrições necessários.',
 'Recupere e aplique\nComo mostrar aumento de 100 para 110 sem exagerar? Uma barra com base zero mostra a diferença proporcional; uma escala truncada exige justificativa/contexto e pode induzir erro. Explique as escolhas e o público.'
], 'Síntese não é ocultar contexto. Um gráfico visualmente atraente pode distorcer dados; uma ideia por slide não é regra absoluta para todo formato.', ['Definir finalidade e público','Construir hierarquia','Conferir gráfico e fonte','Adaptar para exposição e compartilhamento']);
// Correct the noun-phrase reference in lesson/review/flashcard consistently.
const coesion='Em “A Câmara publicou o edital. O documento traz o conteúdo da prova”, a expressão nominal “o documento” retoma “edital” e produz coesão referencial por substituição lexical. Em “Esse documento traz…”, “esse” é pronome demonstrativo. Coesão pode existir mesmo se o sentido global for contraditório.';
LESSONS.pt[2].sections[2]='Exemplo aplicado\n'+coesion;
REVIEW_ACTIVITIES.filter(a=>a.s==='pt'&&a.m===2&&a.kind==='aplicar').forEach(a=>a.answer=coesion);
EXTRA_FLASHCARDS.forEach(a=>{if(a.back?.includes('o pronome demonstrativo retoma “edital”'))a.back=coesion});
// Fill prerequisites explicitly, rather than leaving them only in questions.
LESSONS.info[1].sections.splice(3,0,'Rastreie valores e operadores\nEm Python, len([10,20,30]) conta três elementos; 7 // 2 faz divisão pelo piso e resulta em 3. Em JavaScript, === compara sem converter tipos: 7 === "7" é falso. No laço x=2; enquanto x<6, some 2: estados 2→4→6, então a condição fica falsa. Montar uma tabela de estados evita executar uma volta a mais.');
LESSONS.info[7].sections.splice(3,0,'Referências de planilha\nAo copiar =A1*B1 uma linha abaixo, vira =A2*B2: referências relativas. =$B$2 fixa coluna e linha; =$B2 fixa coluna, B$2 fixa linha. Se B2 guarda a taxa, =A5*$B$2 mantém a taxa ao copiar. Funções podem ter nomes/separadores localizados: SUM/SOMA, vírgula/ponto e vírgula conforme configuração. Não confunda referência absoluta com valor imutável: o conteúdo da célula ainda pode mudar.');
LESSONS.math[11].sections.splice(3,0,'Ordem e repetição decidem o cálculo\nPermutação simples: P(n)=n!, organiza todos. Arranjo sem repetição: A(n,k)=n!/(n−k)!, escolhe k e ordena. Combinação sem repetição: C(n,k)=n!/[k!(n−k)!], escolhe sem ordenar. De cinco pessoas para presidente e secretário: 5×4=20; para comissão de dois membros sem cargos: 20/2!=10. Divida por k! porque cada grupo foi contado em todas as ordens.');
LESSONS.math[13].sections.splice(3,0,'Valor extremo muda medidas de formas diferentes\nEm 2,3,4,5,100: média=114/5=22,8; mediana=4; não há moda. A média usa todos os valores e é puxada pelo 100. Para quantidade par, ordene e tire a média dos dois centrais: 3,5,8,10 → (5+8)/2=6,5. Um conjunto pode ser amodal, unimodal ou multimodal.');
LESSONS.design[8].sections.splice(3,0,'Mistura e gama\nNa luz RGB ideal: vermelho+verde=amarelo; verde+azul=ciano; azul+vermelho=magenta; os três no máximo=branco; ausência de luz=preto. Na mistura subtrativa ideal, ciano+magenta=azul, magenta+amarelo=vermelho, amarelo+ciano=verde. CMY ideal absorve luz; a tinta preta K melhora pretos e controle em processos reais. Perfis e suporte limitam a gama: converter não garante aparência idêntica.');
LESSONS.design[9].sections.splice(3,0,'Veja relações no círculo\nDeclare o modelo cromático usado. Complementares ficam a 180°, triádicas a 120° entre si; análogas ocupam setores vizinhos. No círculo RGB/HSV, vermelho e ciano são opostos. No círculo artístico RYB, a relação tradicional é vermelho e verde. Não misture modelos. Matiz identifica a família, saturação a intensidade, valor/luminosidade o claro-escuro; contraste de matiz sozinho não garante leitura de texto.');
LESSONS.municipio[3].sections.splice(3,0,'Cronologia com fonte\nIBGE: distrito pela Lei Municipal nº 239, de 31/03/1953, subordinado a Goiânia. Lei Estadual nº 10.435, de 09/01/1988, elevou à categoria de município; o histórico também registra suspensão por medida cautelar em 15/07/1988. Instalação em 01/06/1989. Desmembramento de Goiânia, Bela Vista de Goiás e Aparecida de Goiânia. Não simplifique todas as etapas como “fundação em 1989”.');
LESSONS.municipio[3].source=ibge;
// A legal number verified in official 2026 acts is not a consolidated statute lesson.
LESSONS.municipio[13].sections.splice(1,0,'O que já foi identificado e o que precisa de texto\nAtos oficiais municipais de 2026 identificam a Lei nº 1.488/2010 como Estatuto. Esse número não basta para aprender direitos, prazos ou penalidades. Esta aula é um roteiro inicial de leitura; a redação consolidada e suas alterações precisam ser cotejadas antes de memorizar regras específicas.');
LESSONS.municipio[13].source='https://diario.senadorcanedo.go.gov.br/detalhes/13531';
const newQ=(uid,s,t,d,q,o,a,e)=>QUESTIONS.push({uid,id:uid,s,t,d,difficulty_label:{easy:'Fácil',medium:'Médio',hard:'Difícil',expert:'DESAFIO'}[d],q,o,a,e,source_type:'autoral'});
newQ('audit-01','pt','Fonologia','medium','Em “chave”, quantas letras e quantos fonemas há?', ['5 letras e 4 fonemas','5 letras e 5 fonemas','4 letras e 5 fonemas','4 letras e 4 fonemas'],0,'São cinco letras. O dígrafo ch representa um único fonema consonantal, portanto há quatro fonemas.');
newQ('audit-02','pt','Tempos verbais','medium','Em “Quando chegar, avisarei”, e em “Quero chegar cedo”, a forma chegar é, respectivamente:', ['futuro do subjuntivo e infinitivo','infinitivo e futuro do subjuntivo','futuro do indicativo em ambos','presente do subjuntivo e infinitivo'],0,'O primeiro contexto projeta situação futura em oração temporal. No segundo, chegar funciona como infinitivo ligado a quero.');
newQ('audit-03','math','Conjuntos','medium','Se 18 pessoas usam A, 12 usam B e 5 usam ambos, quantas usam ao menos um?', ['25','30','35','7'],0,'A soma 18+12 conta os cinco usuários de ambas duas vezes. Subtraia a interseção: 18+12−5=25.');
newQ('audit-04','math','Trigonometria','medium','Uma escada de 10 m forma 30° com o chão. Usando sen30°=1/2, a altura alcançada é:', ['5 m','10 m','20 m','5√3 m'],0,'A escada é a hipotenusa; a altura é o cateto oposto a 30°. sen30°=altura/10, portanto altura=10×1/2=5 m.');
newQ('audit-05','direito','CF 18-19','medium','Segundo o art. 18 da Constituição, os Territórios Federais:', ['integram a União','são municípios autônomos','são entes federativos soberanos','integram necessariamente o Distrito Federal'],0,'O §2º do art. 18 dispõe que Territórios Federais integram a União; não são um quinto tipo de ente autônomo.');
newQ('audit-06','direito','CF 18-19','medium','Qual prática é vedada aos entes federativos pelo art. 19 da Constituição?', ['recusar fé aos documentos públicos','colaborar em interesse público na forma da lei','organizar a própria administração dentro da Constituição','exercer autonomia nos limites constitucionais'],0,'Art. 19, II. Autonomia não afasta vedações. A colaboração religiosa de interesse público tem ressalva específica na forma da lei.');
newQ('audit-07','design','Software gráfico','medium','Uma equipe prepara foto, brasão vetorial e cartilha multipágina. Qual sequência de ferramentas corresponde às finalidades principais?', ['GIMP → Inkscape → Scribus','Inkscape → Scribus → GIMP','Scribus → GIMP → Inkscape','GIMP → Scribus → Inkscape'],0,'GIMP trata raster; Inkscape edita vetor; Scribus é editoração. As três tarefas se integram, mas possuem finalidades principais diferentes.');
newQ('audit-08','design','Resolução','medium','Uma imagem com 1800 pixels de largura, sem interpolação, mede quanto a 300 ppi?', ['6 polegadas','3 polegadas','12 polegadas','18 polegadas'],0,'Largura física=pixels/ppi=1800/300=6 polegadas. Aumentar a largura para 12 polegadas reduz a densidade para 150 ppi.');
newQ('audit-09','design','Apresentações','medium','Um slide compara 100 e 110 com barras iniciadas em 95, dando impressão de enorme diferença. A revisão prioritária é:', ['corrigir ou contextualizar a escala para não exagerar a diferença','aumentar o peso do título mantendo a escala','padronizar somente a cor das barras','reduzir a fonte para incluir mais números'],0,'O problema é a codificação visual: bases truncadas nas barras distorcem proporções. Hierarquia estética não corrige a representação numérica.');
newQ('audit-10','municipio','História','medium','Segundo o IBGE, a Lei Estadual de janeiro de 1988 e o evento de junho de 1989 correspondem, respectivamente, a:', ['criação legal do município e instalação','criação do distrito e emancipação','instalação e criação legal do município','promulgação da Lei Orgânica e criação do distrito'],0,'A lei de 09/01/1988 elevou o município; a instalação ocorreu em 01/06/1989. A criação do distrito pertence a 1953.');
// Regrade direct-retrieval boost questions; difficulty is editorial, not statistical.
const easy=new Set(['q483','q484','q486','q487','q488','q489','q491','q492','q493','q494','q500','q501','q502','q503','q504','q510','q511']);
const medium=new Set(['q482','q485','q490','q495','q496','q497','q498','q499','q505','q506','q507','q508','q509','q512','q513','q514','q515','q516']);
QUESTIONS.forEach(q=>{if(easy.has(q.uid))q.d='easy';if(medium.has(q.uid))q.d='medium';q.difficulty_label={easy:'Fácil',medium:'Médio',hard:'Difícil',expert:'DESAFIO'}[q.d];});
})();
