/* Canedo Quest — trilha obrigatória por matéria: escolha 1 de 3, feche a matéria inteira, então receba novas opções. */
(function(){'use strict';
const V=2,DAY=86400000,INT=[1,3,7,14,30].map(d=>d*DAY);
const N={pt:'Português',info:'Informática',math:'Matemática',direito:'Direito',municipio:'Senador Canedo',design:'Design Gráfico'};
const I={pt:'📚',info:'💻',math:'∑',direito:'⚖️',municipio:'🏙️',design:'🎨'};
const bad=/^(Como pode aparecer|Autoexplicação|Resumo de bolso|Antes de consultar|Antes de olhar|Recupere sem olhar|Teste de transferência|Recupere o mecanismo)/i;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sh=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const subj=s=>N[s]||s,key=(s,i)=>s+':'+i;
function mods(s){return (MODULES[s]||[]).map((m,i)=>({s,i,key:key(s,i),title:m[0],desc:m[1],lesson:LESSONS[s]?.[i]})).filter(x=>x.lesson)}
function subjects(){return Object.keys(MODULES||{}).filter(s=>mods(s).length)}
function qs(s,i){try{return (moduleQuestions(s,i)||[]).filter(q=>Array.isArray(q.o)&&q.o.length===4&&Number.isInteger(q.a))}catch(e){return []}}
function sections(l){return (l?.sections||[]).map(x=>{let a=String(x).split('\n');return {t:(a.shift()||'').replace(/^[^\p{L}\p{N}]+/u,''),b:a.join('\n').trim()}}).filter(x=>x.t&&x.b&&!bad.test(x.t))}
function save(){try{window.save?.()}catch(e){}}
function xp(n){try{window.addXP?.(n)}catch(e){}}
function root(){let r=document.getElementById('cq-forced');if(!r){document.body.innerHTML='<div id="cq-forced"></div>';r=document.getElementById('cq-forced')}return r}
function path(){let p=state.subjectPath;if(!p||p.v!==V){p={v:V,done:{},choice:[],active:null,review:{},note:''};state.subjectPath=p;save()}return p}
function completeSubjects(){return subjects().filter(s=>path().done[s]?.done)}
function due(){let now=Date.now(),p=path(),out=[];subjects().forEach(s=>mods(s).forEach(m=>{let x=p.review[m.key];if(x?.done&&x.next<=now)out.push(m)}));return out.sort((a,b)=>path().review[a.key].next-path().review[b.key].next)}
function choices(){let p=path();let r=(p.choice||[]).filter(s=>subjects().includes(s)&&!p.done[s]?.done);if(r.length)return r;if(subjects().every(s=>p.done[s]?.done)){p.choice=[];return []}let left=subjects().filter(s=>!p.done[s]?.done);p.choice=sh(left).slice(0,Math.min(3,left.length));save();return p.choice}
function frame(title,mode){let p=path(),active=p.active,total=mods(active?.s||'').length,idx=active?.mi||0,pc=Math.round((idx/Math.max(1,total))*100);return `<div class="cq-session"><button class="cq-x" onclick="CQForced.leave()" aria-label="Voltar">×</button><div><span>${esc(subj(active?.s||''))}</span><strong>${esc(title)}</strong></div><div class="cq-session-progress"><small>${esc(mode||'Estudo')} · módulo ${Math.min(idx+1,total)}/${total}</small><i><b style="width:${pc}%"></b></i></div></div>`}
function page(inner,active='home'){root().innerHTML=`<header class="cq-header"><div class="cq-logo"><b>CQ</b><span><strong>CANEDO QUEST</strong><small>Trilha de aprovação</small></span></div><nav><button class="${active==='home'?'on':''}" onclick="CQForced.home()">Trilha</button><button class="${active==='review'?'on':''}" onclick="CQForced.reviews()">Revisões${due().length?`<em>${due().length}</em>`:''}</button><button class="${active==='errors'?'on':''}" onclick="CQForced.errors()">Erros</button><button class="${active==='method'?'on':''}" onclick="CQForced.method()">Método</button></nav><div class="cq-count"><b>${completeSubjects().length}/${subjects().length}</b><small>matérias fechadas</small></div></header><main class="cq-main">${inner}</main>`;scrollTo(0,0)}
function home(){let p=path(),d=due(),all=completeSubjects().length===subjects().length;
 if(p.active?.s){let s=p.active.s,m=mods(s)[p.active.mi];return page(`<section class="cq-hero compact"><div><span>SESSÃO EM ANDAMENTO</span><h1>Você ainda não fechou ${esc(subj(s))}.</h1><p>Uma matéria escolhida não libera novas matérias até que todos os módulos dela sejam concluídos. O progresso fica salvo.</p></div><strong class="cq-big">${p.active.mi+1}/${mods(s).length}<small>módulo atual</small></strong></section><section class="cq-gate"><div class="cq-gate-icon">▶</div><div><span>CONTINUE DE ONDE PAROU</span><h2>${esc(m?.title||subj(s))}</h2><p>${esc(m?.desc||'Retome o estudo obrigatório.')}</p><button class="cq-btn primary" onclick="CQForced.resume()">Continuar estudo →</button></div></section>`)}
 if(d.length)return page(`<section class="cq-hero compact"><div><span>MEMÓRIA EM DIA</span><h1>Antes de matéria nova, você precisa recuperar o que já estudou.</h1><p>As revisões programadas são parte da trilha. Enquanto houver revisão vencida, novas matérias ficam bloqueadas.</p></div><strong class="cq-big">${d.length}<small>revisões devidas</small></strong></section><section class="cq-gate"><div class="cq-gate-icon">🧠</div><div><span>BLOQUEIO DE CONTEÚDO NOVO</span><h2>Faça a revisão de hoje.</h2><p>${d.slice(0,5).map(m=>esc(subj(m.s)+' · '+m.title)).join('<br>')}</p><button class="cq-btn primary" onclick="CQForced.startDue()">Começar revisão →</button></div></section>`,'home');
 if(all)return page(`<section class="cq-hero"><div><span>PERCURSO COMPLETO</span><h1>Você fechou todas as matérias.</h1><p>Agora o trabalho é manter o conhecimento acessível. Use Revisões para recuperar qualquer módulo e o Caderno de Erros para atacar falhas específicas.</p></div><strong class="cq-big">✓<small>${subjects().length} matérias</small></strong></section><section class="cq-gate"><div class="cq-gate-icon">🧠</div><div><span>FASE DE CONSOLIDAÇÃO</span><h2>Nada de simulados livres para “passar o tempo”.</h2><p>A trilha nova termina aqui; o conteúdo continua voltando por espaçamento.</p><button class="cq-btn primary" onclick="CQForced.reviews()">Abrir revisões →</button></div></section>`,'home');
 let c=choices();return page(`<section class="cq-hero"><div><span>PRÓXIMA ESCOLHA</span><h1>Você recebe 3 matérias. Escolhe 1.</h1><p>As opções são sorteadas entre as matérias restantes. Depois de escolher, você não pode trocar: precisa concluir todos os módulos daquela matéria.</p><div class="cq-bar"><b style="width:${Math.round(completeSubjects().length/Math.max(1,subjects().length)*100)}%"></b></div><small>${completeSubjects().length} de ${subjects().length} matérias fechadas</small></div><strong class="cq-big">3<small>opções sorteadas</small></strong></section>/section><h2 class="cq-section-title">Escolha uma matéria para começar</h2><section class="cq-choice-grid">${c.map((s,i)=>{let ms=mods(s),q=ms.reduce((n,m)=>n+qs(s,m.i).length,0);return `<article class="cq-choice"><span class="cq-num">0${i+1}</span><div class="cq-subject">${I[s]||'📘'} ${esc(subj(s))}</div><h2>Estudar ${esc(subj(s))}</h2><p>${ms.length} módulos obrigatórios nesta matéria. O estudo avança sozinho até fechar todos eles.</p><div><b>${ms.length}</b> módulos <b>${q}</b> questões ligadas</div><button class="cq-btn primary" onclick="CQForced.choose('${s}')">Escolher esta matéria →</button></article>`}).join('')}</section><section class="cq-science"><b>🧠 Por que esse fluxo é duro?</b><p>Leitura não encerra uma etapa. Você precisa tentar lembrar, escrever o mecanismo com suas palavras, responder questões sem consulta e refazer os erros.</p></section>`,'home')}
function choose(s){let p=path();if(!subjects().includes(s)||p.done[s]?.done||p.active)return;p.choice=[];p.active={s,mi:0,phase:'diag',di:0,diag:{},teach:0,recall:{},qi:0,qa:{},order:{},wrong:[],retry:[]};save();render()}
function cur(){let a=path().active;if(!a)return null;let m=mods(a.s)[a.mi];return m?{a,m}:null}
function qpick(s,i,n,exclude=[]){let all=sh(qs(s,i)),u=new Set(exclude),r=[];for(let q of all)if(!u.has(q.uid)){r.push(q);if(r.length>=n)break}return r}
function startModule(){let c=cur();if(!c)return;let a=c.a;const m=mods(a.s)[a.mi];let pre=qpick(m.s,m.i,2),ret=qpick(m.s,m.i,Math.min(5,qs(m.s,m.i).length),pre.map(q=>q.uid));a.pre=pre.map(q=>q.uid);a.ret=ret.map(q=>q.uid);a.phase='diag';a.di=0;a.diag={};a.teach=0;a.recall={};a.qi=0;a.qa={};a.order={};a.wrong=[];a.retry=[];a.started=Date.now();save();render()}
function render(){let c=cur();if(!c){home();return}let a=c.a;if(!a.pre)startModule();else if(a.phase==='diag')diag(c);else if(a.phase==='teach')teach(c);else if(a.phase==='retrieve')retrieve(c,false);else if(a.phase==='retry')retrieve(c,true);else if(a.phase==='review')reviewSession(c)}
function opts(q,a,chosen){a.order=a.order||{};a.order[q.uid] ||= sh([0,1,2,3]);let o=a.order[q.uid];return `<div class="cq-options">${o.map((j,k)=>`<button class="cq-option ${chosen!=null?(j===q.a?'ok':j===chosen?'bad':''):''}" ${chosen!=null?'disabled':''} onclick="CQForced.answerQ(${j})"><span>${'ABCD'[k]}</span>${esc(q.o[j])}</button>`).join('')}</div>`}
function diag(c){let a=c.a,q=QUESTIONS.find(x=>x.uid===a.pre[a.di]),v=a.diag[q?.uid],txt=v==null?'':v;page(frame(c.m.title,'Diagnóstico')+`<section class="cq-card"><span>1 · DIAGNÓSTICO</span><h1>Recupere antes de estudar.</h1><p>Errar aqui não tira ponto. Serve para descobrir o que você já consegue lembrar sem consulta.</p><h2>${esc(q.q)}</h2>${opts(q,a, v)}${v!=null?`<div class="cq-feedback ${v===q.a?'good':'bad'}"><b>${v===q.a?'Você recuperou.':'Esse ponto precisa de atenção.'}</b><p>${esc(q.e)}</p></div><button class="cq-btn primary" onclick="CQForced.nextDiag()">Continuar →</button>`:''}</section>`,'home')}
function answerQ(j){let c=cur();if(!c)return;let a=c.a,qid=a.phase==='diag'?a.pre[a.di]:a.phase==='review'?a.rq[a.ri]:a.phase==='retrieve'?a.ret[a.qi]:a.retry[a.qi],q=QUESTIONS.find(x=>x.uid===qid);if(!q)return;if(a.phase==='diag'){if(a.diag[qid]!=null)return;a.diag[qid]=j;try{recordAnswer(q,j===q.a)}catch(e){}save();render()}else if(a.phase==='review'){if(a.ra[qid])return;a.ra[qid]={v:j,c:j===q.a};try{recordAnswer(q,j===q.a)}catch(e){}save();render()}else if(a.phase==='retrieve'){if(a.qa[qid])return;a.qa[qid]={v:j,c:j===q.a};try{recordAnswer(q,j===q.a)}catch(e){}if(j!==q.a&&!a.retry.includes(qid))a.retry.push(qid);save();render()}else if(a.phase==='retry'){if(a.qa[qid]?.retryed)return;a.qa[qid]={v:j,c:j===q.a,retryed:true};try{recordAnswer(q,j===q.a)}catch(e){}save();render()}}
function nextDiag(){let c=cur(),a=c.a;if(a.di<a.pre.length-1){a.di++;save();render()}else{a.phase='teach';a.teach=0;save();render()}}
function teach(c){let a=c.a,s=c.m,l=sections(s.lesson),x=l[a.teach];if(!x){a.phase='retrieve';a.qi=0;save();return render()}let note=a.recall[a.teach]||'';page(frame(s.title,'Estudo ativo')+`<section class="cq-card"><span>2 · ESTUDO ATIVO · BLOCO ${a.teach+1}/${l.length}</span><h1>${esc(x.t)}</h1><div class="cq-text">${esc(x.b).split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div><div class="cq-recall"><label>Agora feche o texto. Escreva, de memória, a regra, diferença, passo de resolução ou exemplo principal.</label><textarea id="cq-note" maxlength="900" placeholder="Não copie. Explique com suas palavras.">${esc(note)}</textarea><button class="cq-btn primary" onclick="CQForced.saveRecall()">${note.trim().length>=20?'Próximo bloco →':'Registrar e liberar próximo bloco'}</button><small>${note.length}/900 · mínimo 20 caracteres</small></div></section>`,'home')}
function saveRecall(){let c=cur(),v=document.getElementById('cq-note')?.value.trim()||'';if(v.length<20)return;path().active.recall[path().active.teach]=v;save();let a=path().active,l=sections(c.m.lesson);if(a.teach<l.length-1)a.teach++;else{a.phase='retrieve';a.qi=0}render()}
function retrieve(c,retry){let a=c.a,ids=retry?a.retry:a.ret,q=QUESTIONS.find(x=>x.uid===ids[a.qi]);if(!q)return finishModule(c);let ans=a.qa[q.uid],label=retry?'4 · RETOMADA OBRIGATÓRIA':'3 · RECUPERAÇÃO SEM CONSULTA';page(frame(c.m.title,retry?'Retomada':'Recuperação')+`<section class="cq-card"><span>${label}</span><h1>${esc(q.q)}</h1><p>${retry?'Você errou este ponto. A questão continua voltando até acertar.':'Responda sem olhar o conteúdo. A explicação aparece depois da tentativa.'}</p>${opts(q,a,ans?.v)}${ans?`<div class="cq-feedback ${ans.c?'good':'bad'}"><b>${ans.c?'Correto.':'Incorreto.'}</b><p>${esc(q.e)}</p>${!ans.c?'<small>Esse ponto volta antes de liberar a próxima etapa.</small>':''}</div><button class="cq-btn primary" onclick="CQForced.nextRetrieve()">Continuar →</button>`:''}</section>`,'home')}
function nextRetrieve(){let c=cur(),a=c.a;if(a.phase==='retrieve'){if(a.qi<a.ret.length-1){a.qi++;save();return render()}a.retry=a.ret.filter(id=>!a.qa[id]?.c);a.qi=0;if(a.retry.length){a.phase='retry';save();return render()}return finishModule(c)}if(a.phase==='retry'){let id=a.retry[a.qi];if(a.qa[id]?.c){a.retry.splice(a.qi,1)}else{a.qi++;}if(!a.retry.length)return finishModule(c);if(a.qi>=a.retry.length)a.qi=0;save();render()}}
function finishModule(c){let a=c.a,s=c.m,k=s.key,now=Date.now();path().review[k]={done:true,reviews:0,stage:0,next:now+INT[0]};if(a.mi<mods(a.s).length-1){a.mi++;delete a.pre;save();xp(15);render()}else{path().done[a.s]={done:true,at:now};path().choice=[];path().active=null;save();xp(30);completion(s)}}
function completion(m){page(`<section class="cq-completion"><span>MATÉRIA CONCLUÍDA</span><div>✓</div><h1>${esc(subj(m.s))} fechada.</h1><p>Você terminou todos os módulos obrigatórios desta matéria. A próxima rodada será sorteada entre as matérias restantes.</p><button class="cq-btn primary" onclick="CQForced.home()">Receber novas opções →</button><button class="cq-btn" onclick="CQForced.reviews()">Ver revisões</button></section>`,'home')}
function startDue(){let d=due()[0];if(!d)return home();startReview(d,false)}
function startReview(m,manual){let p=path();p.active={s:m.s,mi:m.i,phase:'review',ri:0,rq:qpick(m.s,m.i,Math.min(5,qs(m.s,m.i).length)).map(q=>q.uid),ra:{},manual,order:{},retry:[]};save();render()}
function reviewSession(c){let a=c.a,q=QUESTIONS.find(x=>x.uid===a.rq[a.ri]);if(!q)return finishReview(c);let an=a.ra[q.uid];page(frame(c.m.title,'Revisão espaçada')+`<section class="cq-card"><span>🧠 REVISÃO ${a.manual?'MANUAL':'PROGRAMADA'}</span><h1>Force a lembrança antes de consultar.</h1><p>${a.manual?'Você pediu para revisitar este módulo. Primeiro tente recuperar; o resumo só aparece depois.':'A revisão chegou pelo intervalo programado. Tente lembrar sem abrir a aula.'}</p>${opts(q,a,an?.v)}${an?`<div class="cq-feedback ${an.c?'good':'bad'}"><b>${an.c?'Recuperou.':'Precisa reforçar.'}</b><p>${esc(q.e)}</p><details><summary>Ver trecho do conteúdo</summary>${sections(c.m.lesson).slice(0,2).map(x=>`<h3>${esc(x.t)}</h3><p>${esc(x.b)}</p>`).join('')}</details></div><button class="cq-btn primary" onclick="CQForced.nextReview()">${a.ri===a.rq.length-1?'Concluir revisão':'Próxima →'}</button>`:''}</section>`,'review')}
function answerReview(j){let c=cur(),a=c.a,q=QUESTIONS.find(x=>x.uid===a.rq[a.ri]);if(!q||a.ra[q.uid])return;a.ra[q.uid]={v:j,c:j===q.a};try{recordAnswer(q,j===q.a)}catch(e){}save();render()}
function nextReview(){let c=cur(),a=c.a,q=QUESTIONS.find(x=>x.uid===a.rq[a.ri]);if(!q||!a.ra[q.uid])return;if(a.ra[q.uid].c)a.score=(a.score||0)+1;a.ri++;if(a.ri<a.rq.length){save();render()}else finishReview(c)}
function finishReview(c){let p=path(),a=c.a,k=c.m.key,x=p.review[k],now=Date.now(),score=a.score||0,total=a.rq.length,pass=total?score/total>=.8:true;if(!a.manual&&x){x.reviews=(x.reviews||0)+1;if(pass)x.stage=Math.min(INT.length-1,(x.stage||0)+1);x.next=now+INT[pass?(x.stage||0):0]}p.active=null;save();page(`<section class="cq-completion"><span>REVISÃO ${pass?'CONCLUÍDA':'PRECISA DE REFORÇO'}</span><div>${pass?'✓':'↻'}</div><h1>${pass?'Memória recuperada.':'Vamos manter este ponto em intervalo curto.'}</h1><p>${score}/${total} acertos. ${pass?'O próximo intervalo foi ampliado.':'A próxima revisão continuará próxima.'}</p><button class="cq-btn primary" onclick="CQForced.home()">Voltar à trilha →</button></section>`,'review')}
function reviews(){let p=path(),groups={};subjects().forEach(s=>{let arr=mods(s).filter(m=>p.review[m.key]?.done);if(arr.length)groups[s]=arr});let html=Object.entries(groups).map(([s,arr])=>`<section class="cq-review-group"><h2>${I[s]||'📘'} ${esc(subj(s))}</h2>${arr.map(m=>{let r=p.review[m.key],d=r.next<=Date.now();return `<article><div><b>${esc(m.title)}</b><small>${esc(m.desc)}</small><span>${r.reviews||0} revisão(ões) · ${d?'disponível agora':'programada'}</span></div><button class="cq-btn ${d?'primary':''}" onclick="CQForced.revisit('${m.key}')">${d?'Revisar agora':'Revisitar'}</button></article>`}).join('')}</section>`).join('');page(`<section class="cq-hero compact"><div><span>REVISÕES E REVISITA</span><h1>Aqui você pode voltar ao conteúdo já conquistado.</h1><p>Revisão programada é obrigatória; revisita manual não libera matéria nova nem altera a trilha.</p></div><strong class="cq-big">${due().length}<small>devidas</small></strong></section>${due().length?`<section class="cq-gate"><div class="cq-gate-icon">🧠</div><div><h2>${due().length} revisão(ões) bloqueando conteúdo novo.</h2><button class="cq-btn primary" onclick="CQForced.startDue()">Fazer revisão →</button></div></section>`:''}${html||'<section class="cq-card"><h2>Nenhuma matéria concluída ainda.</h2><p>Volte à Trilha para receber as primeiras três opções.</p></section>'}`,'review')}
function revisit(k){let [s,i]=k.split(':');let m=mods(s)[+i];if(m)startReview(m,true)}
function errors(){let ids=Object.keys(state.wrong||{}).filter(k=>state.wrong[k]),qsx=ids.map(id=>(QUESTIONS||[]).find(q=>q.uid===id)).filter(Boolean);page(`<section class="cq-hero compact"><div><span>CADERNO DE ERROS</span><h1>Questões que provaram que ainda falta recuperação.</h1><p>Erros não somem quando você vê a alternativa certa. Eles ficam disponíveis aqui para uma nova tentativa.</p></div><strong class="cq-big">${qsx.length}<small>erros ativos</small></strong></section>${qsx.length?`<section class="cq-error-list">${qsx.map(q=>`<article><div><b>${esc(subj(q.s))}</b><h3>${esc(q.q)}</h3><small>${esc(q.e)}</small></div><button class="cq-btn primary" onclick="CQForced.error('${q.uid}')">Revisar</button></article>`).join('')}</section>`:'<section class="cq-card"><h2>✅ Nenhum erro pendente.</h2><p>Quando você errar uma questão, ela aparece aqui.</p></section>'}`,'errors')}
function error(uid){let q=QUESTIONS.find(x=>x.uid===uid);if(!q)return;let i=q.modules?.[0]??0,m=mods(q.s)[i];if(!m)return;startReview({...m},true);let a=path().active;a.rq=[uid];a.ri=0;save();render()}
function method(){page(`<section class="cq-hero compact"><div><span>MÉTODO</span><h1>O sistema foi desenhado para lembrar, não só reconhecer.</h1><p>O percurso usa prática de recuperação, estudo distribuído e retomada de erros.</p></div></section><section class="cq-method"><article><b>01</b><h2>Recuperação ativa</h2><p>Depois de estudar, você precisa responder sem consultar. A tentativa vem antes da explicação.</p><a href="https://journals.sagepub.com/doi/pdf/10.1177/1529100612453266" target="_blank">Dunlosky et al. (2013) ↗</a></article><article><b>02</b><h2>Prática distribuída</h2><p>O mesmo módulo volta em 1, 3, 7, 14 e 30 dias quando as revisões são bem recuperadas.</p><a href="https://pubmed.ncbi.nlm.nih.gov/16719566/" target="_blank">Cepeda et al. (2006) ↗</a></article><article><b>03</b><h2>Explicar com palavras próprias</h2><p>Cada bloco exige uma reconstrução curta de memória. Copiar o texto não libera o próximo bloco.</p></article><article><b>04</b><h2>Erro não é fim</h2><p>Questões erradas voltam antes da conclusão; a revisão espaçada retorna depois.</p></article></section><section class="cq-card"><h2>O que foi removido</h2><p>Provas livres, simulados para pular conteúdo, seleção arbitrária de matérias, avanço só por leitura e páginas cheias de frases genéricas.</p></section>`,'method')}
function leave(){save();home()}
function resume(){render()}
window.CQForced={home,reviews,errors,method,choose,resume,leave,startDue,revisit,error,answerQ,nextDiag,saveRecall,nextRetrieve,answerReview,nextReview};
function boot(){state.quiz=null;state.guideView=false;state.page='home';path();home()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
