/* Definitions precede recognition and practice; stable module IDs preserve saved sessions. */
(function(){
'use strict';
const P=[];
const lesson=(i,intro,parts,worked)=>P[i]={intro,parts,worked};
lesson(0,'Interpretar é construir uma leitura que o texto sustenta. Vamos separar informação escrita, informação implícita e opinião de quem lê.',[
['Explícito, inferência e pressuposto','Explícito é o que está escrito: “A loja fecha às 18h” informa diretamente o horário. Inferência é uma conclusão apoiada em pistas: “O chão está molhado e há guarda-chuvas pingando” permite inferir chuva recente, mas não prova que choveu a noite inteira. Pressuposto é uma informação implícita acionada por uma expressão: em “Lia voltou a estudar”, “voltou” indica que ela já estudava antes. Mesmo em “Lia não voltou a estudar”, esse estudo anterior continua pressuposto.'],
['Paráfrase e extrapolação','Paráfrase reformula uma informação preservando seu sentido: “As inscrições terminam hoje” → “Hoje é o último dia para se inscrever”. Extrapolação acrescenta algo sem apoio: concluir que haverá prorrogação apenas porque o prazo termina hoje. Repare que inferir não é inventar uma continuação possível.'],
['Contexto, ironia e ambiguidade','Contexto é a situação que ajuda a interpretar a mensagem. Ironia cria contraste entre o que se diz e o que se pretende comunicar: chamar de “maravilhoso” um atraso, em uma reclamação, sugere crítica. Ambiguidade permite mais de uma leitura: “Lia disse a Bia que seu crachá sumiu” não esclarece de quem era o crachá. Referente é a pessoa, objeto ou ideia retomada por uma expressão; “seu” tem dois referentes possíveis nessa frase.'],
['Verbal, não verbal e intertextualidade','Linguagem verbal usa palavras; a não verbal usa recursos como imagem, gesto e cor. Um cartaz pode combinar as duas: isso é multimodalidade. Intertextualidade acontece quando um texto retoma outro, como um anúncio que adapta um verso conhecido. Para interpretar, observe o que essa retomada acrescenta. Sucessão temporal é ordem no tempo (“depois que”); ela, sozinha, não comprova causa.']
],['“O aplicativo reduziu as filas, mas ainda há espera às segundas.”','“Reduziu” informa melhora. “Mas” introduz uma limitação. “Ainda há” mostra permanência parcial. A conclusão sustentada é melhora sem eliminação total; dizer “resolveu tudo” apaga a segunda parte.']);
lesson(1,'Gênero e tipo textual respondem a perguntas diferentes: que comunicação é esta e como as ideias estão organizadas?',[
['Gênero: o texto em uma situação real','Gênero é uma forma de comunicação reconhecida pelo uso e pela finalidade. Ofício trata formalmente de assunto oficial entre instituições ou autoridades; notícia relata fatos de interesse público; artigo de opinião defende uma posição; ata registra o que ocorreu em uma reunião; cartaz divulga ou orienta por uma composição breve, frequentemente com imagens. O tamanho, sozinho, não determina o gênero.'],
['Os cinco tipos mais comuns','Narração apresenta acontecimentos no tempo: “Ela chegou, abriu a sala e iniciou o atendimento”. Descrição apresenta características: “A sala era pequena e iluminada”. Exposição explica um assunto: “O atendimento funciona por agendamento”. Argumentação defende uma tese com razões: “É preciso ampliar o horário, pois a procura cresceu”. Injunção orienta uma ação: “Preencha o nome e clique em enviar”. Textos instrucionais usam frequentemente injunção.'],
['Tese, argumento e finalidade','Tese é a posição defendida; argumento é a razão usada para sustentá-la. Em “Devemos ampliar o horário porque a fila aumentou”, a primeira parte é a tese e a segunda é o argumento. Finalidade é o que o texto procura fazer: informar, orientar, convencer, registrar ou entreter. Um gênero pode combinar tipos: uma notícia pode narrar um fato e descrever o local.'],
['Outros gêneros que aparecem nas alternativas','Divulgação científica explica conhecimento científico a um público não especializado. Crônica costuma desenvolver uma observação do cotidiano. Tirinha articula quadros, frequentemente com humor. Verbete apresenta informação organizada sobre uma entrada de dicionário ou enciclopédia. Bilhete transmite uma mensagem breve. Identifique a função antes de escolher um nome.']
],['“Lave as mãos. Use água e sabão. Seque com papel.” em um cartaz de saúde.','O gênero é cartaz: comunicação visual dirigida ao público. O tipo predominante é injuntivo: os verbos orientam ações. O tema saúde não transforma automaticamente o cartaz em artigo científico.']);
lesson(2,'As partes de um texto precisam estar ligadas e produzir um sentido compatível. Essas duas necessidades se chamam coesão e coerência.',[
['Frase, oração e período','Frase é um enunciado com sentido em uma situação: “Silêncio!” é frase sem verbo. Oração é uma estrutura organizada em torno de um verbo ou locução verbal: “A equipe chegou”. Período contém uma ou mais orações: “A equipe chegou e abriu a sala” é um período composto. Uma locução verbal, como “vai estudar”, funciona como unidade verbal; não conte automaticamente cada forma como uma oração.'],
['Coesão referencial: como retomar','Coesão é a ligação entre partes do texto. Na coesão referencial, uma expressão retoma ou antecipa outra: “Lia chegou. Ela trouxe o arquivo”. “Ela” retoma Lia, seu referente. Uma expressão equivalente também retoma: “O relatório foi aprovado. Esse documento será publicado”. Elipse é omitir algo recuperável: “Lia trouxe os cartazes; Bia, os convites” omite “trouxe” na segunda parte.'],
['Anáfora, catáfora e conectivos','Anáfora referencial retoma algo já mencionado: “Lia chegou. Ela...”. Catáfora antecipa algo que será apresentado: “Só quero isto: respeito”. Conectivos marcam relações: “e” pode adicionar, “mas” contrapor e “portanto” concluir. Eles ajudam a ligação, mas não garantem que a informação faça sentido.'],
['Coerência e progressão','Coerência é compatibilidade de sentido no contexto. “A mesma reunião já terminou e ainda não começou”, sem uma explicação especial, é contraditório mesmo com ligação gramatical. Progressão temática é acrescentar informação relevante ao assunto. Repetir a mesma afirmação com palavras diferentes pode manter a ligação e ainda assim não fazer o texto avançar.']
],['“O conselho publicou uma nota. Ela esclarece os horários.”','Primeiro localize “Ela”. Depois procure um referente compatível: “uma nota”, feminino singular. A retomada evita repetir “nota” e liga as duas frases: coesão referencial.']);
lesson(3,'A língua muda conforme pessoas e situações. Estudar adequação é aprender a escolher recursos para um contexto, sem tratar diferenças de fala como falta de inteligência.',[
['As dimensões da variação','Variação regional envolve usos de lugares diferentes, como “mandioca”, “aipim” e “macaxeira”. Variação social envolve grupos, profissões e comunidades. Variação histórica ocorre ao longo do tempo. Variação situacional depende da circunstância: a mesma pessoa pode falar de um jeito entre amigos e de outro em uma apresentação formal.'],
['Registro e norma-padrão','Registro é o modo de usar a língua em uma situação, incluindo grau de formalidade e escolha de palavras. Norma-padrão é um modelo de referência codificado em gramáticas e convenções, cobrado em contextos formais. Não representa todos os usos reais da língua. Adequação é a relação entre a forma escolhida e o público, a finalidade e a situação.'],
['Clareza em comunicação institucional','Vocabulário técnico é próprio de uma área: “regência”, por exemplo, é um termo técnico da gramática. Se o cidadão precisa de uma instrução, explique termos indispensáveis e prefira palavras que ele compreenda. Formalidade não exige frases difíceis nem excesso de adjetivos.']
],['Mensagem ao cidadão: “Compareça munido da documentação supracitada.”','“Traga os documentos indicados acima” preserva a orientação e facilita a compreensão. A troca é uma escolha de clareza para o público; não significa que toda linguagem informal seja adequada a documentos oficiais.']);
lesson(4,'Antes de decorar regras de acentuação, precisamos saber dividir sílabas e encontrar a parte pronunciada com mais força.',[
['Sílaba tônica e acento gráfico','Sílaba é uma unidade de pronúncia. Em ca-FÉ, “fé” é a sílaba tônica, pronunciada com maior destaque. Acento gráfico é o sinal escrito, como ´ e ^. Uma palavra pode ter sílaba tônica sem acento gráfico: CA-sa tem tonicidade em “ca” e nenhum sinal escrito. O til marca nasalidade e não deve ser confundido com as regras de acento agudo ou circunflexo.'],
['Oxítona, paroxítona e proparoxítona','Oxítona tem a última sílaba tônica: ca-FÉ, pa-PEL. Paroxítona tem a penúltima: TÓ-rax, ca-DEI-ra. Proparoxítona tem a antepenúltima: MÉ-di-co, LÂM-pa-da. Monossílabo tem uma só sílaba: “pá” é tônico; o artigo “o”, em “o livro”, é átono. Primeiro identifique a posição tônica, depois a terminação.'],
['Regras frequentes de acentuação','Todas as proparoxítonas recebem acento. Oxítonas terminadas em a, e, o, em e ens recebem acento, com s quando cabível: sofá, cafés, avó, também, parabéns. Monossílabos tônicos terminados em a, e, o, seguidos ou não de s, também: pá, pés, pó. Ditongos abertos éi, éu e ói recebem acento em oxítonas e monossílabos tônicos: herói, céu, papéis.'],
['Paroxítonas e encontros vocálicos','Entre as terminações acentuadas das paroxítonas estão l, n, r, x, ps, i/is, us, um/uns, ã/ãs, ão/ãos e ditongo: fácil, hífen, açúcar, tórax, bíceps, júri, vírus, álbum, órfã, órgão, história. “Hifens” não recebe o acento de “hífen”. Ditongo reúne vogal e semivogal na mesma sílaba; hiato separa vogais em sílabas diferentes. Em sa-í-da, o i tônico em hiato recebe acento pela regra aplicável. Há exceções: “rainha” não recebe esse acento antes de nh.'],
['Ortografia e mudanças','Ortografia é a convenção de escrita: a grafia é “exceção”, com xc e ç; não se deduz apenas pelo som. “Ideia” e “heroico” perderam o acento nos ditongos abertos de paroxítonas; “voo” e “leem” não têm circunflexo. Não use a regra das oxítonas para justificar uma paroxítona.']
],['Por que “tórax” tem acento?','Separe TÓ-rax: duas sílabas. A forte é a penúltima, portanto é paroxítona. A palavra termina em x. A justificativa combina classificação e terminação: paroxítona terminada em x.']);
lesson(5,'O sinal à registra a fusão de dois sons a. Para reconhecê-la, primeiro entenda preposição e artigo.',[
['As duas peças: preposição e artigo','Preposição liga termos: em “entreguei o documento a alguém”, o a introduz o destinatário. Artigo acompanha um substantivo: “a diretora”, “o diretor”. Na frase “Entreguei o documento à diretora”, o verbo pede a para o destinatário e “diretora” vem com artigo a. A soma é a + a = à. Regência é justamente a relação que faz um verbo ou nome exigir determinado complemento e, às vezes, uma preposição.'],
['O teste e seus limites','Troque o termo feminino por um masculino equivalente: “entreguei ao diretor”. Ao = a + o; na estrutura feminina correspondente aparece à. A troca precisa manter o sentido e a regência. Não basta a próxima palavra ser feminina: “Vi a diretora” tem apenas artigo, porque ver alguém não exige preposição a.'],
['Casos que não recebem e casos que variam','Antes de verbo, como “começou a trabalhar”, não há artigo feminino: sem crase. “A pé” tem palavra masculina; “a ele” tem pronome pessoal que não admite esse artigo. Em “referiu-se a pessoas”, o a singular não se funde com um artigo plural; “às pessoas” é outra construção. Antes de possessivo feminino singular, o artigo pode ser facultativo: “entreguei a sua chefe” ou “à sua chefe”, conforme o uso do artigo.'],
['Demonstrativos, horas e expressões','“Referiu-se àquelas normas” reúne a preposição a e o a inicial de “aquelas”; não há artigo separado nesse caso. Horário determinado pode receber crase: “a reunião começa às oito”. Em “de segunda a sexta”, o paralelismo de...a ocorre sem artigos. Locuções femininas consagradas podem usar o sinal: “à tarde”, “às vezes”. Estude a construção completa, sem aplicar automaticamente o teste de uma palavra isolada.']
],['Compare “Vi a professora” e “Respondi à professora”.','Ver alguém pede complemento direto: o a é artigo. Responder a alguém introduz destinatário com a: preposição + artigo. Por isso a segunda frase tem à e a primeira não.']);
lesson(6,'Classe gramatical é a categoria da palavra; função sintática é o papel dela na frase. Vamos conhecer as classes antes de pedir uma classificação.',[
['Substantivo, artigo, adjetivo e numeral','Substantivo nomeia seres, objetos, ações, sentimentos e ideias: equipe, relatório, leitura, alegria. Artigo acompanha o substantivo e o apresenta como definido (o, a, os, as) ou indefinido (um, uma, uns, umas). Adjetivo atribui característica ao substantivo: relatório claro, equipe atenta. Numeral expressa quantidade ou ordem: dois relatórios, primeiro lugar. Em “Os dois relatórios claros”, cada palavra desempenha uma dessas classes.'],
['Verbo e advérbio','Verbo expressa processos, ações, estados ou fenômenos e varia em tempo, modo, pessoa e número: revisar, estar, chover. Advérbio modifica verbo, adjetivo ou outro advérbio: “chegou cedo”, “muito claro”, “muito rapidamente”. Pode indicar tempo, lugar, modo, intensidade, negação etc. Em “leu rapidamente”, a palavra diz como leu: advérbio de modo. Em “leitura rápida”, “rápida” caracteriza o substantivo: adjetivo. A terminação -mente é uma pista frequente, não uma definição de todos os advérbios.'],
['Pronome e suas referências','Pronome pode substituir ou acompanhar um nome: “Lia chegou. Ela trouxe seu arquivo”. “Ela” é pessoal e retoma Lia; “seu” é possessivo. “Este” é demonstrativo, “alguém” é indefinido e “quem”, em uma pergunta, é interrogativo. Pronome relativo retoma um antecedente e introduz uma oração sobre ele: “O arquivo que chegou”. Nesse caso, que = o qual.'],
['Preposição, conjunção e interjeição','Preposição liga termos: “arquivo de imagem”, “fui a Goiânia”. Conjunção liga orações ou termos de mesma função: “Lia e Bia”, “estudou, mas errou”. Interjeição expressa reação: “Ufa!”, “Nossa!”. Uma palavra pode mudar de classe conforme o uso: “o jantar” tem substantivo; “vou jantar” tem verbo.'],
['Estrutura e formação da palavra','Radical é a parte que concentra o sentido lexical: feliz em felizmente. Prefixo vem antes da base: des- em desleal. Sufixo vem depois: -mente em felizmente. Afixo é o nome geral de prefixos e sufixos. “Infelizmente” envolve in- + feliz + -mente: prefixação e sufixação. Não é parassíntese, pois existem “infeliz” e “felizmente” independentemente. Composição reúne bases, como guarda-chuva; abreviação reduz uma forma, como foto de fotografia.'],
['Flexão e desinência','Flexão adapta a palavra a categorias gramaticais: relatório/relatórios, clara/claras, estudo/estudamos. Desinência é um elemento que pode marcar essa variação: o -s de livros indica plural. Em verbos, as terminações podem indicar tempo, modo, pessoa e número. Não confunda esse ajuste gramatical com criar outra palavra por prefixo ou sufixo.']
],['“As duas servidoras revisaram cuidadosamente o aviso claro.”','As: artigo; duas: numeral; servidoras e aviso: substantivos; revisaram: verbo; cuidadosamente: advérbio, pois modifica como revisaram; o: artigo; claro: adjetivo, pois caracteriza aviso. Para diferenciar os dois últimos tipos, descubra qual palavra está sendo modificada.']);
lesson(7,'Sintaxe estuda as relações entre as partes de uma oração. Os nomes abaixo descrevem funções; não são sinônimos das classes gramaticais.',[
['Sujeito, núcleo e predicado','Sujeito é o termo com o qual o verbo normalmente concorda e sobre o qual se declara algo. Em “As servidoras revisaram o aviso”, o sujeito é “As servidoras”; seu núcleo, a palavra central, é “servidoras”. Predicado é o que se declara do sujeito: “revisaram o aviso”. Na passiva “O aviso foi revisado”, o sujeito é “O aviso”, embora não pratique a ação. Por isso “quem faz a ação” é uma pista insuficiente.'],
['Transitividade, objeto direto e indireto','Verbo transitivo pede complemento no uso analisado. Objeto direto completa o verbo sem preposição exigida: “A equipe revisou o aviso” → revisou o quê? o aviso. Objeto indireto vem com preposição exigida: “A equipe precisa de apoio” → precisa de quê? de apoio. “Entregou o aviso ao diretor” tem direto (o aviso) e indireto (ao diretor). Verbo intransitivo não exige esse objeto: “O bebê nasceu”. A transitividade depende do sentido e da construção.'],
['Predicativo: uma característica atribuída','Verbo de ligação relaciona sujeito e estado ou característica: “A equipe permaneceu tranquila”. Tranquila é predicativo do sujeito. Predicativo do objeto atribui característica ao objeto: “A equipe considerou o aviso claro”. O aviso é objeto direto; claro é a avaliação atribuída a ele. Compare “revisou o aviso claro”: aqui claro pode apenas especificar qual aviso foi revisado, como adjunto adnominal.'],
['Adjuntos e complemento nominal','Adjunto adverbial indica circunstância, como tempo, lugar ou modo: “A equipe revisou ontem”, “trabalhou na sala”. Adjunto adnominal acompanha e caracteriza ou determina um substantivo: “os dois avisos novos”. Complemento nominal completa o sentido de um nome, adjetivo ou advérbio com preposição: “necessidade de ajuda”, “favorável ao projeto”. No primeiro, de ajuda completa o substantivo necessidade; não é objeto verbal.'],
['Aposto, vocativo e agente da passiva','Aposto explica ou especifica outro termo: “Lia, diretora do setor, chegou”. Vocativo chama o interlocutor: “Lia, revise o aviso”. Agente da passiva indica quem realiza a ação em uma construção passiva: “O aviso foi revisado pela equipe”. Pela equipe é agente; o aviso é sujeito paciente. Compare as relações, não apenas a posição.'],
['Uma oração inteira pode ser sujeito','Em “É necessário que todos estudem”, substitua “que todos estudem” por “isso”: “Isso é necessário”. A oração exerce função de sujeito e é chamada oração subordinada substantiva subjetiva. Em “Os relatórios que chegaram foram publicados”, os relatórios é sujeito de foram publicados; que chegaram caracteriza relatórios.']
],['“Ontem, os servidores entregaram os documentos à diretora.”','Verbo: entregaram. Quem entregou? Os servidores: sujeito, núcleo servidores. Entregaram o quê? Os documentos: objeto direto. A quem? À diretora: objeto indireto. Quando? Ontem: adjunto adverbial de tempo. O predicado contém o verbo, os complementos e a circunstância.']);
lesson(8,'Orações se relacionam pela estrutura e pelo sentido. Primeiro identifique os verbos; depois veja como uma oração se liga à outra.',[
['Coordenação e os nomes da classificação','Na coordenação, uma oração não funciona como termo da outra: “Estudei e revisei”. Coordenada é a oração nessa relação. Sindética significa ligada por conjunção; assindética significa sem conjunção: “Cheguei, sentei, estudei”. “Adversativa” significa oposição. Portanto “coordenada sindética adversativa” reúne três informações: relação coordenada + conjunção + contraste.'],
['Relações na coordenação','Aditiva soma: “estudou e revisou”. Adversativa contrasta: “estudou, mas errou”. Alternativa apresenta alternância: “ou lê ou escreve”. Conclusiva indica conclusão: “treinou, portanto melhorou”. Explicativa justifica uma orientação ou declaração: “Leve o casaco, porque está frio”. A palavra precisa ser interpretada no contexto.'],
['Substantiva e adjetiva','Na subordinação, uma oração exerce função em outra. Substantiva ocupa função típica de substantivo: “Espero que você venha” → espero isso, objeto direto. Adjetiva caracteriza um nome: “O arquivo que chegou é novo” → que chegou caracteriza arquivo. Conjunção integrante introduz oração substantiva, como o que em “Espero que venha”; pronome relativo retoma antecedente, como que = o qual em “o arquivo que chegou”.'],
['Adverbiais: circunstâncias','Oração adverbial indica circunstância: causa (“faltou porque adoeceu”), tempo (“quando chegou, ligou”), condição (“se estudar, aprenderá”), concessão (“embora estivesse cansado, estudou”), finalidade (“estudou para que aprendesse”), consequência (“estudou tanto que cansou”), comparação (“corre como o irmão”), conformidade (“fez conforme combinamos”) e proporção (“quanto mais lê, mais aprende”). Concessão é um obstáculo que não impede o fato; condição é uma hipótese da qual depende o outro fato.'],
['Restrição e explicação','“Os alunos que estudaram passaram” seleciona o grupo que estudou: oração adjetiva restritiva, sem vírgulas. “Os alunos, que estudaram, passaram” acrescenta uma explicação sobre o grupo referido: explicativa, entre vírgulas. A pontuação altera quais alunos estão sendo considerados.']
],['“Embora estivesse cansada, Lia revisou o texto.”','Há duas unidades verbais: estivesse e revisou. O cansaço poderia dificultar a revisão, mas ela aconteceu. A primeira oração indica concessão; é subordinada adverbial concessiva. Não é causa: o cansaço não está apresentado como motivo da revisão.']);
lesson(9,'Regência trata do complemento exigido; concordância trata da combinação de formas. Vamos separar as duas relações.',[
['Regência verbal e nominal','Regência verbal é a relação do verbo com seu complemento. Assistir, no sentido de presenciar, pede a: “assistiu ao filme”, “assistiu à palestra”. Obedecer pede a: “obedeceu ao regulamento”. Preferir compara X a Y: “prefere ler a sair”, sem “mais” e sem “do que” nessa estrutura formal. Regência nominal é a relação de um nome: “favorável ao projeto”, “necessidade de apoio”.'],
['Concordância verbal e núcleo','O verbo normalmente concorda em pessoa e número com o núcleo do sujeito: “O servidor chegou”; “Os servidores chegaram”. O núcleo é o centro do grupo: em “A equipe dos servidores chegou”, é equipe, singular; servidores está dentro de um termo que acompanha equipe. A ordem pode mudar: “Chegaram os servidores”.'],
['Verbos impessoais','Verbo impessoal não tem sujeito e fica na terceira pessoa do singular. Haver no sentido de existir: “Havia dúvidas”, não “haviam dúvidas”. Fazer indicando tempo decorrido: “Faz dois anos”, não “fazem dois anos”. Já existir tem sujeito: “Existem dúvidas”. Não transfira automaticamente a regra de haver para existir.'],
['Concordância nominal e expressões','Concordância nominal ajusta determinantes e adjetivos ao nome: “os documentos anexos”, “as folhas anexas”. Em “Seguem anexos os documentos”, seguem concorda verbalmente com documentos; anexos concorda nominalmente com documentos. “Mais de um servidor participou” normalmente tem singular; há exceções em repetição e reciprocidade. “Nenhum deles participou” também tem núcleo singular. Verbo defectivo é aquele cujo paradigma não apresenta todas as formas de conjugação; isso não explica a concordância de “mais de um”.']
],['“Seguem anexos os documentos solicitados.”','Reorganize: “Os documentos solicitados seguem anexos”. O núcleo documentos é plural, então seguem fica no plural. Anexos caracteriza documentos, masculino plural. Há concordância verbal e nominal na mesma frase.']);
lesson(10,'Pronomes oblíquos átonos são formas como me, te, se, o, a, lhe, nos, vos, os, as e lhes. A colocação pronominal estuda onde ficam em relação ao verbo.',[
['Três posições, três nomes','Próclise: pronome antes do verbo — “não me avisaram”. Ênclise: depois do verbo, ligado por hífen — “avisaram-me”. Mesóclise: no interior de uma forma de futuro — “avisar-me-ão”. Os nomes descrevem posição, não tempo verbal nem o sentido da frase.'],
['Quando ocorre próclise','Palavras negativas atraem o pronome: “Não se preocupe”. Pronomes relativos e conjunções subordinativas também podem atrair: “o documento que me enviaram”, “quando me avisarem”. Advérbio sem pausa pode favorecer próclise: “Aqui se trabalha”. Primeiro procure esse elemento antes de aplicar uma regra de posição.'],
['Ênclise e mesóclise na norma formal','No início de oração formal, sem fator de atração, usa-se tradicionalmente ênclise: “Entregaram-me o documento”. Na fala brasileira, “Me entregaram” é comum, mas a prova pode cobrar a norma formal. A mesóclise ocorre com futuro do presente ou do pretérito, sem fator de próclise: “Enviar-lhe-ei a resposta”; com negação: “Não lhe enviarei a resposta”.'],
['Posição não é voz verbal','Apassivação é transformar ou construir uma estrutura passiva: “Vendem-se casas” corresponde a “Casas são vendidas”. Isso é diferente de dizer onde se encontra o pronome. Em “Não se deve ignorar o contexto”, se aparece antes de deve: a posição é próclise. Uma questão sobre posição não pede a função do se.']
],['“Nunca me disseram isso.”','Localize o pronome me. Ele vem antes de disseram: próclise. Nunca tem valor negativo e atrai o pronome nessa construção. A justificativa reúne a posição observada e o fator que a favorece.']);
lesson(11,'A pontuação torna visíveis as relações entre os termos. Antes de usar uma regra de vírgula, conheça o nome e a função do trecho separado.',[
['Vocativo e aposto','Vocativo chama a pessoa com quem se fala: “Senhores, enviem o arquivo”. Senhores não é o sujeito de enviem; é o chamamento, separado por vírgula. Aposto explicativo acrescenta informação sobre um termo: “Lia, diretora do setor, chegou”. Diretora do setor explica quem é Lia e fica isolado.'],
['Intercalação e deslocamento','Uma informação intercalada se insere no meio da estrutura: “O designer, responsável pelo fechamento, revisou o arquivo”. A dupla de vírgulas marca o trecho inserido; não autoriza separar sujeito e verbo sem intercalação. Circunstâncias deslocadas podem ser marcadas: “Após a revisão, os arquivos foram enviados”. Em adjuntos curtos, a vírgula pode ser facultativa conforme a construção.'],
['O que não se separa diretamente','Não separe sujeito e verbo só porque o sujeito é longo: “Os servidores do setor de comunicação chegaram”. Também não separe verbo e seu complemento direto apenas por uma pausa de leitura: “A equipe revisou o arquivo”. Uma intercalação entre eles pode exigir dois sinais; ela é uma estrutura diferente.'],
['Explicativa ou restritiva','“Os servidores, que estudaram, passaram” acrescenta explicação sobre o grupo referido. “Os servidores que estudaram passaram” restringe a afirmação aos que estudaram. Não é só uma mudança de ritmo: muda o recorte do grupo.'],
['Outros sinais','Dois-pontos anunciam explicação, especificação, enumeração ou fala: “Trouxe dois itens: caneta e papel”. Ponto e vírgula pode separar partes mais extensas ou itens que já contêm vírgulas. Travessões e parênteses podem isolar comentários. Aspas podem marcar citação ou um uso especial da palavra; o efeito exato depende do contexto.']
],['“Colegas, a reunião começará às oito.”','Colegas é o destinatário chamado: vocativo. O sujeito é a reunião, que concorda com começará. Logo a vírgula isola o vocativo; não separa sujeito e verbo.']);
lesson(12,'Semântica estuda o sentido. Estilística examina recursos de expressão. O primeiro passo é enxergar o mecanismo de cada nome.',[
['Sentido literal, figurado e relações de palavras','Denotação é uso literal: “A bomba explodiu”, falando de um explosivo. Conotação é uso figurado ou associado: “A notícia foi uma bomba”, indicando impacto. Polissemia é uma palavra com sentidos relacionados: cabeça do corpo e cabeça do grupo. Sinonímia é proximidade de sentido; antonímia é oposição. Campo semântico reúne palavras de um domínio: hospital, consulta, paciente. Sinônimos não são intercambiáveis em todos os contextos.'],
['Metáfora, comparação e metonímia','Metáfora aproxima por semelhança sem explicitar o comparativo: “Sua voz é mel”, sugerindo doçura. Comparação explicita a aproximação: “Sua voz é doce como mel”. Metonímia substitui por associação, como autor pela obra: “Li Clarice Lispector” significa que li uma obra dela. A associação real autor/obra difere da semelhança metafórica.'],
['Personificação, hipérbole, eufemismo e ironia','Personificação, também chamada prosopopeia, atribui ação ou traço humano a algo não humano: “O vento sussurrou”. Hipérbole exagera: “Esperei uma eternidade”. Eufemismo suaviza: “Ele partiu”, em contexto de morte. Ironia sugere um sentido em contraste com o dito: “Que pontual!”, para quem chegou muito atrasado.'],
['Outras figuras presentes nas alternativas','Pleonasmo repete uma ideia, como “subir para cima”; pode ser vício ou recurso expressivo conforme o uso. Antítese aproxima ideias opostas: “entre o amor e o ódio”. Aliteração repete sons consonantais: “O rato roeu a roupa”. Onomatopeia imita som: tic-tac. Hipérbato altera a ordem habitual dos termos. Antonomásia substitui um nome por uma designação característica, como “Rei do Futebol” por Pelé. Anáfora como figura repete uma palavra no início de segmentos; não confunda com a retomada referencial, também chamada anáfora.'],
['Uma frase pode admitir mais de uma análise','“A cidade acordou” pode personificar a cidade; em outro contexto, “cidade” pode representar seus habitantes, uma leitura metonímica. O enunciado precisa informar qual mecanismo está focalizando. Não procure só uma palavra-chave: leia o efeito e o contexto que a questão especifica.']
],['“Recebi uma montanha de documentos.”','Não há uma montanha literal. A expressão exagera a quantidade, produzindo hipérbole. “Li o autor” faria uma substituição autor/obra, metonímia; não é o mecanismo destacado aqui.']);
lesson(13,'Reescrever exige conservar o que o enunciado pede: informação, relação lógica e correção. Vamos observar como uma mudança pequena pode alterar o sentido.',[
['Paráfrase e equivalência','Paráfrase apresenta a mesma ideia com outra formulação: “A inscrição termina hoje” e “Hoje é o último dia de inscrição”. Equivalência depende de contexto: “alguns servidores” não pode virar “todos os servidores”; “pode ocorrer” não equivale a “ocorrerá”. Quantidade, certeza e tempo são partes do sentido.'],
['Conectivos e relações','“Estudou, mas errou” apresenta contraste. “Estudou, portanto errou” apresenta conclusão e muda a relação. Trocar uma palavra por um sinônimo de dicionário também pode falhar: “banco de dados” não admite substituir banco por assento. Leia a unidade completa.'],
['Paralelismo sintático','Paralelismo usa estruturas correspondentes para ideias coordenadas: “O trabalho exige planejar, revisar e publicar”. Os três verbos estão no infinitivo. “Exige planejamento, revisar e a publicação” mistura estruturas. Outra solução paralela é “exige planejamento, revisão e publicação”, com três substantivos.'],
['Voz ativa e passiva','Na ativa, “A equipe revisou o texto”, a equipe é sujeito agente e o texto é objeto direto. Na passiva, “O texto foi revisado pela equipe”, o texto vira sujeito paciente e pela equipe é agente da passiva. Preserve tempo e concordância: revisou → foi revisado; revisará → será revisado.']
],['Reescreva “A comissão aprovará os projetos” na passiva.','Os projetos vira sujeito, plural. Aprovará indica futuro, então use serão aprovados, não foram aprovados. Resultado: “Os projetos serão aprovados pela comissão”. O tempo e os participantes foram preservados.']);
lesson(14,'Letra é o sinal escrito; fonema é uma unidade sonora que pode distinguir palavras. Letras e sons não têm sempre correspondência de um para um.',[
['Letra, fonema, vogal e semivogal','“Chave” tem cinco letras: c, h, a, v, e. O ch representa um só som consonantal; por isso a análise escolar conta quatro fonemas. Vogal é o núcleo sonoro de uma sílaba. Semivogal é um som vocálico menos proeminente que acompanha uma vogal na mesma sílaba: em “pai”, o a é o núcleo e o i é semivogal. Não classifique apenas pelas letras i e u; observe a pronúncia e a sílaba.'],
['Ditongo: dois sons vocálicos na mesma sílaba','Ditongo reúne vogal e semivogal numa única sílaba. Em pai, o encontro ai fica junto; em cai-xa, ai também fica na primeira sílaba. Quando a semivogal vem depois da vogal, o ditongo é decrescente, como pai. Quando vem antes, é crescente, como a análise escolar usual de qua-se. A pronúncia e a convenção de análise precisam ser consideradas em casos variáveis.'],
['Tritongo e hiato','Tritongo reúne semivogal + vogal + semivogal na mesma sílaba: Pa-ra-guai, com u-a-i na sílaba final, sendo a o núcleo. Hiato tem duas vogais em sílabas diferentes: sa-ú-de, pa-ís, po-e-ta. A diferença decisiva não é ver duas letras juntas; é saber se os sons vocálicos ficam na mesma sílaba. Pai tem ditongo; pa-ís tem hiato.'],
['Dígrafo e encontro consonantal','Dígrafo são duas letras que representam um fonema: ch em chave, lh em folha, nh em ninho, rr em carro, ss em passo. Gu e qu são dígrafos quando o u não é pronunciado: guerra, queijo. Em “guerra”, gu e rr são dois dígrafos consonantais. Em “quase”, o u é pronunciado: qu não é dígrafo. Encontro consonantal reúne sons consonantais distintos, como pr em prato e bl em bloco.'],
['Divisão silábica e tonicidade','Ao separar sílabas, ch, lh e nh permanecem juntos: cha-ve, fo-lha, ni-nho. Rr e ss se separam na escrita: car-ro, pas-so. O hiato se separa; o ditongo permanece junto. Tonicidade é o destaque de uma sílaba; prosódia trata de aspectos da pronúncia, incluindo acento e entonação. Não confunda som com posição de prefixo ou função sintática: são análises diferentes.']
],['Compare pai, país e Paraguai.','Pai: uma sílaba, a + i juntos → ditongo. País: pa-ís, a e i em sílabas diferentes → hiato. Paraguai: Pa-ra-guai, semivogal u + vogal a + semivogal i na sílaba final → tritongo.']);
lesson(15,'Verbos têm formas que situam acontecimentos no tempo e mostram como o falante os apresenta. Vamos separar tempo, modo e formas nominais.',[
['Pessoa, número e modos','Pessoa relaciona a forma verbal a quem fala (eu/nós), com quem se fala (tu/vós, nas formas tradicionais) ou de quem se fala (ele/eles). Você usa terceira pessoa na concordância: “você estuda”. Número distingue singular e plural. Indicativo apresenta o fato como afirmado: “ela estuda”. Subjuntivo apresenta hipótese, desejo ou possibilidade: “talvez ela estude”. Imperativo expressa ordem, pedido ou orientação: “estude”.'],
['Tempos do indicativo','Presente: estudo, hábito ou situação atual. Pretérito perfeito: estudei, fato concluído no passado. Pretérito imperfeito: estudava, hábito ou situação em curso no passado. Mais-que-perfeito: estudara, fato anterior a outro passado; também pode aparecer como tinha estudado. Futuro do presente: estudarei. Futuro do pretérito: estudaria, futuro visto de um ponto passado ou fato condicionado. Os valores concretos dependem do contexto.'],
['Os tempos do subjuntivo','Presente: “Espero que ela estude”. Pretérito imperfeito: “Se ela estudasse, aprenderia”. Futuro: “Quando ela estudar, entenderá”. A terminação -sse é uma pista para o imperfeito do subjuntivo: estudasse, fizesse, tivesse. Em “Se estudasse mais, conseguiria”, o estudo é uma hipótese e a consequência é condicionada.'],
['Infinitivo, gerúndio e particípio','São formas nominais do verbo. Infinitivo apresenta o processo: estudar, fazer, chegar. Gerúndio: estudando, fazendo, chegando. Particípio: estudado, feito, chegado. Podem formar locuções: está estudando, tinha chegado, foi feito. Não confunda infinitivo com uma forma finita só porque a escrita coincide.'],
['Formas iguais, funções diferentes','Em “Quando chegar, avisarei”, chegar é futuro do subjuntivo, num contexto temporal futuro. Em “Quero chegar cedo”, chegar é infinitivo, ligado a quero. Para enxergar a diferença, troque por fazer: “Quando fizer...” e “Quero fazer...”. A escrita de chegar coincide, mas a construção é diferente.']
],['“Se estudasse mais, conseguiria resolver.”','Estudasse expressa hipótese e contém -sse: pretérito imperfeito do subjuntivo. Conseguiria apresenta o resultado condicionado: futuro do pretérito do indicativo. Resolver está no infinitivo, completando conseguiria. Não classifique todos os verbos da frase pelo mesmo tempo.']);
window.CQFoundations={pt:P};
// Clarify ambiguous distractors without changing IDs or correct-answer indices.
const placement=QUESTIONS.find(q=>q.uid==='q242');if(placement)placement.o[3]='Não se devem atrasar a entrega.';
const city=QUESTIONS.find(q=>q.uid==='q246');if(city){city.q='Na frase “a cidade acordou cedo”, considerando a atribuição de uma ação humana à cidade, o recurso destacado é:';city.e='A atribuição de ação humana a algo não humano caracteriza personificação. O comando focaliza esse mecanismo; em outro contexto, cidade poderia representar metonimicamente seus habitantes.';}
const subject=QUESTIONS.find(q=>q.uid==='q236');if(subject)subject.e='“Os designers” é o termo com o qual “entregaram” concorda e sobre o qual se declara a entrega. Seu núcleo é “designers”. Aqui o sujeito também pratica a ação, mas na voz passiva o sujeito pode recebê-la.';
})();
