/* Concrete, local teaching examples. Labels remain live text; geometry is deterministic. */
(function(){
'use strict';
const text=(x,y,t,size=20,color='#17263d',extra='')=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}" font-family="Arial,sans-serif" ${extra}>${esc(t)}</text>`;
const svg=(body,label,h=260)=>`<svg viewBox="0 0 600 ${h}" role="img" aria-label="${esc(label)}">${body}</svg>`;
const circle=(x,y,r=13,c='#315add')=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}"/>`;
const rect=(x,y,w,h,c='#e9eef7',rx=12)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${c}"/>`;
const line=(x,y,a,b,c='#315add',w=4)=>`<path d="M${x} ${y} L${a} ${b}" fill="none" stroke="${c}" stroke-width="${w}"/>`;
const table=(head,rows)=>`<div class="g-table-scroll"><table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(t=>`<td>${esc(t)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const panel=(html,caption='')=>`<figure class="g-example">${html}${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`;
function dots(mode='near'){
 let h='';for(let r=0;r<3;r++)for(let c=0;c<6;c++){const x=mode==='near'?70+c*62+(c>=3?72:0):90+c*82;h+=circle(x,60+r*58,14,mode==='similar'?(c%2?'#d94f25':'#315add'):'#315add');}
 return svg(h,mode==='near'?'Dezoito pontos iguais em dois grupos separados por um espaço maior.':'Pontos igualmente espaçados; colunas alternam azul e laranja.');
}
function contact(grouped){return `<div class="g-contact ${grouped?'is-grouped':''}"><div><strong>Ouvidoria</strong><span>Fale sobre o atendimento</span></div><div><strong>Transparência</strong><span>Consulte gastos públicos</span></div></div>`;}
function poster(good){return `<div class="g-poster ${good?'is-clear':'is-noisy'}"><img src="assets/oficina.jpg" alt="Mãos imprimindo uma gravura azul sobre papel em uma oficina de arte"><div class="g-poster-copy"><span class="g-poster-kicker">CULTURA PARA TODOS</span><strong>Oficina<br>de gravura</strong><p>Sábado · 14h<br>Centro Cultural</p><b>Inscrições gratuitas</b></div></div>`;}
function anatomy(){return svg(`${line(55,202,550,202,'#c95726',2)}${line(55,111,550,111,'#6684aa',2)}${text(98,200,'bag',160,'#162744','font-family="Georgia,serif"')} ${text(390,115,'altura-x',20)}${text(390,203,'linha de base',20)}${line(133,85,325,85,'#315add',2)}${text(335,89,'ascendente',20)}${line(315,244,379,244,'#315add',2)}${text(390,249,'descendente',20)}`,'Letras b, a e g: haste de b sobe acima da altura-x; g desce abaixo da linha de base.',280);}
function closure(){return svg(`<path d="M170 66 H116 V122 M116 156 V212 H170 M210 212 H264 V156 M264 122 V66 H210" stroke="#315add" stroke-width="13" fill="none"/>${text(345,125,'Você completa',24)}${text(345,161,'o contorno?',24)}`,'Quatro cantos separados sugerem um quadrado, embora existam lacunas no contorno.');}
function continuity(){return svg(`<path d="M65 215 C230 200 300 55 510 55" stroke="#17263d" stroke-width="8" fill="none"/><path d="M65 55 C230 65 330 215 510 215" stroke="#17263d" stroke-width="8" fill="none"/>${text(35,225,'A',25)}${text(520,60,'B',25)}${text(35,60,'C',25)}${text(520,225,'D',25)}`,'Duas curvas cruzadas: A segue suavemente até B; C segue suavemente até D.');}
function rubin(){return svg(`${rect(80,15,440,230,'#17263d')}<path d="M225 15 H375 C335 41 335 61 360 80 L375 93 L351 107 L362 122 C351 139 325 147 319 171 C315 192 335 216 365 245 H235 C265 216 285 192 281 171 C275 147 249 139 238 122 L249 107 L225 93 L240 80 C265 61 265 41 225 15Z" fill="#fff"/>`,'Imagem ambígua: o branco central forma um vaso; as bordas escuras formam dois perfis de rosto voltados um ao outro.');}
function grid(){return `<div class="g-layout-demo"><span class="g-col"></span><span class="g-col"></span><span class="g-col"></span><span class="g-col"></span><div class="g-layout-title">Cultura perto de você</div><div class="g-layout-photo"><img src="assets/oficina.jpg" alt="Oficina de gravura"></div><div class="g-layout-type">Aprenda a imprimir<br>Uma oficina aberta à comunidade.<br><b>Reserve sua vaga →</b></div></div>`;}
function percent(){let h='';for(let i=0;i<100;i++)h+=rect(103+(i%10)*27,10+Math.floor(i/10)*24,22,19,i<20?'#315add':'#dfe5f0',3);return svg(h,'Grade de 100 quadrados: 20 azuis e 80 claros. Cada quadrado representa 1%.');}
function venn(){return svg(`<circle cx="238" cy="125" r="95" fill="#315add" opacity=".15" stroke="#315add" stroke-width="3"/><circle cx="365" cy="125" r="95" fill="#dc542d" opacity=".18" stroke="#dc542d" stroke-width="3"/>${text(184,135,'1, 2',27)}${text(291,135,'3',27)}${text(393,135,'4',27)}${text(204,244,'A',22)}${text(379,244,'B',22)}`,'Conjuntos A e B: somente A contém 1 e 2; interseção contém 3; somente B contém 4.');}
function bars(outlier){const vals=outlier?[2,3,4,5,20]:[2,3,4,5,6];return svg(vals.map((v,i)=>rect(100+i*83,210-v*8,48,v*8,i===4?'#dc542d':'#315add',3)+text(115+i*83,239,v,20)).join('')+line(75,211,545,211,'#8090aa',2),'Cinco barras com valores '+vals.join(', '));}
function bleed(){return svg(`${rect(115,10,370,240,'#dce8ff',0)}${rect(134,28,332,203,'#315add',0)}<path d="M146 41 H453 V218 H146 Z" stroke="#fff" stroke-width="2" stroke-dasharray="7 5" fill="none"/>${text(175,100,'OFICINA',35,'white','font-weight="700"')}${text(175,145,'DE GRAVURA',27,'white')}${text(173,187,'texto dentro da margem',17,'white')}${line(110,28,134,28,'#d94f25',2)}${line(134,4,134,24,'#d94f25',2)}${line(466,235,466,253,'#d94f25',2)}${line(472,231,496,231,'#d94f25',2)}`,'Fundo estendido até a sangria, marcas indicam corte, contorno interno pontilhado indica segurança.');}
const visuals={
 elements:()=>panel(`<div class="g-elements"><div><span class="g-point"></span><small>Ponto</small></div><div><span class="g-line"></span><small>Linha</small></div><div><span class="g-shape"></span><small>Forma</small></div><div><span class="g-texture"></span><small>Textura</small></div></div>`,'Mesma cor, funções distintas: foco, direção, área e superfície.'),
 space:()=>panel(`<div class="g-two"><div class="g-space crowded">OFICINA<br>GRATUITA<br>SÁBADO<br>14 HORAS</div><div class="g-space calm"><b>Oficina gratuita</b><span>Sábado · 14h</span></div></div>`,'O vazio também organiza. Compare a separação entre assunto e horário.'),
 proximity:()=>panel(dots('near'),'As formas são idênticas. Só a distância muda.'),
 similarity:()=>panel(dots('similar'),'Agora as distâncias são iguais. A cor sugere famílias.'),
 grouping:()=>panel(`<div id="g-group-demo">${dots('near')}</div><div class="g-demo-tools"><button type="button" class="g-chip" onclick="CQGuideVisual.group('near')">Agrupar por distância</button><button type="button" class="g-chip" onclick="CQGuideVisual.group('similar')">Agrupar por cor</button></div>`,'Alterne e observe qual pista seu olhar usa.'),
 contact:()=>panel(`<div class="g-two"><div><span class="g-label">A · espaçamento uniforme</span>${contact(false)}</div><div><span class="g-label">B · grupos separados</span>${contact(true)}</div></div>`,'Exemplo de menu público. Em B, cada descrição fica mais próxima do seu título.'),
 closure:()=>panel(closure(),'O quadrado é percebido mesmo sem uma borda contínua.'),
 continuity:()=>panel(continuity(),'Siga a curva a partir de A. Em qual letra você chega sem uma mudança brusca de direção?'),
 figure:()=>panel(rubin(),'Tente alternar: primeiro veja o vaso; depois, os dois perfis. A borda é a mesma.'),
 pregnance:()=>panel(svg([0,1,2].map(i=>`<circle cx="${225+i*80}" cy="130" r="65" fill="none" stroke="#315add" stroke-width="6"/>`).join(''),'Três círculos de mesmo raio sobrepostos.'),'É mais simples perceber três círculos sobrepostos do que várias partes isoladas.'),
 posters:()=>panel(`<div class="g-two"><div><span class="g-label">A</span>${poster(false)}</div><div><span class="g-label">B</span>${poster(true)}</div></div>`,'Peças fictícias para estudo. Mesma fotografia e mensagem; hierarquias diferentes.'),
 poster:()=>panel(poster(true),'Peça fictícia. Fotografia criada para este exercício.'),
 grid:()=>panel(grid(),'As quatro colunas aparecem como guias. Título, foto e texto se alinham a elas.'),
 anatomy:()=>panel(anatomy(),'Compare as partes das letras, não apenas o nome da família.'),
 typography:()=>panel(`<div class="g-type-samples"><p class="g-serif">Câmara Municipal <small>Serifa</small></p><p class="g-sans">Câmara Municipal <small>Sem serifa</small></p><p class="g-mono">Câmara Municipal <small>Monoespaçada</small></p></div>`,'“Serifada” descreve uma característica; não determina sozinha se um texto será legível.'),
 legibility:()=>panel(`<div class="g-reading bad">Consulte o edital e confira o prazo de inscrição. Leia os requisitos antes de enviar os documentos.</div><div class="g-reading good">Consulte o edital e confira o prazo de inscrição. Leia os requisitos antes de enviar os documentos.</div>`,'A mesma frase com tamanho, espaçamento e contraste diferentes.'),
 contrast:()=>panel(`<div class="g-contrast-example"><p style="color:#aaa">Inscrições abertas</p><p style="color:#334155">Inscrições abertas</p></div>`,'Ambas usam fundo branco. A primeira usa #AAAAAA; a segunda, #334155.'),
 color:()=>panel(`<div id="g-rgb-swatch" class="g-rgb-swatch" style="background:rgb(255,0,0)"><output id="g-rgb-out">RGB(255, 0, 0)</output></div><div class="g-rgb-controls">${['R','G','B'].map((x,i)=>`<label>${x}<input id="g-rgb-${x}" aria-label="Canal ${x}" type="range" min="0" max="255" value="${i?0:255}" oninput="CQGuideVisual.rgb()"></label>`).join('')}</div>`,'Experimente R=255, G=255 e B=0. O pixel fica amarelo.'),
 harmony:()=>panel(`<div class="g-harmonies">${[['Complementar',['hsl(0 82% 60%)','hsl(180 72% 44%)'],'0° e 180°'],['Análoga',['hsl(0 82% 60%)','hsl(30 84% 53%)','hsl(60 76% 48%)'],'0°, 30° e 60°'],['Triádica',['hsl(0 82% 60%)','hsl(120 55% 48%)','hsl(240 74% 62%)'],'0°, 120° e 240°']].map(([n,colors,a])=>`<div><strong>${n}</strong><div>${colors.map(c=>`<i style="background:${c}"></i>`).join('')}</div><small>${a}</small></div>`).join('')}</div>`,'Relações de matiz do círculo RGB/HSV, com saturação e luminosidade ajustadas para a amostra.'),
 pixels:()=>panel(`<div class="g-two"><div><span class="g-label">Fotografia</span><img class="g-photo-detail" src="assets/oficina.jpg" alt="Fotografia contínua da oficina"></div><div><span class="g-label">Amostra de 24 pixels de largura ampliada</span><canvas id="g-pixel-canvas" width="24" height="16" role="img" aria-label="A mesma foto amostrada em poucos pixels e ampliada"></canvas></div></div>`,'A ampliação revela a grade; mudar o número de ppi não recupera os detalhes perdidos.'),
 vector:()=>panel(svg(`<path d="M80 195 L170 55 L260 195 Z" fill="#315add"/><path d="M340 195 L430 55 L520 195 Z" fill="none" stroke="#315add" stroke-width="4"/>${[ [340,195],[430,55],[520,195] ].map(([x,y])=>rect(x-6,y-6,12,12,'#d94f25',0)).join('')}`,'Triângulo preenchido ao lado do seu caminho vetorial com três nós.'),'A geometria pode ser redesenhada em outra escala; os nós não são pixels.'),
 bleed:()=>panel(bleed(),'Sangria é área externa ao corte; margem de segurança é interna. A medida depende da gráfica.'),
 percent:()=>panel(percent(),'20 em 100 equivalem a 20%. Para outro total, preserve a mesma proporção.'),
 price:()=>panel(`<div class="g-equation"><span>R$ 200</span><b>× 0,80</b><span>R$ 160</span></div>`,'Desconto de 20% deixa 80% do preço original.'),
 balance:()=>panel(svg(`${line(120,89,480,89,'#17263d',6)}${line(300,89,300,215,'#17263d',6)}<path d="M270 220 L300 180 L330 220Z" fill="#17263d"/>${rect(97,22,135,55,'#dfe8ff')}${rect(386,22,125,55,'#ffe1d5')}${text(119,58,'2x + 4',28)}${text(431,58,'10',28)}`,'Balança em equilíbrio: 2x mais 4 é igual a 10.'),'Faça a mesma operação nos dois lados para preservar a igualdade.'),
 ratio:()=>panel(table(['Quantidade','Custo'],[['3 cartazes','R$ 24'],['1 cartaz','R$ 8'],['5 cartazes','?']]),'Hipótese deste exemplo: preço unitário constante, sem taxa fixa.'),
 pa:()=>panel(`<div class="g-sequence"><span>2</span><b>+3 →</b><span>5</span><b>+3 →</b><span>8</span><b>+3 →</b><span>?</span></div>`,'Em uma PA, a diferença entre termos consecutivos é constante.'),
 combination:()=>panel(table(['Dupla sem cargos','Escolhas com cargos'],[['Ana e Bia','Ana presidente / Bia secretária'],['A mesma dupla','Bia presidente / Ana secretária']]),'O grupo é o mesmo; a atribuição dos cargos muda o resultado.'),
 stats:()=>panel(bars(false),'Valores 2, 3, 4, 5 e 6. O centro está em 4.'),
 outlier:()=>panel(bars(true),'Só o último valor mudou: de 6 para 20. O centro ordenado ainda é 4.'),
 sets:()=>panel(venn(),'A={1,2,3}; B={3,4}. Não conte duas vezes o elemento comum.'),
 crase:()=>panel(`<div class="g-equation"><span>ir <b>a</b></span><span>+ <b>a</b> Câmara</span><span>= ir <b>à</b> Câmara</span></div>`,'A preposição vem da regência; o artigo acompanha o substantivo.'),
 syntax:()=>panel(`<div class="g-sentence"><span class="g-subject">A equipe de comunicação<small>quem pratica a ação?</small></span><span class="g-verb">revisou<small>ação verbal</small></span><span class="g-object">o cartaz.<small>o que foi revisado?</small></span></div>`,'Sujeito, verbo e objeto direto no exemplo.'),
 punctuation:()=>panel(`<div class="g-reading good">Não, espere.</div><div class="g-reading good">Não espere.</div>`,'A vírgula muda a relação de “não” com o restante da frase.'),
 cohesion:()=>panel(`<div class="g-reading good">A Câmara publicou <mark>o edital</mark>.<br><mark>O documento</mark> apresenta os requisitos.</div>`,'A segunda expressão retoma a primeira por uma substituição lexical.'),
 inference:()=>panel(`<blockquote class="g-excerpt">“O atendimento presencial foi suspenso nesta sexta-feira. Os pedidos continuam disponíveis pelo portal.”</blockquote>`,'Distingua o que o trecho afirma do que você apenas imagina.'),
 code:()=>panel(`<pre class="g-code"><code>x ← 2\nx ← x × 3\nx ← x + 4\nmostrar x</code></pre>`,'Cada atribuição usa o valor atual e substitui o anterior.'),
 loop:()=>panel(`<pre class="g-code"><code>x ← 2\nenquanto x &lt; 6:\n    x ← x + 2\nmostrar x</code></pre>`,'Antes de repetir, verifique novamente a condição.'),
 memory:()=>panel(`<div class="g-memory"><div><b>SSD</b><span>arquivo salvo</span></div><i>→</i><div><b>RAM</b><span>dados em uso</span></div><i>↔</i><div><b>CPU</b><span>executa instruções</span></div></div>`,'Modelo simplificado de abrir e editar um arquivo; não é um diagrama de barramentos.'),
 sheet:()=>panel(table(['','A · valor','B · taxa','C · resultado'],[['2','100','0,10','=A2*$B$2'],['3','200','','=A3*$B$2']]),'Ao copiar para baixo, A2 muda; $B$2 continua apontando para a mesma célula.'),
 cia:()=>panel(`<div class="g-three"><div><b>Confidencialidade</b><span>Quem pode ler?</span></div><div><b>Integridade</b><span>Foi alterado indevidamente?</span></div><div><b>Disponibilidade</b><span>Está acessível quando preciso?</span></div></div>`,'Três perguntas diferentes sobre a proteção da informação.'),
 public:()=>panel(`<div class="g-two"><div class="g-public-card"><small>PEÇA A · FICTÍCIA</small><b>Vacinação<br>neste sábado</b><span>Unidade Central · 8h às 16h</span></div><div class="g-public-card g-personal"><small>PEÇA B · FICTÍCIA</small><b>Mais uma conquista<br>do nosso líder!</b><span>Vacinação neste sábado</span></div></div>`,'Compare a finalidade informativa com a exaltação de uma autoridade.'),
 federation:()=>panel(table(['Categoria','Exemplo'],[['Ente autônomo','Município de Senador Canedo'],['Órgão do Município','Secretaria municipal'],['Capital Federal','Brasília'],['Integra a União','Território Federal']]),'As categorias não são intercambiáveis. Fonte: Constituição, art. 18.'),
 timeline:()=>panel(`<ol class="g-timeline"><li><b>1953</b><span>Distrito subordinado a Goiânia</span></li><li><b>1988</b><span>Lei de criação do município</span></li><li><b>1989</b><span>Instalação do município</span></li></ol>`,'Marcos distintos. O histórico do IBGE também registra suspensão da execução da lei em julho de 1988.'),
};
window.CQGuideVisual={render:key=>visuals[key]?visuals[key]():'',has:key=>Boolean(visuals[key]),group(mode){document.getElementById('g-group-demo').innerHTML=dots(mode)},rgb(){const vals=['R','G','B'].map(x=>Number(document.getElementById('g-rgb-'+x).value));document.getElementById('g-rgb-swatch').style.background=`rgb(${vals})`;document.getElementById('g-rgb-out').value=`RGB(${vals.join(', ')})`;},mount(){const c=document.getElementById('g-pixel-canvas');if(c){const im=new Image();im.onload=()=>{const context=c.getContext('2d');context.drawImage(im,0,0,24,16)};im.src='assets/oficina.jpg';}}};
})();
