(function(){
'use strict';
function routeAllDone(){return Object.entries(MODULES).every(function(e){return e[1].every(function(_,i){return !!state.lessonDone[e[0]+':'+i]})})}
function routeNext(s){var mods=MODULES[s]||[];var i=mods.findIndex(function(_,n){return !state.lessonDone[s+':'+n]});return i<0?null:{s:s,i:i,title:mods[i][0],desc:mods[i][1]}}
function pending(){return Object.keys(SUBJECTS).map(routeNext).filter(Boolean)}
function shuffle(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=x[i];x[i]=x[j];x[j]=t}return x}
function ensureChoices(force){if(routeAllDone()){state.guidedRoute={choices:[],complete:true};save();return []}var cur=state.guidedRoute&&state.guidedRoute.choices;if(!force&&Array.isArray(cur)&&cur.length&&cur.every(function(x){var n=routeNext(x.s);return n&&n.i===x.i}))return cur;var all=shuffle(pending()),used=(cur||[]).map(function(x){return x.s}),fresh=all.filter(function(x){return used.indexOf(x.s)<0}),choices=fresh.concat(all.filter(function(x){return used.indexOf(x.s)>=0})).slice(0,3);state.guidedRoute={choices:choices,createdAt:Date.now(),complete:false,active:null};save();return choices}
function card(x,n){var total=MODULES[x.s].length,icon=SUBJECTS[x.s][0],done=Object.keys(state.lessonDone).filter(function(k){return k.indexOf(x.s+':')===0}).length;return '<button class="guided-choice-card" onclick="chooseGuidedSubject(\''+x.s+'\','+x.i+')"><span class="guided-choice-index">'+n+'</span><span class="guided-choice-icon">'+icon+'</span><span class="guided-choice-main"><strong>'+esc(SUBJECTS[x.s][1])+'</strong><small>'+esc(x.title)+'</small><em>'+done+'/'+total+' aulas concluídas · próximo conteúdo</em></span><span class="guided-choice-arrow">→</span></button>'}
function revisitList(){var h='';Object.entries(SUBJECTS).forEach(function(e){var s=e[0],v=e[1],done=MODULES[s].map(function(m,i){return{m:m,i:i}}).filter(function(x){return state.lessonDone[s+':'+x.i]});if(!done.length)return;h+='<section class="revisit-subject"><h3>'+v[0]+' '+esc(v[1])+'</h3><div>'+done.map(function(x){return '<button class="revisit-item" onclick="revisitLesson(\''+s+'\','+x.i+')"><span>✓</span><strong>'+esc(x.m[0])+'</strong><small>revisitar</small></button>'}).join('')+'</div></section>'});return h||'<p class="empty-revisit">Você ainda não concluiu nenhuma aula.</p>'}
function showChoices(){var active=state.guidedRoute&&state.guidedRoute.active;if(active&&!state.lessonDone[active.s+':'+active.i]){lesson(active.s,active.i);return}if(routeAllDone()){state.guidedRoute={choices:[],complete:true};save();go('sim');return}var choices=ensureChoices(false),done=Object.keys(state.lessonDone).length,total=sumModules(),pct=Math.round(100*done/Math.max(1,total));shell('Trilha de estudo');var c=document.querySelector('#content');c.innerHTML='<div class="guided-route-wrap"><section class="guided-route-hero card"><div class="eyebrow">TRILHA OBRIGATÓRIA · '+done+'/'+total+' AULAS</div><h1>Escolha apenas o próximo assunto.</h1><p>Você não monta a própria rota. O sistema sorteia até três matérias que ainda têm conteúdo pendente. Depois desta aula, um novo conjunto aparece.</p><div class="guided-route-progress"><span style="width:'+pct+'%"></span></div></section><section class="guided-choice-section"><div class="section-head"><div><div class="eyebrow">SORTEIO DA ETAPA</div><h2>Qual das três você quer estudar agora?</h2><p>As opções mudam a cada etapa.</p></div></div><div class="guided-choice-list">'+choices.map(card).join('')+'</div></section><details class="revisit-panel"><summary>↩ Revisitar conteúdos já estudados</summary><div class="revisit-grid">'+revisitList()+'</div></details></div>'}
window.routeAllDone=routeAllDone;
window.showGuidedChoices=showChoices;
window.chooseGuidedSubject=function(s,i){var n=routeNext(s);if(!n||n.i!==i){ensureChoices(true);showChoices();return}state.guidedRoute=Object.assign({},state.guidedRoute,{active:{s:s,i:i}});state.guidedRevisit=false;save();lesson(s,i)};
window.revisitLesson=function(s,i){if(!state.lessonDone[s+':'+i]){toast('A aula ainda não foi liberada na trilha.');return}state.guidedRevisit=true;state.guidedRoute=Object.assign({},state.guidedRoute,{active:null});save();lesson(s,i)};
window.completeLesson=function(s,i){var key=s+':'+i;if(!state.lessonDone[key]){state.lessonDone[key]=true;state.xp+=12;touchStudy();uiSound('unlock')}state.guidedRevisit=false;state.guidedRoute={choices:[],active:null,complete:routeAllDone(),lastCompleted:{s:s,i:i,at:Date.now()}};save();if(routeAllDone())go('sim');else showChoices()};
window.guidedContinue=function(){if(state.guidedRevisit){state.guidedRevisit=false;save();go('study')}else showChoices()};
window.startGuided=function(){showChoices()};window.guidedAction=function(){return{type:'choices',choices:ensureChoices(false)}};window.guidedNext=function(){var c=ensureChoices(false);return c.length?{type:'choices',choices:c}:{type:'complete'}};window.guidedLabel=function(){var c=ensureChoices(false);return c.length?{eyebrow:'ESCOLHA DA ETAPA',title:c.length+' matérias sorteadas',desc:'Escolha uma opção. A próxima etapa será sorteada depois da aula.',button:'Ver opções'}:{eyebrow:'TRILHA CONCLUÍDA',title:'Conteúdo completo',desc:'Todas as aulas obrigatórias foram concluídas.',button:'Fazer prova'}};
var oldLesson=window.lesson;window.lesson=function(s,i){var done=!!state.lessonDone[s+':'+i],cur=state.guidedRoute&&state.guidedRoute.active,valid=cur&&cur.s===s&&cur.i===i;if(!done&&!valid){toast('A trilha escolhe o próximo conteúdo para você.');showChoices();return}oldLesson(s,i);setTimeout(function(){document.querySelectorAll('.lesson-body section').forEach(function(sec){var h=sec.querySelector('h3');var t=h?h.textContent:'';if(t.indexOf('Como pode aparecer na prova')>=0)sec.remove();if(t.indexOf('✅ Autoexplicação')>=0)sec.remove()});document.querySelector('.deep-box')?.remove();var tip=document.querySelector('.tip strong');if(tip)tip.textContent='⚠️ Armadilha de prova';document.querySelectorAll('.lesson-actions button').forEach(function(btn){var t=(btn.textContent||'').trim();if(t.indexOf('Próxima aula')>=0||t.indexOf('Aula anterior')>=0)btn.remove();if(t.indexOf('Voltar aos módulos')>=0){btn.textContent='← Voltar à trilha';btn.onclick=function(){go('study')}}if(t.indexOf('Concluir e continuar')>=0)btn.textContent='✅ Concluir e ver próximas opções';if(t.indexOf('Prova do módulo')>=0&&!routeAllDone())btn.remove();if(t.indexOf('Próximo passo')>=0&&state.guidedRevisit)btn.textContent='← Voltar à trilha'})},0)};
window.sim=(function(prev){return function(){if(!routeAllDone()){shell('Provas bloqueadas');document.querySelector('#content').innerHTML='<section class="card route-lock"><div class="eyebrow">🔒 PROVAS BLOQUEADAS</div><h1>Termine a trilha antes dos simulados.</h1><p>Conclua todas as aulas obrigatórias para liberar as provas.</p><button class="btn primary" onclick="showGuidedChoices()">Voltar para a trilha</button></section>';return}return prev()}})(window.sim);
window.moduleExam=(function(prev){return function(s,i){if(!routeAllDone()){toast('As provas de módulo ficam disponíveis depois da trilha completa.');showChoices();return}return prev(s,i)}})(window.moduleExam);
window.train=(function(prev){return function(){if(!routeAllDone()){showChoices();return}return prev()}})(window.train);
window.navButtons=function(){var items={home:['⌂','Início','Seu próximo passo'],study:['📖','Trilha','Próximo assunto'],review:['🔁','Revisar','Rever o que já estudou']};if(routeAllDone())items.sim=['🎯','Provas','Simulados liberados'];return Object.entries(items).map(function(e){var id=e[0],a=e[1];return '<button class="'+(state.page===id?'active':'')+'" onclick="go(\''+id+'\')"><span class="icon">'+a[0]+'</span><span><strong>'+a[1]+'</strong><small>'+a[2]+'</small></span></button>'}).join('')};
window.moreMenu=function(){return '<div class="more-panel" id="more-panel"><div class="more-head"><div><div class="eyebrow">APOIO</div><h3>Ferramentas de estudo</h3><p>A rota principal continua obrigatória. Aqui ficam recursos para revisar o que já foi estudado.</p></div><button class="icon-btn" onclick="toggleMore()" aria-label="Fechar">×</button></div><div class="more-grid"><button onclick="go(\'errors\');toggleMore()"><b>🧩</b><span><strong>Meus erros</strong><small>Corrigir questões erradas</small></span></button><button onclick="go(\'cards\');toggleMore()"><b>🧠</b><span><strong>Flashcards</strong><small>Recuperação ativa</small></span></button><button onclick="go(\'board\');toggleMore()"><b>✏️</b><span><strong>Lousa</strong><small>Resolver e organizar ideias</small></span></button><button onclick="go(\'sources\');toggleMore()"><b>📚</b><span><strong>Fontes</strong><small>Referências</small></span></button></div></div>'};
window.study=function(){showChoices()};
})();