/* Authored mini-lessons. Teaching illustrations and scenarios are original examples, not official exam questions. */
(function(){
'use strict';
const T=(title,text,visual)=>({type:'teach',title,text,visual});
const Q=(title,options,answer,explain,visual)=>({type:'choice',title,options,answer,explain,visual});
const I=(title,accepted,explain,visual)=>({type:'input',title,accepted,explain,visual});
const packs={};
const P=(key,goal,summary,steps,source)=>packs[key]={goal,summary,steps,source};
P('design:0','Perceber como ponto, linha, forma e espaço conduzem o olhar.','Os elementos visuais ganham função quando se relacionam: destacar, separar, orientar ou agrupar.',[
 T('Antes do nome, olhe','Um ponto pode concentrar atenção. Uma linha sugere direção ou separação. Uma forma ocupa uma área. A textura sugere uma superfície. Observe as diferenças.','elements'),
 Q('Você precisa separar duas seções de um cartaz. Qual elemento pode cumprir essa função diretamente?',['Uma linha divisória','Uma textura em toda a página','Vários pontos com o mesmo peso'],0,['A linha estabelece uma fronteira visual entre regiões. A separação também pode ser feita por espaço.','Textura altera a superfície percebida; não estabelece necessariamente uma separação entre seções.','Pontos distribuídos podem criar ritmo, mas não deixam clara a fronteira entre duas seções.'],'elements'),
 T('O espaço não está sobrando','Em uma composição, o vazio define intervalos. Compare como o segundo exemplo separa o assunto do horário sem adicionar nenhuma moldura.','space'),
 Q('O segundo exemplo organiza melhor o assunto e o horário principalmente porque…',['muda a relação de espaço e importância','usa uma fotografia mais nítida','adiciona mais informações'],0,['A mensagem permanece. Espaçamento e escala deixam as relações mais claras.','Não há fotografia neste exemplo. Procure a mudança que realmente ocorreu.','A informação é a mesma. Organização não depende de aumentar a quantidade.'],'space'),
 T('Leve isso para uma peça','Antes de escolher um efeito, pergunte: onde a pessoa deve olhar primeiro? O que pertence ao mesmo grupo? O que precisa ficar separado? Essas decisões orientam os próximos fundamentos.','poster'),
 Q('Qual decisão usa os elementos com uma finalidade de comunicação?',['Aumentar o título principal e separar data e local em um grupo','Colocar textura em todas as áreas para eliminar os vazios','Dar exatamente o mesmo tamanho a todas as informações'],0,['Escala cria prioridade e proximidade agrupa informações relacionadas.','Eliminar todo vazio pode dificultar agrupamento e leitura.','O mesmo peso pode funcionar em casos específicos, mas não expressa a prioridade pedida.'])
]);
P('design:1','Distinguir proximidade de semelhança olhando exemplos.','Proximidade agrupa pelo intervalo; semelhança agrupa por características compartilhadas.',[
 T('Seu olhar forma grupos','Antes de contar os pontos, observe quantos blocos você percebe. Eles têm a mesma forma, cor e tamanho. O espaço entre eles é a pista.','proximity'),
 Q('Por que os pontos parecem formar dois grupos?',['O intervalo entre os blocos é maior','Os dois blocos têm cores diferentes','As bordas desenham duas caixas'],0,['O agrupamento vem da proximidade relativa: pouco espaço dentro de cada bloco e mais espaço entre eles.','Todos os pontos têm a mesma cor. A variável que mudou foi a distância.','Não existem caixas desenhadas. O agrupamento pode surgir só do espaçamento.'],'proximity'),
 T('Agora mude a pista','Aqui os intervalos são iguais. Mesmo assim, as cores sugerem famílias. Isso é semelhança: elementos com características compartilhadas tendem a ser associados.','similarity'),
 Q('Nesta segunda composição, qual pista cria as famílias visuais?',['A cor compartilhada','Uma diferença de distância entre os pontos','Um contorno fechado ao redor de cada família'],0,['A cor é a característica semelhante. Também podem atuar forma, tamanho ou orientação.','As distâncias são regulares neste exemplo.','Não há contorno separando as famílias.'],'similarity'),
 T('Experimente você','Alterne os dois exemplos. Observe que o agrupamento muda sem ser necessário acrescentar linhas divisórias. As duas pistas podem cooperar ou competir em uma peça.','grouping'),
 Q('No menu B, por que cada descrição se associa melhor ao seu título?',['Ela está mais perto do próprio título que do próximo grupo','Todas as palavras estão em letras maiúsculas','O fundo cria uma ilusão de profundidade'],0,['Esse é o uso de proximidade em uma interface: o intervalo interno é menor que o intervalo entre assuntos.','A diferença importante não é o uso de maiúsculas. Compare os intervalos.','Profundidade não é o mecanismo demonstrado.'],'contact'),
 T('Não confunda os nomes','Proximidade responde “o que está perto?”. Semelhança responde “o que tem características parecidas?”. Uma questão pode manter uma pista constante e alterar a outra.','contact')
]);
P('design:2','Perceber contornos incompletos e trajetórias contínuas.','Fechamento completa mentalmente lacunas; boa continuidade favorece trajetórias suaves.',[
 T('Veja o que não foi desenhado','Você provavelmente percebe um quadrado. Mas as bordas têm lacunas: não existe um contorno fechado no desenho. O olhar completa a forma sugerida.','closure'),
 Q('Qual mecanismo explica o quadrado percebido?',['Fechamento','Semelhança de cores entre categorias','Perspectiva com ponto de fuga'],0,['Fechamento é a tendência de completar contornos sugeridos por partes.','A pergunta trata de uma borda ausente, não de categorias associadas por cor.','Não há profundidade ou ponto de fuga neste exemplo.'],'closure'),
 T('Siga uma trajetória','Comece em A e acompanhe o caminho mais suave. Na interseção, o olhar tende a manter a direção da curva, em vez de trocar abruptamente de trajetória.','continuity'),
 Q('Seguindo a curva suavemente desde A, você chega a…',['B','C','D'],0,['A e B pertencem à mesma curva suave. Esse percurso exemplifica boa continuidade.','Para chegar a C seria preciso trocar de trajetória na interseção.','D é a extremidade da outra curva.'],'continuity'),
 T('Onde isso aparece no trabalho','Um símbolo pode sugerir uma forma com trechos ausentes. Uma linha de percurso pode guiar a leitura. São decisões distintas: completar um contorno não é o mesmo que seguir uma direção.'),
 Q('Um logotipo omite pequenos trechos, mas você reconhece sua borda circular. Qual princípio está em destaque?',['Fechamento','Proximidade entre parágrafos','Contraste de saturação'],0,['A forma reconhecida depende de completar as lacunas do contorno.','Proximidade trata de agrupamento pela distância.','Saturação descreve uma característica cromática; não explica o contorno completado.'])
]);
P('design:3','Alternar figura e fundo e reconhecer organizações simples.','Figura e fundo dependem de como a borda é interpretada; pregnância favorece uma organização estável e simples.',[
 T('Uma imagem, duas leituras','Olhe primeiro para a região branca: tente ver um vaso. Agora olhe para as bordas escuras laterais: tente ver dois perfis de rosto.','figure'),
 Q('O que muda quando você alterna entre vaso e rostos?',['A região percebida como figura e a interpretação da borda','A posição real dos elementos','A resolução da imagem'],0,['Os mesmos limites separam as regiões. A organização perceptiva alterna; a imagem não precisa mudar.','Nenhum elemento se move. A mudança acontece na interpretação.','A resolução permanece igual.'],'figure'),
 T('Fundo não é algo sem função','O espaço entre elementos também pode formar uma imagem. Ao criar um símbolo, avalie tanto as massas preenchidas quanto o espaço negativo. Um fundo pode competir com a mensagem.','figure'),
 T('Uma organização econômica','Você tende a perceber três círculos sobrepostos, em vez de uma coleção de fragmentos curvos. Uma organização simples e regular é mais estável para o olhar. Isso ajuda a entender pregnância.','pregnance'),
 Q('Pregnância significa que toda peça deve ter o menor número possível de elementos?',['Não. Trata da organização perceptiva, não de uma regra de minimalismo','Sim. Qualquer detalhe adicional viola a Gestalt','Sim. Imagens complexas nunca são reconhecidas'],0,['Uma composição pode ter muitos elementos e ainda apresentar relações claras e estáveis.','Contar elementos não mede sozinho a organização percebida.','Reconhecimento de complexidade é possível. A tendência perceptiva não proíbe imagens complexas.']),
 Q('Se o fundo de um cartaz compete com o título e dificulta identificá-lo, o problema imediato envolve…',['a distinção entre figura e fundo','a gramatura do papel','o número de páginas do arquivo'],0,['Contraste e separação entre mensagem e suporte visual influenciam o que se destaca como figura.','Gramatura é uma propriedade física do papel; não explica a disputa perceptiva descrita.','Quantidade de páginas não resolve essa relação visual.'])
]);
P('design:4','Reconhecer e construir uma ordem de leitura em uma peça.','Hierarquia organiza a prioridade por escala, posição, contraste e espaço.',[
 T('Leia antes de analisar','Os dois cartazes têm a mesma fotografia e mensagem. Em qual deles você encontra mais rapidamente o assunto, depois horário e local?','posters'),
 Q('Qual cartaz deixa o assunto principal mais evidente?',['B','A','Ambos dão exatamente o mesmo peso a tudo'],0,['Em B, “Oficina de gravura” tem maior escala e posição estável. Os detalhes aparecem em um nível secundário.','Em A, pesos e posições disputam atenção; a ordem fica menos clara.','A escala e a distribuição do conteúdo diferem visivelmente.'],'posters'),
 T('Não é só aumentar a fonte','Em B, tamanho, alinhamento, contraste e proximidade cooperam. A foto contextualiza; o título identifica o evento; data e local resolvem a informação prática.','poster'),
 Q('Se tudo fosse grande, colorido e em negrito, o que tenderia a acontecer?',['As informações disputariam prioridade','A hierarquia ficaria automaticamente melhor','O leitor sempre seguiria a ordem correta'],0,['Destaque é relativo. Quando tudo tem o mesmo destaque, a prioridade pode desaparecer.','Mais ênfase não significa uma ordem mais clara.','A sequência depende das relações, não de uma garantia automática.']),
 T('A prioridade depende da tarefa','Num aviso de interrupção de serviço, o período da interrupção pode ser tão importante quanto o título. Primeiro defina o que a pessoa precisa descobrir.'),
 Q('Um aviso tem um título enorme, mas o prazo aparece minúsculo. O que você deve fazer?',['Ajustar a hierarquia à importância do prazo para o cidadão','Manter o prazo pequeno porque títulos sempre dominam tudo','Acrescentar uma textura atrás do texto'],0,['Hierarquia serve à tarefa. Uma informação crítica não pode ficar ilegível só para preservar um efeito.','Não existe regra que justifique esconder uma informação essencial.','Textura não corrige a prioridade nem o tamanho de leitura.'])
]);
P('design:5','Usar colunas, margens e alinhamentos como estrutura.','Grid organiza relações; não exige preencher todas as colunas nem impede variação.',[
 T('Enxergue as linhas invisíveis','As faixas representam quatro colunas. A foto ocupa duas; o texto ocupa as outras duas. O título se alinha à mesma margem esquerda.','grid'),
 Q('Qual decisão cria coerência entre título, foto e texto?',['Compartilhar alinhamentos do grid','Usar uma fonte diferente em cada linha','Distribuir cada elemento sem referência comum'],0,['O grid oferece pontos de referência compartilhados, criando relações consistentes.','Variar fontes não produz alinhamento por si só.','Sem referência, a distribuição pode parecer arbitrária.'],'grid'),
 T('Coluna não é uma caixa obrigatória','Um título pode atravessar quatro colunas e uma foto ocupar duas. A estrutura dá opções de combinação, desde que o propósito e o alinhamento permaneçam claros.','grid'),
 Q('O espaço entre duas colunas é chamado de…',['gutter ou entrecoluna','sangria','altura-x'],0,['É o intervalo que separa colunas.','Sangria é extensão de conteúdo além da linha de corte.','Altura-x é uma medida da anatomia tipográfica.']),
 T('No celular, reorganize','Uma composição de duas áreas lado a lado pode virar uma coluna. Preserve a ordem de leitura e relações de proximidade; não apenas encolha a peça inteira.'),
 Q('Uma tabela larga fica ilegível quando reduzida para caber. Qual revisão faz mais sentido?',['Adaptar a apresentação e preservar uma leitura utilizável','Reduzir ainda mais a fonte para evitar qualquer rolagem','Converter tudo em uma imagem pequena'],0,['O objetivo é acesso à informação. Dependendo da tabela, use reorganização ou rolagem sinalizada.','Caber fisicamente não equivale a ser legível.','Uma imagem pequena mantém o problema e pode impedir seleção e leitura assistiva.'])
]);
P('design:6','Identificar partes das letras em exemplos visíveis.','Altura-x, ascendentes e descendentes são relações de desenho; famílias têm características, não funções fixas.',[
 T('Veja as letras por dentro','A linha inferior é a base. O “a” mostra o corpo de uma minúscula. A haste do “b” sobe; parte do “g” desce abaixo da base.','anatomy'),
 Q('A parte do “g” abaixo da linha de base é…',['descendente','ascendente','entrelinha'],0,['Descendente é a parte que ultrapassa a linha de base para baixo.','Ascendente ultrapassa a altura-x para cima, como na haste do b.','Entrelinha é o espaço entre linhas de texto.'],'anatomy'),
 T('Mesma mensagem, desenhos diferentes','Compare os remates da serifada, a estrutura sem serifa e a largura regular da monoespaçada. Essa última costuma facilitar a organização de código.','typography'),
 Q('Uma fonte sem serifa é sempre mais legível que uma serifada?',['Não; tamanho, desenho, suporte e espaçamento também importam','Sim; a presença de serifa impede leitura','Sim; a família elimina a necessidade de testes'],0,['A categoria é apenas uma característica. A leitura precisa ser avaliada no uso real.','Serifas não impedem leitura; muitas publicações as utilizam com bons resultados.','Nenhuma categoria dispensa testar contraste, escala e contexto.']),
 T('Duas medidas de espaçamento','Kerning ajusta pares específicos, como A e V. Tracking altera o espaçamento de uma sequência. Entrelinha atua na distância vertical entre linhas.'),
 Q('Um par “AV” parece afastado demais dentro de uma palavra. O ajuste mais específico é…',['kerning','entrelinha','sangria'],0,['Kerning atua na relação daquele par. Tracking alteraria a sequência toda.','Entrelinha atua verticalmente entre linhas.','Sangria pertence à produção gráfica.'])
]);
P('design:7','Diagnosticar o que dificulta a leitura de uma mensagem.','Legibilidade depende do desenho e das condições de leitura; organização textual também influencia a fluência.',[
 T('Leia as duas versões','A mensagem é a mesma. Compare o esforço necessário para identificar as palavras e seguir as linhas.','legibility'),
 Q('Qual diagnóstico descreve melhor a primeira versão?',['Tamanho, contraste e espaçamento dificultam a leitura','O texto tem necessariamente uma informação errada','O tema impede que seja legível'],0,['São condições visuais observáveis. O conteúdo não precisa estar errado para ser difícil de ler.','O enunciado continua igual na segunda versão.','O assunto não determina a legibilidade.'],'legibility'),
 T('Teste no destino','Uma legenda lida a centímetros de uma tela e uma placa vista a metros precisam de decisões diferentes. Avalie escala, distância, iluminação e suporte.'),
 Q('Um cartaz ficou bonito no monitor, mas será visto de longe. Qual teste é mais útil?',['Avaliar a leitura no tamanho e na distância de uso','Ver apenas uma miniatura na tela','Conferir somente o nome da fonte'],0,['O contexto de uso revela dificuldades que a tela de edição pode ocultar.','Uma miniatura não reproduz, sozinha, todas as condições do cartaz real.','O nome da fonte não informa o desempenho naquela aplicação.']),
 T('Destaque com propósito','Caixa-alta pode funcionar em rótulos curtos. Num parágrafo longo, seu uso contínuo pode reduzir diferenças de forma e tornar a leitura menos confortável. Não transforme uma tendência em proibição absoluta.'),
 Q('Qual alteração preserva melhor a mensagem de um parágrafo pequeno e apertado?',['Aumentar a escala e ajustar a entrelinha, revendo o espaço disponível','Aplicar contorno em todas as letras','Reduzir a largura das letras até tudo caber'],0,['Ajustar a composição ao texto é mais consistente que deformar os caracteres.','Contornos podem aumentar ruído e não resolvem necessariamente a escala.','Deformação pode comprometer o desenho e a leitura.'])
]);
P('design:8','Experimentar a mistura aditiva e distinguir luz de tinta.','RGB combina luz; CMYK organiza tintas no processo de impressão. Conversão depende de perfis e condições.',[
 T('Acenda as luzes','Mantenha R em 255 e aumente G até 255. Depois, acrescente B. Observe amarelo e branco surgindo no quadro.','color'),
 Q('Com R=255, G=255 e B=0, o resultado é…',['amarelo','preto','ciano'],0,['Vermelho e verde, na mistura aditiva RGB, produzem amarelo.','Preto corresponde a ausência de luz: os três canais em zero.','Ciano resulta de verde e azul.']),
 T('O suporte muda a lógica','Na tela, somamos luz. Na impressão, tintas absorvem parte da luz refletida pelo papel. CMY ideal combina ciano, magenta e amarelo; o preto K ajuda a reprodução e o controle no processo real.'),
 Q('Por que um azul intenso de tela pode mudar ao imprimir?',['As gamas, os perfis e o processo de reprodução diferem','Todo arquivo RGB está corrompido','A impressora transforma qualquer azul em verde'],0,['Nem toda cor reproduzível em um dispositivo cabe na gama do outro. Perfis ajudam a gerenciar a conversão.','RGB é um modelo válido. O problema é a reprodução no destino.','A mudança não segue essa regra universal.']),
 T('Escolha pelo destino','Para fechar um impresso, confirme o perfil e as especificações da gráfica. Converter sem conhecer o processo pode produzir um resultado diferente do esperado.'),
 Q('Uma foto RGB precisa ir para uma gráfica. Qual caminho é mais responsável?',['Confirmar especificações, gerenciar a conversão e avaliar prova','Trocar a extensão para .cmyk','Aumentar saturação até parecer mais forte'],0,['O destino orienta o tratamento e a avaliação da cor.','Mudar o nome de um arquivo não converte seus dados.','Saturar mais não garante correspondência e pode perder detalhe.'])
]);
P('design:9','Comparar relações entre matizes sem confundir harmonia e legibilidade.','Relações angulares dependem do círculo escolhido; harmonia não garante contraste de leitura.',[
 T('Três relações diferentes','Complementares ficam opostas; análogas, próximas; uma tríade usa três intervalos iguais. Aqui usamos relações do círculo RGB/HSV.','harmony'),
 Q('No círculo RGB/HSV, qual matiz fica oposto ao vermelho?',['Ciano','Verde','Laranja'],0,['Vermelho e ciano estão a 180° no círculo RGB/HSV.','Vermelho–verde é uma relação tradicional no círculo artístico RYB, outro modelo.','Laranja é próximo do vermelho neste círculo.'],'harmony'),
 T('Paleta não resolve tudo','Duas cores podem formar uma harmonia e ainda ter luminosidades próximas. Nesse caso, um texto sobre o fundo pode ficar difícil de ler.','contrast'),
 Q('Uma paleta é complementar. Isso basta para aprovar o contraste de um texto?',['Não; é preciso avaliar o contraste entre texto e fundo','Sim; oposição cromática garante acessibilidade','Sim; basta que sejam cores diferentes'],0,['A relação de matiz não determina sozinha a diferença de luminância.','Complementaridade não é um certificado de contraste.','Cores diferentes podem apresentar contraste insuficiente.']),
 T('Um procedimento simples','Escolha a relação de matiz; defina a função de cada cor; teste texto e fundo; confira estados e variações. A paleta deve servir à informação.'),
 Q('Três matizes separados por 120° formam uma relação…',['triádica','análoga','monocromática'],0,['Três intervalos iguais de 120° completam o círculo.','Análogas ocupam setores próximos.','Monocromática trabalha variações de um mesmo matiz.'])
]);
P('design:16','Distinguir corte, sangria e margem de segurança em uma peça.','O fundo avança além do corte; informações essenciais ficam protegidas dentro dele.',[
 T('O corte tem tolerância','Imagine uma pequena variação na guilhotina. Se o fundo terminar exatamente na borda final, pode surgir um filete branco. A sangria estende esse fundo.','bleed'),
 Q('Qual conteúdo deve normalmente continuar para além da linha de corte?',['O fundo ou a imagem que chega à borda','O telefone essencial ao atendimento','Todo o texto, inclusive o título'],0,['O avanço evita filetes caso o corte varie.','Informação essencial deve ficar dentro da área segura.','Texto não deve ser levado para uma área que será removida.'],'bleed'),
 T('Segurança é outra área','Sangria fica fora do formato final. Margem de segurança fica dentro, afastando texto e elementos importantes do corte. Não confunda as duas.'),
 Q('A gráfica pede sangria de 3 mm. Essa medida é uma regra universal?',['Não; siga a especificação do processo e do fornecedor','Sim; qualquer produto exige exatamente 3 mm','Não; sangria nunca é necessária'],0,['3 mm é uma solicitação possível, mas o projeto e o processo podem exigir outra medida.','Uma prática comum não vira regra universal.','Sangria pode ser necessária quando o conteúdo chega ao corte.']),
 T('Antes de exportar','Confira formato, sangria, segurança, imagens, fontes e perfil solicitado. Uma marca de corte não cria automaticamente a área de sangria.'),
 Q('Você colocou marcas de corte, mas o fundo termina na linha final. O que falta?',['Estender o fundo até a área de sangria','Mover o texto para fora da página','Adicionar somente uma borda preta'],0,['As marcas orientam o corte; não inventam conteúdo externo.','Mover texto para fora causa perda de informação.','Uma borda não substitui a extensão do fundo.'])
]);
P('design:18','Entender por que ampliar uma foto pode expor pixels.','Pixels são amostras; ppi relaciona essas amostras ao tamanho físico de reprodução.',[
 T('A mesma cena, menos amostras','À direita, a fotografia foi reduzida a 24 pixels de largura e ampliada. Os blocos ficam visíveis porque faltam amostras para representar os detalhes.','pixels'),
 Q('Mudar apenas o valor de ppi recupera os detalhes ausentes?',['Não; não cria novas informações da cena','Sim; basta digitar 300','Sim; se o arquivo for salvo como PDF'],0,['Ppi relaciona pixels e tamanho físico. Interpolar pode estimar pixels, mas não recupera automaticamente o detalhe original.','300 é uma densidade, não uma operação mágica de reconstrução.','PDF é um contêiner; pode continuar contendo a mesma imagem de baixa resolução.'],'pixels'),
 T('Faça a relação','Largura em polegadas = largura em pixels ÷ ppi. Uma foto de 1800 pixels a 300 ppi ocupa 6 polegadas, aproximadamente 15,24 cm.'),
 I('Uma imagem de 2400 pixels a 300 ppi tem quantas polegadas de largura?',['8','8 polegadas'],'2400 ÷ 300 = 8 polegadas. A conta liga amostras digitais ao tamanho físico.'),
 T('Vetor segue outra lógica','Uma forma vetorial é descrita por geometria. Ela pode ser redesenhada em outra escala. Mas um SVG ou PDF também pode conter uma fotografia incorporada.','vector'),
 Q('Salvar uma miniatura JPG dentro de um SVG torna a foto vetorial?',['Não; o arquivo pode conter pixels incorporados','Sim; a extensão define todo o conteúdo','Sim; porque SVG elimina a resolução'],0,['É preciso distinguir o formato do arquivo da natureza dos elementos dentro dele.','A extensão não garante que todos os elementos sejam vetoriais.','O raster incorporado continua tendo uma quantidade de pixels.'])
]);
P('design:22','Identificar problemas de contraste e de uso exclusivo de cor.','Contraste de texto e alternativas à cor são verificações diferentes de acessibilidade.',[
 T('Compare o esforço de leitura','Os dois textos estão em fundo branco. Na primeira linha, o cinza claro reduz o contraste. Tamanho e peso também influenciam a condição de leitura.','contrast'),
 T('O critério tem números','No nível AA da WCAG, texto comum exige contraste de pelo menos 4,5:1. Texto grande pode usar 3:1: pelo menos 18 pt, ou 14 pt em negrito. Há exceções específicas, como logotipos e texto incidental.'),
 Q('Um parágrafo comum tem contraste medido de 3,2:1. Ele atende ao mínimo AA para texto comum?',['Não; precisa de pelo menos 4,5:1','Sim; qualquer valor acima de 3:1 basta','Sim; desde que a cor seja azul'],0,['A redução para 3:1 não se aplica a qualquer parágrafo.','3:1 é o limite para texto grande nas condições do critério.','O nome da cor não determina a razão de contraste.']),
 T('Cor sozinha pode não bastar','Se um formulário mostra erro apenas trocando a borda para vermelho, parte das pessoas pode não perceber. Acrescente mensagem e identificação clara do campo.'),
 Q('Qual feedback de erro comunica além da cor?',['“Informe uma data válida” junto ao campo identificado','Apenas uma borda vermelha','Uma animação rápida sem texto'],0,['A mensagem descreve o problema e não exige distinguir apenas uma cor.','A borda depende exclusivamente da distinção cromática.','Uma animação não explica necessariamente o problema e pode passar despercebida.']),
 T('Aplique em duas verificações','Primeiro confira contraste suficiente. Depois pergunte se alguma informação depende só de cor. Aprovar um desses itens não aprova automaticamente o outro.')
],'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html');
P('design:31','Escolher ferramentas pelo tipo de trabalho.','Raster, vetor e editoração cumprem funções diferentes e podem participar do mesmo projeto.',[
 T('Comece pelo material','Fotografias são representadas por pixels. Símbolos podem ser construídos por curvas. Publicações organizam imagens e textos em páginas. A tarefa orienta a ferramenta.','pixels'),
 Q('Para criar um símbolo escalável, qual grupo tem finalidade principal vetorial?',['Illustrator, CorelDRAW e Inkscape','Photoshop e GIMP','InDesign e Scribus'],0,['São ferramentas de criação vetorial, embora também possam lidar com outros tipos de conteúdo.','O foco principal dessas ferramentas é o tratamento raster.','O foco é editoração e diagramação de páginas.'],'vector'),
 T('Monte um fluxo','Uma cartilha pode começar no tratamento da foto, passar pela criação dos símbolos e terminar na diagramação. Preserve arquivos editáveis, vínculos e licenças.'),
 Q('Qual sequência combina as finalidades de foto, símbolo e cartilha?',['GIMP → Inkscape → Scribus','Scribus → GIMP → Inkscape','Inkscape → Scribus → GIMP'],0,['Raster, vetor e editoração, respectivamente.','A ordem não corresponde às finalidades principais pedidas.','Essa ordem também troca as finalidades pedidas.']),
 T('Confira a saída','Exportar um símbolo para PNG gera uma imagem raster. Isso pode ser adequado à entrega, mas o arquivo vetorial editável continua importante.'),
 Q('O cliente precisa de PNG para o site. Você deve descartar o vetor original?',['Não; preserve o editável e gere a saída necessária','Sim; PNG substitui o editável em qualquer uso','Sim; o vetor não tem outra utilidade'],0,['Uma entrega não substitui todos os usos futuros. O vetor permite mudanças e outras escalas.','PNG não preserva a estrutura vetorial editável.','O original continua útil para manutenção e outras saídas.'])
]);
P('pt:0','Separar informação expressa, inferência e extrapolação.','Uma inferência precisa de apoio no texto; uma possibilidade não vira fato só por parecer plausível.',[
 T('Leia o trecho curto','Procure duas informações: qual modalidade foi suspensa e qual continua disponível. Não acrescente causas que o trecho não oferece.','inference'),
 Q('Qual afirmação está expressa no trecho?',['Pedidos continuam disponíveis pelo portal','Todos os serviços foram encerrados','A suspensão ocorreu por falta de funcionários'],0,['A segunda frase informa a continuidade pelo portal.','“Atendimento presencial” não significa todos os serviços.','O texto não apresenta a causa da suspensão.'],'inference'),
 T('Agora conecte as informações','É possível concluir que a suspensão do atendimento presencial não eliminou toda possibilidade de fazer pedidos. Essa conclusão combina as duas frases.'),
 Q('Qual alternativa extrapola o trecho?',['O prédio sofreu uma reforma nesta sexta-feira','O presencial foi suspenso naquela sexta-feira','O portal continuou oferecendo pedidos'],0,['Reforma seria uma causa possível, mas não foi informada.','Essa informação está expressa no trecho.','Essa informação também está expressa.']),
 T('Cuidado com palavras absolutas','“Todos”, “nunca”, “somente” e “sempre” podem ampliar ou restringir o sentido sem apoio. Compare a força da alternativa com a força do que foi escrito.'),
 Q('“Pedidos continuam disponíveis pelo portal” prova que só o portal pode receber pedidos?',['Não; não foi dito “somente”','Sim; disponibilidade significa exclusividade','Sim; qualquer outro canal está proibido'],0,['A frase afirma disponibilidade, não exclusividade.','São relações diferentes.','Não há proibição de outros canais no trecho.'])
]);
P('pt:2','Reconhecer uma retomada e testar a coerência de uma ligação.','Coesão liga partes do texto; coerência envolve a construção global de sentido.',[
 T('Veja a ligação','“O documento” retoma “o edital”. A expressão evita repetição e mantém o referente. Não é um pronome: é uma expressão nominal.','cohesion'),
 Q('Qual mecanismo aparece nessa retomada?',['Substituição lexical para manter o referente','Uso obrigatório de pronome demonstrativo','Troca do assunto para um novo documento'],0,['O edital é retomado por outra expressão nominal.','“O documento” não contém pronome demonstrativo. “Esse documento” conteria.','O contexto apresenta continuidade, não um novo referente.'],'cohesion'),
 T('O conectivo dá uma pista','Em “Estudou, portanto avançou”, “portanto” indica conclusão. Em “Estudou, mas não avançou”, “mas” estabelece oposição à expectativa.'),
 Q('Qual conectivo preserva uma relação de conclusão?',['Portanto','Embora','Apesar de'],0,['“Portanto” introduz uma conclusão decorrente do que veio antes.','“Embora” introduz concessão.','“Apesar de” também expressa concessão.']),
 T('Ligação não garante sentido','“Ele faltou a todos os encontros, portanto esteve presente em todos” tem conectivo, mas cria uma contradição no contexto comum. Coesão e coerência não são sinônimos.'),
 Q('Um texto cheio de conectivos é necessariamente coerente?',['Não; as relações de sentido também precisam se sustentar','Sim; conectivos impedem contradições','Sim; basta substituir palavras repetidas'],0,['É preciso avaliar o que as frases afirmam e como se relacionam.','Conectivos não corrigem contradições automaticamente.','Substituição lexical não garante sentido global.'])
]);
P('pt:5','Decidir se existem os dois elementos que formam a crase.','No caso básico, a crase funde a preposição a com o artigo a; não aparece só porque a palavra seguinte é feminina.',[
 T('Procure os dois “a”','Na construção “ir à Câmara”, o verbo pede preposição a e o substantivo admite artigo a. A fusão é marcada pelo acento grave.','crase'),
 Q('Qual raciocínio justifica “à Câmara” nesse exemplo?',['Preposição a + artigo a','Qualquer palavra feminina exige crase','Toda palavra com inicial maiúscula exige crase'],0,['São as duas condições do exemplo. O teste masculino “ao plenário” ajuda a reconhecê-las.','Há palavras femininas sem artigo e construções sem a preposição.','Maiúscula não decide crase.'],'crase'),
 T('Use um teste compatível','“Fui ao plenário” ajuda a verificar “fui à Câmara”. Mantenha a estrutura. O teste não substitui o estudo de locuções e casos especiais.'),
 Q('Em “Começou a estudar”, por que não há crase?',['O infinitivo estudar não recebe artigo feminino','Verbos nunca podem aparecer perto de crase','O verbo começar só existe no passado'],0,['Não existe artigo a para se fundir com a preposição.','A proximidade gráfica não é o critério. Analise a construção.','Tempo verbal não explica esse caso.']),
 Q('Complete: “Entreguei o formulário ___ ela”.',['a','à','há'],0,['O pronome pessoal ela não recebe artigo feminino nesse uso; fica apenas a preposição.','Não há artigo para formar a fusão.','“Há” é forma do verbo haver e não cumpre essa função.']),
 T('Guarde o mecanismo','Primeiro examine a regência. Depois veja se o termo admite artigo ou outro elemento que participe da fusão. Não decida apenas pelo gênero da palavra.')
]);
P('pt:7','Identificar sujeito, verbo e complemento em uma oração.','A função sintática depende da relação na oração; nem todo termo próximo do verbo é sujeito.',[
 T('Divida a oração pelo papel','Quem revisou? A equipe de comunicação. Revisou o quê? O cartaz. O verbo organiza essas relações.','syntax'),
 Q('Qual é o núcleo do sujeito?',['equipe','comunicação','cartaz'],0,['“Equipe” é o núcleo. “De comunicação” caracteriza essa equipe.','Esse termo integra uma expressão que modifica o núcleo equipe.','Cartaz é o objeto da ação neste exemplo.'],'syntax'),
 T('Direto ou indireto?','“Revisou o cartaz” tem objeto direto. Em “precisa de revisão”, o verbo exige a preposição de, formando objeto indireto. Não classifique pela proximidade.'),
 Q('Em “A equipe precisa de revisão”, “de revisão” é…',['objeto indireto','sujeito','predicativo do sujeito'],0,['O termo completa o sentido de precisar com preposição exigida pelo verbo.','O sujeito é a equipe.','Não se atribui uma característica por verbo de ligação neste exemplo.']),
 T('A ordem pode mudar','Em “O cartaz, a equipe revisou ontem”, a posição inicial de “o cartaz” não o transforma em sujeito. Reconstrua a relação com o verbo.'),
 Q('Em “Chegaram os documentos”, qual é o sujeito?',['os documentos','um sujeito inexistente','chegaram'],0,['Os documentos é o sujeito posposto e determina o plural de chegaram.','O verbo chegar não torna a oração sem sujeito.','Chegaram é o verbo.'])
]);
P('pt:11','Perceber como a pontuação modifica a interpretação.','Pontuar é marcar relações da construção, não apenas pausas da fala.',[
 T('Uma vírgula muda a orientação','Na primeira frase, alguém nega uma ideia anterior e pede que se espere. Na segunda, a negação recai sobre esperar.','punctuation'),
 Q('Qual frase orienta a pessoa a não esperar?',['Não espere.','Não, espere.','As duas têm obrigatoriamente o mesmo sentido.'],0,['Sem a vírgula, não modifica diretamente espere.','Com a vírgula, a orientação é espere.','A mudança de pontuação altera a relação.'],'punctuation'),
 T('Não separe sujeito e verbo','Na ordem básica “A equipe revisou o cartaz”, não cabe uma vírgula apenas entre “a equipe” e “revisou”. Um termo intercalado pode ser isolado por duas vírgulas.'),
 Q('Qual frase preserva corretamente essa estrutura?',['A equipe, após a reunião, revisou o cartaz.','A equipe, revisou o cartaz.','A equipe revisou, o cartaz.'],0,['As duas vírgulas delimitam um adjunto intercalado.','A vírgula separa diretamente sujeito e verbo sem motivo.','A vírgula separa diretamente verbo e objeto nesse caso.']),
 T('Restrição e explicação','“Os servidores que estudaram passaram” restringe o grupo. “Os servidores, que estudaram, passaram” apresenta a oração como explicação sobre o grupo referido.'),
 Q('Retirar vírgulas de uma oração adjetiva pode mudar o sentido?',['Sim; pode mudar explicação para restrição','Não; vírgulas são apenas respiração','Não; adjetivas nunca são delimitadas'],0,['O alcance do grupo referido pode mudar.','Pontuação tem função sintática e semântica.','Orações explicativas são delimitadas por vírgulas.'])
]);
P('math:1','Reconstruir uma proporção pelo valor de uma unidade.','Antes de multiplicar cruzado, identifique as grandezas e a relação entre elas.',[
 T('Descubra uma unidade','Três cartazes custam R$ 24. Neste exemplo, o preço unitário é constante. Divida 24 por 3 para descobrir o custo de um cartaz.','ratio'),
 I('Qual é o custo de um cartaz, em reais?',['8','8,00','8.00'],'24 ÷ 3 = 8. A unidade intermediária torna a relação visível.','ratio'),
 I('Quanto custam cinco cartazes nesse mesmo preço unitário?',['40','40,00','40.00'],'5 × 8 = 40. A quantidade e o custo são diretamente proporcionais nessa hipótese.'),
 T('A hipótese importa','Se houver uma taxa fixa de preparação, o custo total pode deixar de ser diretamente proporcional à quantidade. Não aplique a relação só porque há dois números.'),
 Q('Dobrar a quantidade sempre dobra o custo total de qualquer serviço?',['Não; taxas fixas e outras regras podem mudar a relação','Sim; é uma regra universal','Sim; independentemente do enunciado'],0,['A proporcionalidade precisa ser informada ou sustentada pelo contexto.','É necessário examinar a relação entre as grandezas.','O enunciado define as condições do problema.']),
 T('Leve o método para outra questão','Identifique o que varia, ache a unidade quando possível e confira se aumentar uma grandeza aumenta ou diminui a outra.')
]);
P('math:3','Calcular porcentagem e entender por que aumentos e descontos não se anulam.','A porcentagem age sobre uma base. Quando a base muda, o mesmo percentual representa outro valor.',[
 T('20% é uma relação','Na grade, vinte dos cem quadrados estão azuis. Isso equivale a 20/100 = 0,20. Para achar 20% de um total, multiplique esse total por 0,20.','percent'),
 I('Quanto é 20% de R$ 200? Digite só o valor.',['40','40,00','40.00'],'0,20 × 200 = 40. Esse é o desconto, não o preço final.'),
 T('Agora encontre o restante','Depois de descontar R$ 40, restam R$ 160. Você também pode calcular diretamente 80% de 200: 0,80 × 200.','price'),
 I('Um produto de R$ 100 aumenta 20%. Qual é o novo preço?',['120','120,00','120.00'],'100 × 1,20 = 120. Agora 120 é a nova base.'),
 I('Sobre os R$ 120, aplique desconto de 20%. Qual é o preço final?',['96','96,00','96.00'],'120 × 0,80 = 96. O desconto foi R$ 24, maior que o aumento de R$ 20.'),
 Q('Por que +20% e depois −20% não voltaram ao início?',['Os percentuais atuaram sobre bases diferentes','Porcentagem não pode ter desconto','Os dois fatores deveriam ser somados'],0,['Os fatores se multiplicam: 1,20 × 0,80 = 0,96. O resultado é 96% da base original.','Descontos podem ser expressos em porcentagens.','As mudanças são sucessivas, então cada fator age no resultado anterior.'])
]);
P('math:5','Resolver uma equação preservando o equilíbrio.','Faça a mesma operação nos dois membros; o objetivo é isolar a incógnita.',[
 T('Pense em equilíbrio','A equação 2x + 4 = 10 representa duas expressões com o mesmo valor. Uma operação aplicada apenas a um lado pode destruir essa igualdade.','balance'),
 Q('Qual é um primeiro passo válido?',['Subtrair 4 dos dois lados','Subtrair 4 só do lado esquerdo','Trocar 10 por 4 sem outra operação'],0,['Fica 2x = 6. A mesma operação preserva a igualdade.','Nesse caso, os dois lados deixam de representar valores iguais.','Essa troca não é justificada.'],'balance'),
 I('Depois de obter 2x = 6, qual é o valor de x?',['3'],'Divida ambos os lados por 2: x = 3.'),
 T('Verifique na expressão original','Substitua x por 3: 2 × 3 + 4 = 10. O resultado confirma a solução. Fazer a verificação ajuda a encontrar erros de sinal.'),
 I('Agora resolva: 3x − 6 = 12. Quanto vale x?',['6'],'Some 6 aos dois lados: 3x=18. Divida por 3: x=6.'),
 Q('“Passar para o outro lado trocando o sinal” é um atalho para…',['aplicar a operação inversa nos dois lados','mudar sinais sem preservar a igualdade','eliminar qualquer número da equação'],0,['O fundamento é uma operação equivalente nos dois membros.','Troca arbitrária não produz uma equação equivalente.','Não é possível eliminar termos sem uma operação válida.'])
]);
P('math:10','Distinguir crescimento por diferença e por razão.','PA mantém diferença constante; PG mantém razão constante quando a divisão está definida.',[
 T('Observe o salto','A sequência 2, 5, 8 aumenta sempre 3. Esse salto constante é a razão da progressão aritmética.','pa'),
 I('Qual é o próximo termo de 2, 5, 8?',['11'],'8 + 3 = 11. A diferença entre termos consecutivos é 3.','pa'),
 T('Conte os intervalos','Do primeiro ao quinto termo há quatro saltos. Por isso a fórmula é aₙ=a₁+(n−1)r. Não use n saltos partindo do primeiro termo.'),
 I('Na PA que começa em 2 e tem razão 3, qual é o quinto termo?',['14'],'2 + (5−1) × 3 = 14.'),
 Q('Na sequência 2, 6, 18, 54, o padrão é…',['multiplicar por 3: uma PG','somar 3: uma PA','somar sempre o mesmo número'],0,['A razão 6/2=18/6=54/18 é 3.','As diferenças são 4, 12 e 36, não 3.','As diferenças não são constantes.']),
 T('Antes da fórmula','Compare diferenças e razões. Só depois use a fórmula apropriada. Um padrão curto, sem regra declarada, pode admitir outras continuações matemáticas.')
]);
P('math:11','Decidir se a ordem altera o resultado antes de contar.','Cargos distintos tornam a ordem relevante; grupos sem cargos não distinguem permutações internas.',[
 T('Mesmas pessoas, resultados diferentes?','Ana presidente e Bia secretária não é igual a Bia presidente e Ana secretária. Mas uma comissão formada por Ana e Bia é a mesma dupla nas duas ordens.','combination'),
 Q('Escolher presidente e secretário entre cinco pessoas, sem acumular cargos, dá quantas possibilidades?',['20','10','25'],0,['Há 5 opções para presidente e 4 restantes para secretário: 5 × 4 = 20.','10 seria o número de duplas sem distinguir cargos.','25 permitiria a mesma pessoa nos dois cargos.']),
 T('Remova a contagem duplicada','Para uma comissão de duas pessoas sem cargos, cada dupla foi contada duas vezes: Ana–Bia e Bia–Ana. Divida 20 por 2! e obtenha 10.'),
 I('Uma comissão de duas pessoas entre cinco, sem cargos, pode ser formada de quantas maneiras?',['10'],'C(5,2)=5×4/2=10. A ordem dos membros não cria nova comissão.'),
 Q('Qual pergunta decide primeiro entre arranjo e combinação?',['Trocar a ordem produz um resultado diferente?','O enunciado tem números grandes?','As pessoas têm o mesmo nome?'],0,['A relevância da ordem é central; também confira repetição e quantidade selecionada.','O tamanho dos números não decide o tipo de contagem.','O que importa é se as escolhas são distinguíveis no problema.']),
 T('Guarde uma decisão, não só uma fórmula','Seleção ordenada sem repetição usa arranjo. Seleção sem ordem usa combinação. Organizar todos os elementos distintos usa permutação.')
]);
P('math:13','Comparar média e mediana diante de um valor extremo.','A média usa todos os valores; a mediana depende da posição no conjunto ordenado.',[
 T('Ache o centro','Os valores são 2, 3, 4, 5 e 6. A soma é 20, então a média é 4. O valor central ordenado também é 4: a mediana.','stats'),
 T('Mude só uma observação','Troque o 6 por 20. A soma vira 34, mas o terceiro valor da lista ordenada continua sendo 4.','outlier'),
 I('Qual é a nova média de 2, 3, 4, 5 e 20?',['6,8','6.8'],'34 ÷ 5 = 6,8. O valor extremo eleva a média.','outlier'),
 I('Qual é a mediana desse mesmo conjunto?',['4'],'O terceiro valor ordenado é 4. Não confunda a posição central com a média dos cinco números.'),
 T('E quando são quatro valores?','Em 3, 5, 8 e 10, os centrais são 5 e 8. A mediana é (5+8)/2 = 6,5. Ordenar vem antes de localizar o centro.'),
 Q('Média e mediana precisam ser iguais?',['Não; dependem da distribuição dos valores','Sim; são dois nomes para a mesma medida','Sim; se todos os números forem positivos'],0,['Podem coincidir em alguns conjuntos e divergir em outros.','São medidas construídas de formas diferentes.','Serem positivos não garante igualdade.'])
]);
P('math:15','Usar as regiões de dois conjuntos para operar sem confusão.','União reúne; interseção seleciona o comum; diferença retira os elementos do outro conjunto.',[
 T('Leia as regiões','1 e 2 estão só em A. O 3 pertence a ambos. O 4 está só em B. A localização explica as operações.','sets'),
 Q('Qual é A ∩ B?',['{3}','{1,2,3,4}','{1,2}'],0,['Interseção contém apenas o elemento comum.','Esse é o conjunto união.','Essa é a diferença A−B.'],'sets'),
 Q('Qual é A − B?',['{1,2}','{3}','{4}'],0,['Retire de A o que também pertence a B: sobra 1 e 2.','3 é comum e deve ser retirado nessa operação.','4 forma B−A, a operação inversa.'],'sets'),
 T('Não conte duas vezes','Se 18 pessoas usam A, 12 usam B e 5 usam ambos, a soma 18+12 conta essas cinco duas vezes. Subtraia uma das contagens.'),
 I('Quantas pessoas usam ao menos um, nesse caso?',['25'],'18 + 12 − 5 = 25.'),
 Q('A diferença A−B sempre é igual a B−A?',['Não; a ordem da diferença importa','Sim; as duas retiram os mesmos elementos','Sim; sempre resultam na interseção'],0,['No desenho, A−B={1,2} e B−A={4}.','Cada diferença começa em um conjunto diferente.','Interseção é outra operação.'])
]);
P('info:0','Executar um algoritmo na ordem e distinguir condição de repetição.','Um algoritmo descreve passos; cada decisão deve ter uma condição verificável.',[
 T('Siga uma instrução de cada vez','A seta significa atribuição. Primeiro x recebe 2. Depois passa a conter o triplo do valor atual. Por fim, soma-se 4 a esse resultado.','code'),
 I('Depois de x ← x × 3, quanto vale x?',['6'],'O valor anterior era 2. Logo, 2 × 3 = 6.','code'),
 I('Qual valor aparece em “mostrar x”?',['10'],'A última atribuição usa 6 + 4 = 10. Não volte ao valor inicial.'),
 T('Decisão não é repetição','“Se o arquivo existe, abra” testa uma condição para decidir. “Enquanto houver arquivos, processe o próximo” repete e volta a testar a condição.'),
 Q('Qual estrutura volta a testar a condição para repetir um bloco?',['Enquanto','Uma atribuição isolada','Mostrar resultado'],0,['Enquanto controla repetição enquanto a condição permanece verdadeira.','Atribuição atualiza um valor; sozinha não repete.','Saída de dados não é uma estrutura de repetição.']),
 T('Antes de programar','Teste um caso comum e um caso limite. Pergunte o que acontece se não houver nenhum item ou se a condição já começar falsa.')
]);
P('info:1','Rastrear o valor de uma variável em um laço.','Teste a condição antes de cada repetição e registre o valor atualizado.',[
 T('Entre somente se a condição permitir','x começa em 2. Como 2 é menor que 6, executa a soma. Depois a condição será testada outra vez.','loop'),
 I('Após a primeira execução de x ← x + 2, quanto vale x?',['4'],'2 + 2 = 4. Agora compare 4 com 6.','loop'),
 I('Quando o laço termina, quanto vale x?',['6'],'A sequência é 2 → 4 → 6. Como 6 < 6 é falso, não há uma terceira soma.'),
 T('O operador faz diferença','Se a condição fosse x ≤ 6, o corpo ainda executaria quando x fosse 6. O valor final seria 8. Não trate < e ≤ como equivalentes.'),
 Q('Em JavaScript, 7 === "7" resulta em…',['false','true','14'],0,['A comparação estrita não converte a string em número: os tipos são diferentes.','A comparação estrita leva em conta a diferença de tipos.','=== compara; não soma.']),
 T('Outras linguagens, outros operadores','Em Python, 7 // 2 resulta em 3: divisão pelo piso. len([10,20,30]) resulta em 3: quantidade de elementos. Identifique a linguagem antes de interpretar a sintaxe.')
]);
P('info:5','Distinguir processamento, memória de trabalho e armazenamento.','CPU executa; RAM mantém dados de trabalho; SSD preserva arquivos sem energia.',[
 T('Acompanhe um arquivo','O arquivo salvo está no armazenamento. Ao abrir e editar, dados de trabalho ocupam a RAM e a CPU executa instruções. O desenho simplifica esse fluxo.','memory'),
 Q('Qual componente preserva normalmente o arquivo salvo após desligar o computador?',['SSD','RAM volátil','Registrador da CPU'],0,['SSD é armazenamento não volátil.','RAM comum depende de energia para manter seu conteúdo.','Registradores são memória interna de trabalho do processador.'],'memory'),
 T('Mais RAM não é mais espaço para arquivos','RAM suficiente ajuda a manter tarefas em uso. Capacidade do SSD determina quanto pode ser armazenado nele. Processador, memória e armazenamento afetam aspectos diferentes.'),
 Q('Um computador tem pouco espaço para guardar fotos. Qual recurso está diretamente ligado a essa limitação?',['Capacidade do armazenamento','Quantidade de núcleos, exclusivamente','Resolução do monitor'],0,['Espaço de arquivos é capacidade de armazenamento.','Núcleos influenciam processamento, não fornecem espaço para salvar fotos.','A resolução do monitor não aumenta o armazenamento.']),
 T('Periféricos também têm função','Teclado e scanner fornecem entrada; monitor e impressora apresentam saída. Alguns dispositivos combinam funções, como telas sensíveis ao toque.'),
 Q('Uma tela sensível ao toque realiza…',['entrada e saída','somente armazenamento','somente processamento central'],0,['Exibe informação e recebe interação pelo toque.','Ela não é classificada principalmente como armazenamento.','A CPU continua responsável pelo processamento central.'])
]);
P('info:7','Copiar uma fórmula mantendo a referência que deve ficar fixa.','O cifrão fixa a parte da referência: coluna, linha ou ambas.',[
 T('Leia a fórmula pelo propósito','A2 contém o valor. B2 contém a taxa. A fórmula multiplica o valor pela taxa fixa. Ao copiar uma linha abaixo, o valor passa para A3, mas a taxa continua em B2.','sheet'),
 Q('Ao copiar =A2*$B$2 uma linha abaixo, a fórmula fica…',['=A3*$B$2','=A3*$B$3','=A2*$B$2'],0,['A referência relativa A2 acompanha a linha. Coluna e linha de $B$2 estão fixas.','A linha de B2 está protegida pelo segundo cifrão.','A2 é relativa e muda ao copiar para baixo.'],'sheet'),
 T('Fixa referência, não conteúdo','Se você alterar o valor guardado em B2, todas as fórmulas que apontam para essa célula passam a usar o novo valor. Referência absoluta não torna o conteúdo imutável.'),
 Q('Em B$2, o que fica fixo ao copiar?',['A linha 2','A coluna B e a linha 2','Somente a coluna B'],0,['O cifrão antes de 2 fixa a linha. A coluna permanece relativa.','Para fixar ambas, use $B$2.','Para fixar apenas a coluna, use $B2.']),
 T('Cuidado com a configuração','Nomes de funções e separadores podem variar com o idioma: SOMA ou SUM, por exemplo. Leia a configuração declarada na questão.'),
 Q('A fórmula aponta para $B$2 e o conteúdo de B2 muda. O cálculo pode mudar?',['Sim; a referência é fixa, mas o valor pode mudar','Não; o cifrão bloqueia edição da célula','Não; referências absolutas deixam de recalcular'],0,['O cifrão controla o ajuste da referência ao copiar.','Proteção de célula é outro recurso.','Referência absoluta não impede recálculo.'])
]);
P('info:13','Diagnosticar qual propriedade da informação foi afetada.','Confidencialidade, integridade e disponibilidade protegem aspectos diferentes.',[
 T('Faça três perguntas','Quem consegue ler? O conteúdo foi alterado sem autorização? O serviço está acessível quando necessário? Cada pergunta aponta a uma propriedade.','cia'),
 Q('Uma pessoa sem autorização leu dados restritos, sem modificá-los. Qual propriedade foi diretamente violada?',['Confidencialidade','Disponibilidade','Somente capacidade de armazenamento'],0,['Houve acesso indevido à informação.','O problema relatado não foi indisponibilidade.','Capacidade não explica acesso indevido.'],'cia'),
 Q('Uma falha alterou os valores de uma planilha. Qual propriedade foi diretamente afetada?',['Integridade','Disponibilidade, necessariamente','Confidencialidade, necessariamente'],0,['A correção do conteúdo foi comprometida.','O arquivo pode continuar acessível e ainda estar alterado.','Não foi descrita leitura indevida.']),
 T('Uma medida não resolve tudo','Backup ajuda na recuperação, mas não impede sozinho acesso indevido. Autenticação verifica identidade; autorização define o que essa identidade pode fazer.'),
 Q('Você entrou com sua conta, mas não pode editar a folha de pagamento. Essa limitação é de…',['autorização','resolução de imagem','compactação'],0,['A identidade foi reconhecida; as permissões delimitam a ação.','Não se trata de imagem.','Compactação não controla permissões de edição.']),
 T('Use a falha como pista','Leitura indevida aponta a confidencialidade; alteração indevida, integridade; inacessibilidade, disponibilidade. Um incidente pode afetar mais de uma delas.')
]);
P('direito:0','Aplicar princípios da Administração a uma peça de comunicação.','A publicidade institucional deve servir ao interesse público; informação não se confunde com promoção pessoal.',[
 T('Compare a finalidade','As peças são fictícias. A primeira informa serviço, horário e local. A segunda desloca a atenção para exaltar uma autoridade. Esse contraste ajuda a aplicar a impessoalidade.','public'),
 Q('Qual problema é mais evidente na peça B?',['Indício de promoção pessoal de autoridade','Ausência de qualquer imagem fotográfica','Uso obrigatório de fonte serifada'],0,['O art. 37, §1º veda elementos que caracterizem promoção pessoal na publicidade pública.','Fotografia não é obrigatória para toda peça.','Não há essa obrigação tipográfica no princípio.'],'public'),
 T('Os cinco princípios expressos','Legalidade, impessoalidade, moralidade, publicidade e eficiência estão no art. 37, caput. O desafio é reconhecer sua aplicação no caso, e não apenas recitar as iniciais.'),
 Q('Uma equipe publica informação para o cidadão, mas acrescenta elogios pessoais ao gestor. A finalidade informativa elimina o problema?',['Não; a promoção pessoal ainda precisa ser avaliada','Sim; basta existir uma informação útil','Sim; publicidade significa divulgar qualquer mensagem'],0,['O caráter informativo não autoriza elementos de promoção pessoal.','Uma parte útil não legitima automaticamente o restante.','Publicidade é um princípio submetido à finalidade pública e aos limites constitucionais.']),
 T('Eficiência tem limites','Buscar melhor resultado com recursos adequados não permite ignorar legalidade, direitos ou os outros princípios. Eles devem ser considerados em conjunto.'),
 Q('“Foi mais rápido” basta para justificar uma atuação contrária à lei?',['Não; eficiência não afasta legalidade','Sim; rapidez sempre prevalece','Sim; desde que a peça fique bonita'],0,['Os princípios convivem; eficiência não autoriza descumprimento da lei.','Rapidez não é uma autorização ilimitada.','Qualidade visual não substitui conformidade jurídica.'])
],'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm');
P('direito:16','Distinguir ente federativo, órgão e capital.','Autonomia é dos entes previstos na Constituição; uma secretaria é órgão, e Brasília é a capital.',[
 T('Não misture categorias','União, Estados, Distrito Federal e Municípios compõem a organização político-administrativa, todos autônomos nos termos constitucionais. Uma secretaria faz parte da estrutura de um ente.','federation'),
 Q('Uma secretaria municipal é…',['um órgão do Município','um novo ente federativo soberano','a capital federal'],0,['Ela integra a estrutura administrativa; não se torna um ente autônomo adicional.','Órgãos não são entes federativos soberanos.','Brasília é a capital federal.'],'federation'),
 T('Autonomia não é soberania','A República Federativa do Brasil é soberana. Os entes exercem autonomia nos limites da Constituição. Isso não significa independência internacional de cada Município.'),
 Q('Segundo o art. 18, Territórios Federais…',['integram a União','são um quinto tipo de ente autônomo','são sempre partes do Distrito Federal'],0,['É a regra do §2º do art. 18.','Eles não constam como um quinto tipo de ente autônomo no caput.','Não há essa vinculação obrigatória ao DF.']),
 T('Olhe também as vedações','O art. 19 traz limites, entre eles recusar fé a documentos públicos e criar distinções entre brasileiros ou preferências entre si. Leia a redação completa para as hipóteses e ressalvas.'),
 Q('Brasília e Distrito Federal são termos juridicamente equivalentes?',['Não; Brasília é a capital e DF é ente federativo','Sim; ambos são municípios','Sim; ambos são territórios federais'],0,['As categorias constitucionais são distintas.','O DF não é classificado como município.','Nenhum dos dois é descrito assim pelo art. 18.'])
],'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm');
P('municipio:3','Associar cada data ao acontecimento correto.','Criação do distrito, criação legal do Município e instalação são marcos diferentes.',[
 T('Dê um significado a cada data','1953 marca a criação do distrito. A lei estadual de janeiro de 1988 elevou Senador Canedo à categoria de município. A instalação aconteceu em junho de 1989.','timeline'),
 Q('Qual acontecimento corresponde a 1989?',['Instalação do município','Criação do distrito','Lei estadual de janeiro que elevou à categoria de município'],0,['A instalação ocorreu em 01/06/1989, segundo o histórico do IBGE.','A criação do distrito pertence a 31/03/1953.','A Lei Estadual 10.435 é de 09/01/1988.'],'timeline'),
 T('A cronologia tem contexto','O IBGE registra também suspensão da execução da lei por medida cautelar em 15/07/1988. Por isso, não trate todos os acontecimentos como uma única “fundação”.'),
 Q('Por que “criação legal” e “instalação” não devem ser trocadas?',['São etapas distintas e ocorreram em datas diferentes','Porque 1988 não aparece no histórico','Porque o distrito já era um município independente'],0,['A questão pode cobrar a relação entre marco e data, não apenas um ano isolado.','1988 aparece como ano da lei e de sua suspensão registrada.','O distrito era subordinado a Goiânia.']),
 T('Use uma âncora curta','Distrito: 1953. Lei de criação: 1988. Instalação: 1989. Depois recupere dia, mês e contexto de cada etapa no texto oficial.'),
 Q('Em 1953, o distrito de Senador Canedo era subordinado a…',['Goiânia','Brasília','Anápolis'],0,['O histórico do IBGE registra a subordinação a Goiânia.','Brasília não é a relação descrita no histórico.','Anápolis não é a relação descrita.'])
],'https://www.ibge.gov.br/biblioteca/visualizacao/dtb/goias/senadorcanedo.pdf');
window.CQGuideContent=packs;
})();
