(function(){
'use strict';
const step=(prompt,answer,explanation,visual='')=>({prompt,answer,explanation,visual});
const table=(heads,rows)=>'<div class="lab-table-wrap"><table class="table"><thead><tr>'+heads.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const triangle='<svg viewBox="0 0 520 300" role="img" aria-label="Triângulo retângulo com ângulo theta na base esquerda, cateto oposto 3, adjacente 4 e hipotenusa 5"><path d="M70 240 L430 240 L430 40 Z" fill="#eff6ff" stroke="#334155" stroke-width="3"/><path d="M407 240 V217 H430" fill="none" stroke="#334155" stroke-width="2"/><g fill="#1f2937" font-size="20"><text x="96" y="231">θ</text><text x="230" y="275">adjacente: 4</text><text x="435" y="140">3</text><text x="205" y="120">hipotenusa: 5</text></g></svg>';
const timeline=table(['Marco','Data','O que muda'],[['Distrito','31/03/1953','Subordinação a Goiânia'],['Criação legal do município','09/01/1988','Lei Estadual 10.435'],['Instalação','01/06/1989','Instalação efetiva']]);
const labs={
 'pt:5':{title:'Crase: teste duas condições',visual:table(['Construção','Regência exige a?','Termo admite artigo a?','Conclusão'],[['Fui ___ Câmara','Sim: ir a','Sim: a Câmara','a + a = à'],['Começou ___ estudar','Há a','Infinitivo não recebe artigo','a, sem crase'],['Entreguei ___ ela','Sim: entregar a','Pronome ela não recebe artigo','a, sem crase']]),steps:[step('Em “Fui ___ Câmara”, complete a lacuna.','à','O verbo exige preposição a e Câmara admite artigo a. O teste masculino compatível é “fui ao plenário”.'),step('Em “Começou ___ estudar”, complete a lacuna.','a','Estudar é infinitivo: não há artigo feminino para fundir com a preposição. Ser palavra próxima de a não basta.') ]},
 'pt:14':{title:'Conte sons, não apenas letras',visual:table(['Palavra','Letras','Fonemas','Análise'],[['chave','5','4','ch representa um som'],['guerra','6','4','gu e rr: dois dígrafos'],['prato','5','5','pr preserva dois sons']]),steps:[step('Quantos fonemas há em “chave”?','4','C+h representam um fonema. a, v e e representam os outros três.'),step('Separe “saúde” em sílabas; use hífens.','sa-ú-de','a e ú pertencem a sílabas diferentes: há hiato. O acento não cria o hiato; a estrutura sonora o caracteriza.')]},
 'pt:15':{title:'A forma depende da oração',visual:table(['Frase','Modo/forma','Relação'],[['Quando chegar, avisarei','Futuro do subjuntivo','Situação futura'],['Quero chegar cedo','Infinitivo','Complementa quero'],['Se estudasse, conseguiria','Imperfeito do subjuntivo','Hipótese']]),steps:[step('Na expressão “Se estudasse”, qual é o modo de estudasse?','subjuntivo','O tempo é pretérito imperfeito do subjuntivo; a oração coloca uma hipótese, não um fato passado concluído.') ]},
 'info:1':{title:'Execute uma instrução por vez',visual:table(['Etapa','Instrução','Valor antes','Valor depois'],[['1','x ← 2','—','2'],['2','x ← x × 3','2','6'],['3','x ← x + 4','6','?']]),steps:[step('Após a terceira instrução, qual é o valor de x?','10','O valor anterior é 6. A atribuição substitui x por 6+4, não volta ao valor inicial 2.'),step('Agora x=2; enquanto x<6, some 2. Qual é o valor ao sair?','6','2<6: vira 4. 4<6: vira 6. 6<6 é falso: encerra. Não execute uma volta depois da condição falsa.')]},
 'info:7':{title:'Copie fórmulas com intenção',visual:table(['Referência','Coluna ao copiar','Linha ao copiar'],[['B2','Varia','Varia'],['$B$2','Fixa','Fixa'],['$B2','Fixa','Varia'],['B$2','Varia','Fixa']]),steps:[step('Ao copiar =A1*B1 uma linha abaixo, qual fórmula resulta?','=A2*B2','Ambas são relativas: avançam uma linha. O cifrão fixa a parte imediatamente seguinte.'),step('Ao copiar =$B$2 uma linha abaixo, qual fórmula resulta?','=$B$2','Coluna e linha estão fixadas. Isso não bloqueia edição do valor da célula B2.') ]},
 'math:3':{title:'Percentuais sucessivos mudam a base',visual:table(['Etapa','Base','Fator','Valor'],[['Inicial','100','—','100'],['Aumento 20%','100','1,20','120'],['Desconto 20%','120','0,80','?']]),steps:[step('Quanto resta depois de aumentar 100 em 20% e descontar 20% do novo valor?','96','120×0,80=96. O desconto é 24, porque a base agora é 120; não é 20.'),step('O resultado ficou quantos por cento menor que o inicial?','4','A diferença é 100−96=4. Dividindo pela base inicial 100, temos 4%. Operações opostas com bases diferentes não se anulam.')]},
 'math:11':{title:'Cargos diferentes alteram a contagem',visual:table(['Seleção de 2 entre 5','Ordem importa?','Contagem'],[['Presidente e secretário','Sim: Ana/Beto ≠ Beto/Ana','5 × 4 = 20'],['Dois membros sem cargos','Não: Ana/Beto = Beto/Ana','20 ÷ 2! = 10']]),steps:[step('Quantas duplas sem cargos diferentes podem ser escolhidas entre cinco pessoas?','10','A lista ordenada tem 20 pares. Cada dupla aparece em duas ordens; divida por 2!.'),step('Se os cargos forem presidente e secretário, quantas seleções existem?','20','Agora trocar as pessoas de cargo muda a seleção; não divida por 2!.')]},
 'math:15':{title:'Separe a região comum',visual:table(['Só A','A e B','Só B'],[['1, 2','3','4']]),steps:[step('Para A={1,2,3}, B={3,4}, digite A∩B.','{3}','Interseção inclui o que está nos dois. 1 e 2 pertencem apenas a A; 4 apenas a B.'),step('18 usam A, 12 usam B e 5 usam ambas. Quantos usam ao menos uma?','25','Na soma 18+12 a região comum foi contada duas vezes. Subtraia 5 uma vez: 25.')]},
 'math:16':{title:'Marque o ângulo antes da razão',visual:triangle+table(['Razão em θ','Fórmula','Neste desenho'],[['sen θ','oposto / hipotenusa','3/5'],['cos θ','adjacente / hipotenusa','4/5'],['tan θ','oposto / adjacente','3/4']]),steps:[step('Quanto vale sen θ no desenho? Responda como fração.','3/5','Oposto=3, hipotenusa=5. A orientação do desenho não muda a relação.'),step('Escada de 10 m a 30° do chão, sen30°=1/2. Qual a altura em metros?','5','A escada é a hipotenusa, e a altura é o lado oposto: altura/10=1/2.') ]},
 'direito:2':{title:'Ilegalidade ou mudança de conveniência?',visual:table(['Situação','Controle','Motivo'],[['Ato inválido','Anulação','Ilegalidade'],['Ato válido, retirada admitida','Revogação','Conveniência/oportunidade'],['Vício sanável, requisitos atendidos','Convalidação','Saneamento']]),steps:[step('Um ato válido deixou de ser conveniente; sua retirada por mérito é admitida. Qual instrumento?','revogação','O enunciado afirma validade e mérito: revogação. Se o problema fosse ilegalidade, a categoria seria anulação.'),step('O ato foi praticado contra a lei e deve ser retirado. Qual instrumento?','anulação','Anulação lida com ilegalidade. O Judiciário pode controlar legalidade; não substitui simplesmente o mérito administrativo por sua própria preferência.')]},
 'direito:16':{title:'Entes, capital e órgãos são categorias diferentes',visual:table(['Categoria','Exemplo','Característica'],[['Ente autônomo','Município','Integra organização federativa'],['Capital Federal','Brasília','Capital, não ente adicional'],['Órgão municipal','Secretaria','Centro de competências'],['Território Federal','Se criado conforme norma','Integra a União']]),steps:[step('Qual ente os Territórios Federais integram?','união','Art. 18, §2º. Não são um quinto tipo de ente autônomo.'),step('A República Federativa do Brasil é soberana; os entes são o quê?','autônomos','Autonomia ocorre nos limites da Constituição. Municípios não possuem soberania internacional.')]},
 'municipio:3':{title:'Criação legal e instalação são eventos distintos',visual:timeline,steps:[step('Em qual ano foi criado o distrito subordinado a Goiânia?','1953','O marco é 31/03/1953; antecede a elevação à categoria de município.'),step('Em qual ano o município foi instalado?','1989','Instalação: 01/06/1989. A criação legal pertence a 1988; não troque os dois marcos.') ]},
 'design:31':{title:'Escolha pelo trabalho a executar',visual:table(['Material','Tipo de trabalho','Ferramentas principais'],[['Fotografia','Raster','Photoshop / GIMP'],['Símbolo escalável','Vetor','Illustrator / CorelDRAW / Inkscape'],['Cartilha multipágina','Editoração','InDesign / Scribus']]),steps:[step('Qual software livre da tabela é voltado à diagramação de uma cartilha multipágina?','scribus','Scribus é editoração. Inkscape prioriza vetor; GIMP prioriza raster. A diferença é a finalidade principal.'),step('1800 pixels a 300 ppi permitem quantas polegadas de largura sem interpolação?','6','Divida 1800 por 300: 6 polegadas. Salvar em outra extensão não cria detalhe.') ]},
 'design:32':{title:'Compare a evidência sem distorcer',visual:table(['Escolha','Impacto'],[['Título informa a conclusão','Orienta a leitura'],['Barra começa em zero','Permite comparar comprimentos proporcionalmente'],['Fonte e período visíveis','Permitem verificar o dado'],['Texto inteiro comprimido no slide','Aumenta esforço de leitura']]),steps:[step('De 100 para 110, qual é o aumento percentual?','10','(110−100)/100×100=10%. Uma escala que faça essa diferença parecer enorme distorce a percepção.') ]}
};
const normalize=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s/g,'').replace(/,/g,'.');
window.labCheck=function(key,index){
 const st=labs[key]?.steps[index],input=document.getElementById(`lab-${index}`),feedback=document.getElementById(`lab-feedback-${index}`);
 if(!st||!input||!feedback)return;
 const raw=input.value.trim();if(!raw){feedback.textContent='Tente responder antes de conferir.';return;}
 const ok=normalize(raw)===normalize(st.answer);
 state.labAttempts=state.labAttempts||{};state.labAttempts[`${key}:${index}`]={answer:raw,correct:ok,ts:Date.now()};save();touchStudy();
 feedback.textContent=(ok?'Correto. ':'Confira: '+st.answer+'. ')+st.explanation;
 feedback.className='lab-feedback '+(ok?'good':'bad');
};
function colors(){return '<section class="learning-lab"><div class="eyebrow">EXPERIMENTO</div><h2>RGB: acenda as três luzes</h2><p>O quadro calcula os canais de um pixel. Coloque R e G em 255 e B em 0: surge amarelo. Com os três em 255, surge branco; com os três em zero, preto.</p><div class="color-lab-grid"><div>'+['R','G','B'].map((v,i)=>'<label for="rgb-'+v+'">'+v+' <output id="rgb-value-'+v+'">'+(i===0?255:0)+'</output></label><input id="rgb-'+v+'" type="range" min="0" max="255" value="'+(i===0?255:0)+'" oninput="updateColorLab()">').join('')+'</div><div id="rgb-swatch" class="rgb-swatch" role="img" aria-label="Resultado RGB"><span id="rgb-result"></span></div></div>'+table(['Mistura ideal','RGB: soma luz','CMY: filtra luz'],[['Dois canais','R+G = amarelo','C+M = azul'],['Outros pares','G+B = ciano; B+R = magenta','M+Y = vermelho; Y+C = verde'],['Três canais no máximo','Branco','Preto ideal; processo real usa K'],['Nenhum canal/tinta','Preto: sem luz','Branco do papel']])+'<p class="small">Comparação conceitual. Tintas e perfis reais dependem do processo e não são simulados pelo monitor.</p></section>';}
window.updateColorLab=function(){const vals=['R','G','B'].map(v=>{const x=Number(document.getElementById('rgb-'+v).value);document.getElementById('rgb-value-'+v).value=x;return x});const sw=document.getElementById('rgb-swatch');sw.style.background=`rgb(${vals.join(',')})`;sw.setAttribute('aria-label',`Resultado RGB ${vals.join(', ')}`);const result=document.getElementById('rgb-result');result.textContent=`RGB(${vals.join(', ')})`;};
function harmonies(){return '<section class="learning-lab"><h2>Relações angulares no círculo RGB/HSV</h2><div class="harmony-grid"><div class="hue-wheel" role="img" aria-label="Círculo de matizes RGB HSV: vermelho no topo e ciano no lado oposto"><span class="hue-label hue-red">Vermelho · 0°</span><span class="hue-label hue-cyan">Ciano · 180°</span></div>'+table(['Relação','Ângulos de exemplo','O que observar'],[['Análoga','0°, 30°, 60°','Setores próximos'],['Complementar','0° e 180°','Posições opostas'],['Triádica','0°, 120°, 240°','Três intervalos iguais']])+'</div><p>O círculo artístico RYB tem outras relações tradicionais. Sempre identifique o modelo. Harmonia não comprova contraste suficiente para texto.</p></section>';}
const oldLesson=window.lesson;
window.lesson=function(s,i){
 oldLesson(s,i);const key=`${s}:${i}`,body=document.querySelector('.lesson-body');if(!body)return;
 if(s==='design'&&i===8){document.querySelector('.lesson-visual-card')?.remove();body.insertAdjacentHTML('afterend',colors());updateColorLab();}
 else if(s==='design'&&i===9){document.querySelector('.lesson-visual-card')?.remove();body.insertAdjacentHTML('afterend',harmonies());}
 const lab=labs[key];if(lab){
 const html='<section class="learning-lab"><div class="eyebrow">APLIQUE EM ETAPAS</div><h2>'+esc(lab.title)+'</h2>'+lab.visual+'<p>Observe o exemplo. Depois cubra a tabela e tente responder. O sistema compara respostas curtas; use a explicação para avaliar o raciocínio.</p>'+lab.steps.map((st,j)=>'<article class="lab-step"><label for="lab-'+j+'">'+esc(st.prompt)+'</label><div class="toolbar"><input class="lab-input" id="lab-'+j+'" autocomplete="off" value="'+esc(state.labAttempts?.[`${key}:${j}`]?.answer||'')+'"><button class="btn" onclick="labCheck(\''+key+'\','+j+')">Conferir raciocínio</button></div><p id="lab-feedback-'+j+'" class="lab-feedback" role="status"></p><details><summary>Ver solução comentada</summary><p>'+esc(st.answer)+' · '+esc(st.explanation)+'</p></details></article>').join('')+'</section>';
 body.insertAdjacentHTML('afterend',html);
 }
 if(LESSONS[s][i].source)body.insertAdjacentHTML('afterend','<p class="lesson-source">Fonte para esta aula: <a target="_blank" rel="noopener" href="'+esc(LESSONS[s][i].source)+'">texto oficial</a></p>');
 // Every lesson gets a concrete retrieval attempt and an explicit self-evaluation, not automatic grading of prose.
 const activity=REVIEW_ACTIVITIES.find(a=>a.s===s&&a.m===i&&a.kind==='aplicar');
 if(activity){const box=document.createElement('section');box.className='learning-lab';box.innerHTML='<div class="eyebrow">RECUPERE E COMPARE</div><h2>Explique o mecanismo sem consultar</h2><label for="transfer-recall">'+esc(activity.prompt)+'</label><textarea id="transfer-recall" class="note-box" oninput="saveReviewAttempt(\''+activity.uid+'\',this.value)">'+esc(state.reviewAttempts[activity.uid]?.text||'')+'</textarea><details><summary>Comparar com o exemplo e critérios</summary><p>'+esc(activity.answer)+'</p><ul><li>Identifiquei a regra que decide o caso?</li><li>Mostrei como a regra se aplica ao exemplo?</li><li>Expliquei por que uma alternativa parecida não se aplica?</li></ul><p>Esta é uma autoavaliação. O texto digitado não recebe correção automática.</p></details>';body.parentNode.insertBefore(box,document.querySelector('.lesson-actions'));}
 document.querySelectorAll('textarea').forEach((el,j)=>{if(!el.hasAttribute('aria-label')&&!document.querySelector('label[for="'+el.id+'"]'))el.setAttribute('aria-label','Resposta de estudo '+(j+1));});
};
})();
