(function(){
'use strict';
var timer=null,feedbackTimer=null,run=null,RKEY='rapid';
function R(){if(!state[RKEY])state[RKEY]={seen:[],mistakes:[],history:[],total:0,correct:0,bestScore:0,bestCombo:0,topic:{}};var r=state[RKEY];r.seen=Array.isArray(r.seen)?r.seen:[];r.mistakes=Array.isArray(r.mistakes)?r.mistakes:[];r.history=Array.isArray(r.history)?r.history:[];r.topic=r.topic||{};return r}
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function pk(a){return a[Math.floor(Math.random()*a.length)]}
function sh(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=x[i];x[i]=x[j];x[j]=t}return x}
function norm(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function esc(s){return String(s||'').replace(/[&<>'"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]})}
function optionKey(v){var n=norm(v),m=n.match(/^(-?\d+(?:[.,]\d+)?)\/(-?\d+(?:[.,]\d+)?)$/);if(m&&Number(m[2])!==0)return 'number|'+(Number(m[1].replace(',','.'))/Number(m[2].replace(',','.'))).toFixed(10);if(/^-?\d+([.,]\d+)?$/.test(n))return 'number|'+Number(n.replace(',','.')).toFixed(10);return n}
function qmk(x){var opts=[x.answer].concat(x.wrong||[]),seen={},clean=[];opts.forEach(function(v){var n=optionKey(v);if(!seen[n]){seen[n]=1;clean.push(v)}});if(clean.length!==4)return null;var oo=sh(clean);return{uid:'rapid-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),sig:x.sig,s:x.s,t:x.t,d:x.d||'easy',difficulty_label:x.d==='expert'?'DESAFIO':x.d==='hard'?'DIFÍCIL':x.d==='medium'?'MÉDIO':'FÁCIL',q:x.q,o:oo,a:oo.findIndex(function(v){return optionKey(v)===optionKey(x.answer)}),e:x.e||'',extra:x.extra||'',visual:x.visual||'',rapid:true}}

var F=[];
function add(f){F.push(f)}
add(function(){var n=ri(50,950),p=pk([5,10,15,20,25,30,40]),v=n*p/100;return{s:'math',t:'Porcentagem',d:p>=25?'medium':'easy',sig:'gen|pct|'+n+'-'+p,q:'Quanto é '+p+'% de '+n+'?',answer:String(v),wrong:[String(v+n/10),String(v-p),String(n+p)],e:'Calcule '+n+' × '+p+'/100 = '+v+'.'}})
add(function(){var c=ri(200,2000),i=pk([2,3,4,5]),t=pk([2,3,4,6]),j=c*i*t/100;return{s:'math',t:'Juros simples',d:'medium',sig:'gen|js|'+c+'-'+i+'-'+t,q:'Capital de R$ '+c+', taxa de '+i+'% ao período e '+t+' períodos. Qual é o juro simples?',answer:'R$ '+j,wrong:['R$ '+(j+c),'R$ '+(c*i/100),'R$ '+Math.round(c*((1+i/100)**t-1))],e:'J = C·i·t. Então '+c+' × '+i+'/100 × '+t+' = '+j+'.'}})
add(function(){var a=ri(2,8),b=ri(4,12),c,k,s;do{c=ri(6,16);s=a+b+c}while(s%3);return{s:'math',t:'Estatística',d:'easy',sig:'gen|mean|'+a+'-'+b+'-'+c,q:'A média de '+a+', '+b+' e '+c+' é:',answer:String(s/3),wrong:[String(s/3+1),String(s),String(Math.floor((b+c)/2))],e:'Some os valores e divida por 3: '+s+'/3 = '+(s/3)+'.'}})
add(function(){var a=ri(2,10),unit=ri(2,10),b=a*unit,c=ri(2,12);if(c===a)c=a===12?2:a+1;var x=unit*c;return{s:'math',t:'Regra de três',d:'medium',sig:'gen|r3|'+a+'-'+unit+'-'+c,q:'Se '+a+' unidades custam R$ '+b+', quanto custam '+c+' unidades, mantendo a proporção?',answer:'R$ '+x,wrong:['R$ '+(b+c),'R$ '+(x+a),'R$ '+(unit*a/c).toFixed(2)],e:'É uma proporção direta. O custo por unidade é R$ '+unit+', então '+c+' × '+unit+' = R$ '+x+'.'}})
add(function(){var a=ri(1,15),r=pk([2,3,4,5]),n=pk([4,5,6,7]),x=a+(n-1)*r;return{s:'math',t:'PA e PG',d:'medium',sig:'gen|pa|'+a+'-'+r+'-'+n,q:'Em uma PA com primeiro termo '+a+' e razão '+r+', o '+n+'º termo é:',answer:String(x),wrong:[String(a+n*r),String(a*r*n),String(a+(n+1)*r)],e:'aₙ = a₁ + (n−1)r = '+x+'.'}})
add(function(){var w=ri(3,18),h=ri(2,15);return{s:'math',t:'Geometria plana',d:'easy',sig:'gen|area|'+w+'-'+h,q:'Um retângulo mede '+w+' cm por '+h+' cm. Qual é sua área?',answer:w*h+' cm²',wrong:[2*(w+h)+' cm²',(w+h)+' cm²',w*h*2+' cm²'],e:'Área = base × altura = '+w+' × '+h+' = '+w*h+' cm².'}})
add(function(){var t=ri(4,12),f=ri(1,t-1);return{s:'math',t:'Probabilidade',d:'medium',sig:'gen|prob|'+t+'-'+f,q:'Um evento tem '+f+' casos favoráveis em '+t+' casos equiprováveis. A probabilidade é:',answer:f+'/'+t,wrong:[(t-f)+'/'+t,(f+1)+'/'+t,f+'/'+(t+1)],e:'P = casos favoráveis/casos possíveis = '+f+'/'+t+'.'}})

add(function(){var n=ri(10,99);return{s:'info',t:'Segurança da informação',d:'easy',sig:'gen|cia|'+n,q:'Em um sistema que impede acesso de pessoas não autorizadas, qual propriedade da tríade CIA está sendo protegida? (Exemplo '+n+')',answer:'Confidencialidade',wrong:['Integridade','Disponibilidade','Redundância'],e:'Confidencialidade trata do acesso autorizado; integridade, de alterações indevidas; disponibilidade, do acesso quando necessário.'}})
add(function(){var n=ri(10,99);return{s:'info',t:'Ambiente corporativo',d:'easy',sig:'gen|auth|'+n,q:'No procedimento '+n+', o sistema verifica se a pessoa é realmente quem afirma ser. Isso é:',answer:'Autenticação',wrong:['Autorização','Auditoria','Compartilhamento'],e:'Autenticação responde quem é você. Autorização responde o que você pode fazer.'}})
add(function(){var n=ri(10,99);return{s:'info',t:'Redes e Internet',d:'medium',sig:'gen|dns|'+n,q:'Qual serviço traduz nomes de domínio em endereços IP? Cenário '+n+'.',answer:'DNS',wrong:['DHCP','SMTP','FTP'],e:'DNS resolve nomes. DHCP distribui configurações; SMTP é usado no envio de e-mail.'}})
add(function(){var x=pk(['IaaS','PaaS','SaaS']),n=ri(10,99),d=x==='IaaS'?'infraestrutura':x==='PaaS'?'plataforma para desenvolvimento e execução':'software pronto como serviço';return{s:'info',t:'Cloud computing',d:'easy',sig:'gen|cloud|'+x+'-'+n,q:'No cenário '+n+', qual modelo corresponde a '+d+'?',answer:x,wrong:['DNS','IMAP',x==='IaaS'?'SaaS':x==='PaaS'?'IaaS':'PaaS'],e:'IaaS = infraestrutura; PaaS = plataforma; SaaS = software como serviço.'}})
add(function(){var n=ri(10,99);return{s:'info',t:'Backup e recuperação',d:'medium',sig:'gen|backup|'+n,q:'Em um procedimento de segurança nº '+n+', qual ação é essencial para validar se um backup funciona?',answer:'Fazer um teste de restauração',wrong:['Apenas copiar os arquivos','Renomear a pasta','Deixar a cópia no mesmo volume'],e:'Backup confiável precisa ser recuperável. Testes de restauração revelam falhas e inconsistências.'}})
add(function(){var n=ri(10,99);return{s:'info',t:'Navegadores e pesquisa',d:'easy',sig:'gen|cache|'+n,q:'No exemplo '+n+', uma cópia temporária de recursos para acelerar o carregamento é chamada de:',answer:'Cache',wrong:['Cookie','DNS','Firewall'],e:'Cache é armazenamento temporário. Cookie é outro mecanismo, usado para dados de sessão/preferências.'}})
add(function(){var n=ri(10,99);return{s:'info',t:'Malware e defesa',d:'medium',sig:'gen|phish|'+n,q:'No cenário '+n+', uma mensagem falsa tenta induzir a vítima a clicar em um link para roubar credenciais. Isso é:',answer:'Phishing',wrong:['Backup','Firewall','Compressão'],e:'Phishing usa engenharia social para induzir a vítima a fornecer dados ou executar uma ação maliciosa.'}})

add(function(){var x=pk([['legalidade','agir dentro da lei'],['impessoalidade','evitar favorecimento pessoal'],['publicidade','dar transparência aos atos'],['eficiência','buscar melhor desempenho administrativo']]),n=ri(10,99);return{s:'direito',t:'Princípios da Administração Pública',d:'easy',sig:'gen|limpe|'+x[0]+'-'+n,q:'Em uma situação administrativa nº '+n+', qual princípio corresponde a '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:['Moralidade','Hierarquia','Soberania'],e:'Legalidade, impessoalidade, moralidade, publicidade e eficiência são princípios expressos no art. 37.'}})
add(function(){var x=pk([['hierárquico','organização e distribuição interna de competências',['disciplinar','poder de polícia','constituinte']],['disciplinar','apuração e sanção de infrações funcionais',['hierárquico','poder de polícia','constituinte']],['poder de polícia','limitação administrativa em favor do interesse coletivo',['hierárquico','disciplinar','constituinte']]]),n=ri(10,99);return{s:'direito',t:'Poderes administrativos',d:'medium',sig:'gen|poder|'+x[0]+'-'+n,q:'No cenário administrativo '+n+', qual poder está associado a '+x[1]+'?',answer:x[0].replace(/^./,function(m){return m.toUpperCase()}),wrong:x[2],e:'Os poderes administrativos têm finalidades diferentes; a prova costuma trocar suas características.'}})
add(function(){var x=pk([['anulação','ilegalidade'],['revogação','mérito, por conveniência e oportunidade']]),n=ri(10,99);return{s:'direito',t:'Atos administrativos',d:'hard',sig:'gen|ato|'+x[0]+'-'+n,q:'Em um caso administrativo nº '+n+', qual providência se relaciona principalmente a '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:[x[0]==='anulação'?'Revogação':'Anulação','Convalidação','Delegação'],e:x[0]==='anulação'?'Anulação se relaciona à ilegalidade.':'Revogação se relaciona, em regra, a mérito: conveniência e oportunidade.'}})
add(function(){var x=pk([['Pregão','bens e serviços comuns'],['Concurso','trabalho técnico, científico ou artístico'],['Leilão','alienação de bens nas hipóteses legais']]),n=ri(10,99);return{s:'direito',t:'Licitações — modalidades',d:'medium',sig:'gen|lic|'+x[0]+'-'+n,q:'Na situação de contratação '+n+', qual modalidade está associada a '+x[1]+'?',answer:x[0],wrong:['Concorrência','Diálogo competitivo','Inexigibilidade'],e:'Modalidade e hipótese legal são conceitos diferentes; a banca pode misturá-los.'}})
add(function(){var n=ri(10,99);return{s:'direito',t:'Contratação direta',d:'hard',sig:'gen|direct|'+n,q:'Na hipótese '+n+', qual contratação direta pressupõe inviabilidade de competição?',answer:'Inexigibilidade',wrong:['Dispensa','Pregão','Concurso'],e:'Inexigibilidade envolve inviabilidade de competição. Dispensa é hipótese distinta.'}})

add(function(){var x=pk([['proximidade','elementos próximos são percebidos como relacionados'],['semelhança','elementos semelhantes tendem a ser agrupados'],['fechamento','a mente completa formas incompletas'],['figura e fundo','diferenciação entre figura focal e plano de fundo']]),n=ri(10,99);return{s:'design',t:'Gestalt',d:'medium',sig:'gen|gestalt|'+x[0]+'-'+n,q:'No estudo visual '+n+', qual princípio corresponde a '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:['Kerning','CMYK','Sangria'],e:'A Gestalt descreve como percebemos e organizamos relações entre elementos visuais.'}})
add(function(){var x=pk(['RGB','CMYK']),n=ri(10,99);return{s:'design',t:'Cor — modelos',d:'easy',sig:'gen|rgbcmyk|'+x+'-'+n,q:'No arquivo '+n+', qual modelo está mais diretamente associado a '+(x==='RGB'?'luz e telas':'tintas e impressão')+'?',answer:x,wrong:[x==='RGB'?'CMYK':'RGB','Pantone','Grayscale'],e:'RGB é aditivo e ligado a telas/luz; CMYK é associado à reprodução por tintas.'}})
add(function(){var x=pk([['kerning','ajuste entre pares específicos de letras'],['tracking','ajuste do espaçamento de um conjunto de caracteres'],['entrelinha','espaçamento vertical entre linhas']]),n=ri(10,99);return{s:'design',t:'Tipografia',d:'medium',sig:'gen|type|'+x[0]+'-'+n,q:'Na composição tipográfica '+n+', qual termo descreve '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:['Grid','Sangria','CMYK'],e:'Kerning atua em pares; tracking no conjunto; entrelinha no espaçamento vertical.'}})
add(function(){var x=pk(['contraste','escala','posição','peso tipográfico']),n=ri(10,99);return{s:'design',t:'Hierarquia e composição',d:'medium',sig:'gen|hier|'+x+'-'+n,q:'Em uma peça identificada como '+n+', qual recurso pode ser usado diretamente para criar hierarquia visual?',answer:x,wrong:['Tornar todos os elementos idênticos','Eliminar o alinhamento','Usar sempre a mesma escala'],e:'Hierarquia depende de diferenciação perceptual. Contraste, escala, posição e peso são recursos comuns.'}})
add(function(){var x=pk([['sangria','ultrapassa a linha de corte'],['margem segura','mantém conteúdo importante afastado do corte']]),n=ri(10,99);return{s:'design',t:'Fechamento de arquivo',d:'medium',sig:'gen|print|'+x[0]+'-'+n,q:'No fechamento do arquivo '+n+', qual conceito corresponde a '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:['Kerning','Tracking','Wireframe'],e:'Sangria passa além do corte. Margem segura protege conteúdo importante perto da borda.'}})
add(function(){var a=[['Perceptível','conteúdo pode ser percebido'],['Operável','controles podem ser utilizados'],['Compreensível','informação é entendível e previsível'],['Robusto','funciona com tecnologias de acesso']],x=pk(a),n=ri(10,99);return{s:'design',t:'WCAG',d:'hard',sig:'gen|wcag|'+x[0]+'-'+n,q:'Na revisão de acessibilidade '+n+', qual princípio da WCAG corresponde a '+x[1]+'?',answer:x[0],wrong:a.filter(function(v){return v[0]!==x[0]}).map(function(v){return v[0]}),e:'Os quatro princípios WCAG são Perceptível, Operável, Compreensível e Robusto.'}})
add(function(){var x=pk([['feedback','indica o resultado de uma ação'],['consistência','padrões semelhantes se comportam de modo semelhante'],['affordance','sugere como um elemento pode ser usado']]),n=ri(10,99);return{s:'design',t:'UX/UI',d:'medium',sig:'gen|ux|'+x[0]+'-'+n,q:'Em uma interface pública de referência '+n+', qual conceito corresponde a '+x[1]+'?',answer:x[0],wrong:['CMYK','Sangria','Backup'],e:'UX/UI cobra comportamento e uso da interface, não só sua aparência.'}})
add(function(){var x=pk([['área de proteção','espaço mínimo ao redor da marca'],['manual de identidade','regras para uso consistente da marca']]),n=ri(10,99);return{s:'design',t:'Identidade visual',d:'medium',sig:'gen|identity|'+x[0]+'-'+n,q:'No manual de identidade '+n+', qual item corresponde a '+x[1]+'?',answer:x[0].charAt(0).toUpperCase()+x[0].slice(1),wrong:['Wireframe','Backup','Entrelinha'],e:'Identidade visual depende de regras de aplicação e consistência.'}})

add(function(){var x=pk([['1953','criação do distrito'],['1988','emancipação política'],['1989','instalação do município']]);return{s:'municipio',t:'História de Senador Canedo',d:'easy',sig:'gen|munhist|'+x[0],q:'Qual marco está associado ao ano de '+x[0]+' no histórico de Senador Canedo?',answer:x[1],wrong:['fundação de Goiânia','criação da Câmara dos Deputados','instalação do Governo do Estado'],e:'Estude datas junto do acontecimento, consultando o histórico oficial do IBGE e as fontes municipais.'}})
add(function(){var x=pk([['Esplanada','denominação histórica associada ao local'],['Câmara Municipal','Poder Legislativo municipal']]),n=ri(10,99);return{s:'municipio',t:'Conhecimentos locais',d:'medium',sig:'gen|munlocal|'+x[0]+'-'+n,q:'Na revisão local '+n+', qual associação é correta para '+x[0]+'?',answer:x[1],wrong:['órgão do Poder Judiciário federal','modalidade de licitação','modelo de cor'],e:'Questões rápidas podem cobrar relações diretas entre fatos, nomes e órgãos locais.'}})

add(function(){var x=pk([['lâmpada','proparoxítona; por isso é acentuada'],['café','oxítona terminada em “e”'],['herói','oxítona com ditongo aberto tônico'],['fácil','paroxítona terminada em “l”']]),n=ri(10,99);return{s:'pt',t:'Ortografia e acentuação',d:'easy',sig:'gen|ptaccent|'+x[0]+'-'+n,q:'Na revisão nº '+n+', por que “'+x[0]+'” recebe acento?',answer:x[1],wrong:['é sempre sem acento','é monossílabo átono','é uma palavra sem sílaba tônica'],e:'A regra depende da sílaba tônica e da classificação da palavra. A banca costuma cobrar a classificação junto da regra.'}})
add(function(){var x=pk([['à','preposição “a” + artigo “a”'],['a','preposição diante de verbo no infinitivo'],['à','preposição “a” + artigo “a”, em construção regida']]),n=ri(10,99),q=x[0]==='à'?'No exemplo '+n+', “Fui ___ Câmara”: qual forma completa a frase?':'No exemplo '+n+', “Começou ___ estudar”: qual forma completa a frase?';return{s:'pt',t:'Crase',d:x[0]==='à'?'medium':'easy',sig:'gen|ptcrase|'+n+'-'+x[0]+'-'+q, q:q,answer:x[0],wrong:[x[0]==='à'?'a':'à','há','às'],e:x[1]+'. Crase exige analisar regência e presença de artigo; não é simplesmente “palavra feminina”.'}})
add(function(){var x=pk([['vocativo','“Cristiano, revise a questão.”'],['aposto','“A Câmara, órgão legislativo, aprovou o texto.”'],['adjunto adverbial deslocado','“Após a reunião, a Câmara publicou o resumo.”']]),n=ri(10,99);return{s:'pt',t:'Pontuação',d:'medium',sig:'gen|ptpunct|'+x[0]+'-'+n,q:'Na frase '+x[1]+', a vírgula está associada a qual função?',answer:x[0],wrong:['objeto direto','sujeito','predicado'],e:'A justificativa da vírgula é sintática/semântica; decorar “pausa” não basta.'}})
add(function(){var x=pk([['assistir ao filme','regência com preposição a, no sentido de ver'],['preferir X a Y','regência tradicional com a no segundo termo'],['faltam documentos','concordância com o núcleo do sujeito']]),n=ri(10,99);return{s:'pt',t:'Regência e concordância',d:'medium',sig:'gen|ptreg|'+x[0]+'-'+n,q:'Na construção “'+x[0]+'”, qual explicação é correta?',answer:x[1],wrong:['preferir X do que Y como regra obrigatória','faltam documentos: verbo invariável','assistir ao filme: sem preposição'],e:x[1]+'. A norma-padrão cobra regência e concordância conforme a construção, não apenas a posição das palavras.'}})
add(function(){var x=pk([['não me disseram','a palavra negativa favorece próclise'],['dir-me-ão','mesóclise é possível com futuro, sem atrator'],['estudou-se','ênclise aparece em contexto compatível']]),n=ri(10,99);return{s:'pt',t:'Colocação pronominal',d:'medium',sig:'gen|ptpron|'+x[0]+'-'+n,q:'Na construção “'+x[0]+'”, qual explicação está correta?',answer:x[1],wrong:['a posição do pronome é sempre livre','próclise é obrigatória em qualquer oração','mesóclise ocorre antes de qualquer verbo'],e:'Negativas, subordinativas e outros fatores atraem o pronome; futuro sem atrator pode admitir mesóclise no padrão formal.'}})
function qgen(level,avoid){
 var rr=R();
 for(var i=0;i<240;i++){
  var x=pk(F)();if(avoid&&x.t===avoid)continue;
  if(level<=1&&(x.d==='hard'||x.d==='expert'))continue;
  if(level>=4&&x.d==='easy'&&Math.random()<.8)continue;
  // Scenario IDs do not create new concepts. Keep mathematical variables in signatures.
  if(x.s!=='math'&&!x.sig.startsWith('gen|munhist|'))x.sig=x.sig.replace(/-\d+$/,'');
  if(rr.seen.includes(x.sig))continue;
  var generated=qmk(x);if(!generated)continue;rr.seen.push(x.sig);rr.seen=rr.seen.slice(-2000);return generated;
 }
 var bank=QUESTIONS.filter(function(q){return !rr.seen.includes('bank|'+q.uid)&&(level>=4||q.d==='easy'||q.d==='medium')});
 if(!bank.length)bank=QUESTIONS.filter(q=>level>=4||q.d==='easy'||q.d==='medium');
 var b=pk(bank),result=qmk({s:b.s,t:b.t,d:b.d,sig:'bank|'+b.uid,q:b.q,answer:b.o[b.a],wrong:b.o.filter(function(_,i){return i!==b.a}),e:b.e,extra:b.extra,visual:b.visual});
 rr.seen.push('bank|'+b.uid);rr.seen=rr.seen.slice(-2000);return result;
}

function stopTimers(){if(timer)clearInterval(timer);timer=null;if(feedbackTimer)clearTimeout(feedbackTimer);feedbackTimer=null}
function levelName(l){return ['AQUECIMENTO','BASE','APLICAÇÃO','RITMO','PRESSÃO','ELITE'][Math.max(0,Math.min(5,l))]||'BASE'}
function injectNav(){
  var nav=document.querySelector('.nav');
  if(nav&&!nav.querySelector('[data-rapid]'))nav.insertAdjacentHTML('beforeend','<button data-rapid class="'+(state.page==='rapid'?'active':'')+'" onclick="go(&quot;rapid&quot;)"><span class="icon">⚡</span><span><strong>Modo rápido</strong><small>30 s por questão</small></span></button>');
  var more=document.querySelector('.more-grid');
  if(more&&!more.querySelector('[data-rapid]'))more.insertAdjacentHTML('beforeend','<button data-rapid onclick="go(&quot;rapid&quot;);toggleMore()"><b>⚡</b><span><strong>Modo rápido</strong><small>Run infinito</small></span></button>');
  var bn=document.querySelector('.bottom-nav');
  if(bn&&!bn.querySelector('[data-rapid]'))bn.insertAdjacentHTML('beforeend','<button data-rapid class="'+(state.page==='rapid'?'active':'')+'" onclick="go(&quot;rapid&quot;)"><span class="bn-icon">⚡</span><span>Rápido</span></button>')
}
var oldShell=window.shell;window.shell=function(title){oldShell(title);injectNav()};
var oldGo=window.go;window.go=function(page){if(page==='rapid'){stopTimers();state.page='rapid';state.quiz=null;save();rapidHome();return}stopTimers();oldGo(page)};
var oldCloseBoard=window.closeBoard;window.closeBoard=function(){if(state.board&&state.board.returnRapid&&run&&run.active){state.board.returnRapid=false;save();state.page='rapid';renderRapidQuestion(true);return}oldCloseBoard()};
function rapidHome(){run=null;stopTimers();shell('Modo rápido');var rr=R(),acc=rr.total?Math.round(rr.correct/rr.total*100):0,c=document.querySelector('#content');c.innerHTML='<section class="rapid-hero card"><div><div class="eyebrow">PRÁTICA CONTÍNUA · 30 SEGUNDOS</div><h1>⚡ Modo rápido</h1><p>Questões curtas e variações de prática. Você tem 30 segundos por questão. Acertos aumentam a pressão; erros reduzem o nível e acionam revisão.</p><div class="rapid-pills"><span>⏱ 30 s</span><span>♾️ infinito</span><span>🔄 repetição controlada</span><span>🧠 anti-chute</span></div><button class="btn primary btn-big" onclick="startRapid()">▶ Começar Run</button>'+(rr.mistakes.length?'<button class="btn" style="margin-left:8px" onclick="startRapidReview()">🧩 Rever erros ('+rr.mistakes.length+')</button>':'')+'</div><div class="rapid-score"><div class="rapid-stat"><strong>'+rr.bestScore+'</strong><small>melhor pontuação</small></div><div class="rapid-stat"><strong>'+acc+'%</strong><small>aproveitamento</small></div><div class="rapid-stat"><strong>'+rr.bestCombo+'</strong><small>maior combo</small></div></div></section><div class="grid grid-3 rapid-info-grid"><div class="card"><span class="rapid-icon">🧠</span><h3>Anti-chute</h3><p>Erros recorrentes interrompem o ritmo e exigem uma microexplicação antes de continuar.</p></div><div class="card"><span class="rapid-icon">🔄</span><h3>Variação real</h3><p>Variações numéricas geram novos cálculos. Perguntas conceituais podem voltar para revisão; o histórico recente reduz repetições.</p></div><div class="card"><span class="rapid-icon">📈</span><h3>Dificuldade dinâmica</h3><p>O nível cresce com acertos e recua com erros. Você precisa sustentar o desempenho.</p></div></div>';injectNav()}
function startRapid(){run={active:true,index:0,score:0,combo:0,bestCombo:0,level:1,correct:0,total:0,seconds:30,current:null,answered:false,fast:0,started:Date.now(),lastTopic:null};state.page='rapid';save();renderRapidQuestion()}
function startRapidReview(){var arr=R().mistakes.slice(0,12);if(!arr.length){rapidHome();return}run={active:true,index:0,score:0,combo:0,bestCombo:0,level:2,correct:0,total:0,seconds:30,current:null,answered:false,fast:0,started:Date.now(),lastTopic:null,reviewQueue:arr};state.page='rapid';save();renderRapidQuestion()}
function renderRapidQuestion(resume){if(!run||!run.active){rapidHome();return}stopTimers();var q=resume?run.current:run.reviewQueue&&run.reviewQueue[run.index]?run.reviewQueue[run.index]:qgen(run.level,run.lastTopic);run.current=q;if(!resume)run.seconds=30;run.answered=false;shell('Modo rápido');var c=document.querySelector('#content');c.innerHTML='<div class="rapid-run"><div class="rapid-top card"><div class="rapid-top-main"><span class="eyebrow">⚡ '+(run.reviewQueue?'REVISÃO':'PRÁTICA CONTÍNUA')+'</span><strong>'+levelName(run.level)+'</strong><span class="rapid-topic">'+esc(subjectName(q.s))+' · '+esc(q.t)+'</span></div><div class="rapid-score-live"><span>⭐ '+run.score+'</span><span>🔥 '+run.combo+'</span></div><div class="rapid-timer"><div class="rapid-timer-ring" id="rapid-ring" style="--p:100%"><span id="rapid-seconds">30</span></div><small>segundos</small></div></div><div class="rapid-question card"><div class="rapid-diff"><span class="difficulty '+(q.d||'easy')+'">'+q.difficulty_label+'</span><span>Questão '+(run.index+1)+'</span></div><h2>'+esc(q.q)+'</h2>'+(q.visual?'<div class="visual-question">'+q.visual+'</div>':'')+'<div class="rapid-options">'+q.o.map(function(o,i){return '<button class="rapid-option" onclick="rapidAnswer('+i+')"><span>'+('ABCD'[i])+'</span>'+esc(o)+'</button>'}).join('')+'</div><div class="rapid-feedback" id="rapid-feedback"></div></div><div class="rapid-bottom"><button class="btn" onclick="rapidBoard()">✏️ Lousa</button><button class="btn danger" onclick="stopRapid()">■ Encerrar Run</button></div></div>';injectNav();startTimer()}
function startTimer(){var end=Date.now()+run.seconds*1000,ring=document.querySelector('#rapid-ring'),sec=document.querySelector('#rapid-seconds');timer=setInterval(function(){if(!run||!run.active){stopTimers();return}var left=Math.max(0,end-Date.now());run.seconds=Math.ceil(left/1000);if(sec)sec.textContent=String(run.seconds);if(ring)ring.style.setProperty('--p',(left/30000*100)+'%');if(left<=0){stopTimers();rapidAnswer(null,true)}},100)}
function rapidAnswer(i,timeout){if(!run||!run.active||run.answered)return;stopTimers();run.answered=true;var q=run.current,ok=!timeout&&i===q.a,elapsed=30-run.seconds;if(elapsed<2&&!timeout)run.fast++;run.total++;var rr=R();rr.total++;var tk=q.s+'|'+q.t;rr.topic[tk]=rr.topic[tk]||{total:0,correct:0};rr.topic[tk].total++;var fb=document.querySelector('#rapid-feedback');document.querySelectorAll('.rapid-option').forEach(function(b,j){b.disabled=true;if(j===q.a)b.classList.add('correct');if(!ok&&j===i)b.classList.add('wrong')});if(ok){rr.mistakes=rr.mistakes.filter(m=>m.sig!==q.sig);run.correct++;run.combo++;run.bestCombo=Math.max(run.bestCombo,run.combo);rr.correct++;rr.topic[tk].correct++;var pts=10+Math.max(0,run.combo-1)*2+(q.d==='hard'||q.d==='expert'?3:q.d==='medium'?2:1);run.score+=pts;if(run.combo>=3)run.level=Math.min(5,run.level+1);if(typeof uiSound==='function')uiSound('good');if(fb)fb.innerHTML='<div class="rapid-good">✅ Correto <span>+'+pts+' pts</span></div><p>'+esc(q.e)+'</p>'}else{run.combo=0;run.level=Math.max(1,run.level-1);rr.mistakes.unshift({uid:q.uid,s:q.s,t:q.t,d:q.d,difficulty_label:q.difficulty_label,q:q.q,o:q.o,a:q.a,e:q.e,extra:q.extra,ts:Date.now(),sig:q.sig});rr.mistakes=rr.mistakes.slice(0,100);if(typeof uiSound==='function')uiSound('bad');if(fb)fb.innerHTML='<div class="rapid-bad">❌ '+(timeout?'Tempo esgotado':'Resposta incorreta')+'</div><p>'+esc(q.e)+'</p>'}rr.bestScore=Math.max(rr.bestScore,run.score);rr.bestCombo=Math.max(rr.bestCombo,run.bestCombo);run.lastTopic=q.t;touchStudy();save();var recent=rr.mistakes.filter(function(m){return m.ts>=run.started}).length;var pause=!ok&&(recent>=2||run.fast>=3);run.pauseAfterFeedback=pause;if(fb)fb.insertAdjacentHTML('beforeend','<button class="btn primary" onclick="continueRapidQuestion()">'+(pause?'Revisar o conceito':'Próximo desafio')+'</button>')}
function rapidReviewPause(q){stopTimers();shell('Modo rápido · revisão');var c=document.querySelector('#content');c.innerHTML='<div class="rapid-review-card card"><div class="eyebrow">🧠 PAUSA DE APRENDIZAGEM</div><h1>'+esc(q.t)+'</h1><p class="rapid-review-title">Você acumulou erros ou respostas rápidas demais. Antes de voltar ao Run, explique com suas palavras o conceito abaixo.</p><div class="rapid-review-body"><strong>O que a questão estava testando</strong><p>'+esc(q.e)+'</p>'+(q.extra?'<div class="rapid-review-extra">'+esc(q.extra)+'</div>':'')+'</div><textarea id="rapid-explain" class="rapid-explain" rows="5" placeholder="Explique com suas palavras o que você entendeu…" oninput="rapidCheckExplain()"></textarea><div class="rapid-explain-hint" id="rapid-explain-hint">Escreva pelo menos 15 caracteres para liberar o próximo desafio.</div><div class="toolbar"><button id="rapid-continue" class="btn primary btn-big" disabled onclick="continueRapidAfterReview()">✓ Continuei — voltar ao Run</button><button class="btn" onclick="rapidBoard()">✏️ Lousa</button></div></div>'}
function rapidCheckExplain(){var el=document.querySelector('#rapid-explain'),b=document.querySelector('#rapid-continue'),h=document.querySelector('#rapid-explain-hint');if(!el||!b)return;var ok=el.value.trim().length>=15;b.disabled=!ok;if(h)h.textContent=ok?'Boa. Agora você pode continuar.':'Escreva pelo menos 15 caracteres para liberar o próximo desafio.'}
function continueRapidQuestion(){if(!run||!run.answered)return;if(run.pauseAfterFeedback)rapidReviewPause(run.current);else nextRapid()}
function continueRapidAfterReview(){var el=document.querySelector('#rapid-explain');if(!el||el.value.trim().length<15)return;if(!run)return;run.fast=0;nextRapid()}
function nextRapid(){if(!run||!run.active)return;run.index++;if(run.reviewQueue&&run.index>=run.reviewQueue.length){finishRapid();return}renderRapidQuestion()}
function stopRapid(){if(run&&run.active)finishRapid()}
function finishRapid(){stopTimers();if(!run)return;run.active=false;var rr=R(),score=run.total?Math.round(run.correct/run.total*100):0;rr.bestScore=Math.max(rr.bestScore,run.score);rr.bestCombo=Math.max(rr.bestCombo,run.bestCombo);rr.history.unshift({ts:Date.now(),mode:run.reviewQueue?'review':'run',total:run.total,correct:run.correct,score:score,combo:run.bestCombo,points:run.score});rr.history=rr.history.slice(0,30);save();rapidResult(score)}
function rapidResult(score){shell('Resultado do Modo rápido');var c=document.querySelector('#content'),rr=R();c.innerHTML='<div class="rapid-result card"><div class="eyebrow">RUN ENCERRADO</div><div class="rapid-big-score">'+score+'<small>%</small></div><h1>'+((score>=90)?'Ritmo excelente.':score>=70?'Bom ritmo.':'Agora você sabe onde reforçar.')+'</h1><p>'+run.correct+'/'+run.total+' acertos · '+run.score+' pontos · maior combo '+run.bestCombo+'</p><div class="grid grid-3"><div class="rapid-result-stat"><strong>'+run.correct+'</strong><small>acertos</small></div><div class="rapid-result-stat"><strong>'+(run.total-run.correct)+'</strong><small>erros</small></div><div class="rapid-result-stat"><strong>'+rr.seen.length+'</strong><small>desafios já vistos</small></div></div><div class="toolbar" style="justify-content:center;margin-top:20px"><button class="btn primary btn-big" onclick="startRapid()">⚡ Outro Run</button>'+(rr.mistakes.length?'<button class="btn" onclick="startRapidReview()">🧩 Rever erros</button>':'')+'<button class="btn" onclick="go(&quot;home&quot;)">Voltar</button></div></div>'}
function rapidBoard(){if(!run||run.answered){toast('Leia a explicação e continue antes de abrir a lousa.');return}stopTimers();if(state.board){state.board.returnRapid=true;save()}state.page='board';render()}
var oldRender=window.render;window.render=function(){if(state.page==='rapid'&&!state.quiz){rapidHome();return}oldRender()};
window.continueRapidQuestion=continueRapidQuestion;window.startRapid=startRapid;window.startRapidReview=startRapidReview;window.rapidAnswer=rapidAnswer;window.stopRapid=stopRapid;window.continueRapidAfterReview=continueRapidAfterReview;window.rapidCheckExplain=rapidCheckExplain;window.rapidBoard=rapidBoard;window.CQRapidTest={getQuestion:function(){return qgen(2)},makeQuestion:qmk,getRun:function(){return run},families:F,seen:function(){return R().seen.length}};R();setTimeout(function(){try{render()}catch(e){rapidHome()}},0);
})();