(function(){
'use strict';

const D={
pt:[
["Interpretação e inferência","Interpretar não é repetir palavras do texto. Primeiro separe o que está explicitamente dito, o que é pressuposto pela própria construção e o que precisa ser inferido a partir das pistas. Observe finalidade, interlocutores, contexto, tom, conectivos e relações entre linguagem verbal e não verbal. Em questões de interpretação, a alternativa correta precisa ser sustentada pelo texto; uma leitura apenas possível não basta quando a pergunta pede o que se pode concluir. Inferência exige evidência, enquanto opinião do leitor é uma extrapolação.","• explícito × pressuposto × inferido\n• ironia e ambiguidade dependem do contexto\n• em texto + imagem, os códigos podem construir um sentido conjunto"],
["Gêneros e tipos textuais","Gênero textual é uma forma social de comunicação: ofício, notícia, editorial, cartaz, anúncio, carta, relatório e artigo de opinião são gêneros porque cumprem finalidades e seguem convenções de uso. Tipo textual é o modo de organização predominante, como narração, descrição, exposição, argumentação e injunção. Um gênero pode combinar vários tipos. Em prova, descubra primeiro finalidade, público, situação e estrutura; depois determine a classificação predominante.","• gênero = uso social; tipo = organização do discurso\n• gêneros são híbridos\n• finalidade comunicativa pesa mais que o tema"],
["Estrutura textual","Frase, oração e período não são sinônimos. Oração possui verbo; período é o enunciado delimitado por pontuação final e pode ser simples ou composto. No nível do texto, coesão liga partes por pronomes, conjunções, repetições controladas e substituições; coerência diz respeito à construção global de sentido. Progressão temática significa fazer a informação avançar, evitando um texto que apenas repita a mesma ideia.","• oração é identificada pelo verbo\n• coesão = mecanismos de ligação\n• coerência = sentido global e compatibilidade das ideias"],
["Variação e adequação","A língua varia conforme região, grupo social, época, situação e grau de formalidade. A norma-padrão é uma variedade de prestígio e aparece em situações institucionais, mas adequação depende do contexto. Em prova, cuidado com afirmações absolutas que tratam toda variedade não padrão como “erro”. O ponto central é distinguir existência de uma forma linguística de sua adequação a determinada situação comunicativa.","• variação não é ausência de regras\n• formalidade muda escolha lexical e sintática\n• adequação depende de situação, finalidade e interlocutor"],
["Ortografia e acentuação","Acentuação depende principalmente da sílaba tônica e da estrutura da palavra. Um método seguro é classificar a palavra em oxítona, paroxítona ou proparoxítona e só depois aplicar a regra específica. Proparoxítonas são acentuadas; nas oxítonas e paroxítonas existem conjuntos de terminações e exceções que precisam ser reconhecidos. Ortografia também envolve grafias oficiais, uso de letras e convenções, e a banca pode explorar palavras parecidas que diferem apenas por uma regra.","• primeiro encontre a sílaba tônica\n• proparoxítonas: todas acentuadas\n• diferencie regra de acentuação de simples “memorização da palavra”"],
["Crase","Crase não é simplesmente “acento em palavra feminina”. Ela ocorre quando a preposição a se encontra com o artigo a ou com outra ocorrência compatível. Por isso, a regência é essencial: pergunte se o termo anterior exige a preposição e se o termo seguinte admite artigo. O teste pelo masculino pode ajudar quando a troca preserva a estrutura. Também há contextos em que a crase é proibida ou facultativa, por isso não se deve generalizar a regra.","• procure preposição + artigo\n• regência vem antes do sinal gráfico\n• verbo no infinitivo não recebe crase simplesmente por ser precedido de a"],
["Morfologia","Morfologia estuda a estrutura das palavras e suas classes gramaticais. O radical concentra o núcleo lexical; prefixos e sufixos podem alterar sentido ou formar novas palavras. Substantivo, adjetivo, verbo, advérbio, pronome, artigo, numeral, preposição, conjunção e interjeição são classes diferentes, cada uma com propriedades próprias. A flexão pode indicar gênero, número, pessoa, tempo, modo ou grau, conforme a classe.","• classe gramatical ≠ função sintática\n• radical, prefixo e sufixo ajudam a analisar formação\n• observe também flexões e processos de derivação/composição"],
["Sintaxe e termos da oração","Para analisar sintaxe, comece pelo verbo e descubra a estrutura que ele organiza. Sujeito e predicado são termos essenciais; objetos, complemento nominal e agente da passiva integram a estrutura; adjuntos, aposto e vocativo exercem funções específicas. A transitividade do verbo orienta a identificação dos complementos. Não classifique um termo apenas pela posição na frase: a função depende da relação sintática que ele mantém com o restante da oração.","• comece pelo verbo\n• posição não define função\n• transitividade e regência ajudam a localizar complementos"],
["Coordenação e subordinação","Na coordenação, as orações têm independência sintática relativa e podem ser ligadas por conjunções ou justaposição. Na subordinação, uma oração exerce função em outra, podendo atuar como substantiva, adjetiva ou adverbial. Além da classificação sintática, a banca pode cobrar a relação semântica: causa, condição, concessão, finalidade, consequência, comparação e outras. Memorizar listas de conectivos sem ler o contexto é uma armadilha comum.","• coordenação = relação entre orações independentes\n• subordinação = uma oração exerce função na outra\n• conectivo deve ser interpretado pelo contexto"],
["Regência e concordância","Regência investiga a relação entre um termo regente e seu complemento, especialmente as preposições exigidas por verbos e nomes. Concordância trata da combinação de gênero, número e pessoa entre núcleos e seus determinantes ou entre sujeito e verbo. Em prova, verbos de regência consagrada, sujeitos pospostos e expressões quantitativas podem gerar pegadinhas. Analise o núcleo antes de analisar a expressão o termo mais próximo.","• regência = relação + preposição\n• concordância = combinação com o núcleo\n• não confunda objeto com qualquer palavra depois do verbo"],
["Colocação pronominal","Próclise, ênclise e mesóclise descrevem posições do pronome oblíquo átono em relação ao verbo. Palavras negativas, pronomes relativos, conjunções subordinativas e certos advérbios favorecem a próclise. A mesóclise está associada a determinados tempos do futuro em contexto formal sem elemento atrativo. Na prova, o critério não é “soa natural para mim”; é verificar a estrutura sintática e a norma cobrada.","• identifique primeiro elementos atrativos\n• próclise, ênclise e mesóclise são posições diferentes\n• fala cotidiana e norma-padrão nem sempre coincidem"],
["Pontuação","Pontuação organiza a sintaxe e produz efeitos de sentido. A vírgula pode separar termos deslocados, orações, apostos, vocativos e outros elementos, mas não deve ser usada entre sujeito e verbo apenas porque existe uma pausa na fala. Dois-pontos introduzem explicação, enumeração, consequência contextual ou citação em determinadas construções; travessões e parênteses podem destacar informação. Em questões, a justificativa sintática é mais segura do que o argumento de “respiração”.","• vírgula não depende apenas de pausa\n• pontuação pode alterar foco e sentido\n• analise a estrutura antes de justificar o sinal"],
["Semântica e estilística","Semântica estuda relações de sentido em contexto. Uma mesma palavra pode ter sentidos diferentes segundo o enunciado; metáfora, metonímia, ironia, eufemismo e outras figuras exploram deslocamentos ou efeitos expressivos. O nome da figura é secundário em relação ao mecanismo: pergunte o que foi comparado, substituído, exagerado ou sugerido e qual efeito isso produz. O contexto pode eliminar uma ambiguidade ou criar uma leitura figurada.","• sentido é contextual\n• figura de linguagem = mecanismo + efeito\n• literal e figurado não são escolhas fixas da palavra isolada"],
["Reescrita e produção textual","Reescrever não significa trocar palavras aleatoriamente. A alternativa deve preservar o sentido, a relação lógica, a correção gramatical e, quando exigido, o registro. Mudanças de voz verbal, posição de adjuntos, conectivos e pronomes podem modificar foco ou relação semântica. Em prova, compare o original e a reescrita em camadas: sentido geral, relação entre ideias, estrutura sintática e norma-padrão.","• preserve sentido e relações lógicas\n• verifique concordância, regência e pontuação depois da transformação\n• sinônimo não garante equivalência em todo contexto"]
],
info:[
["Algoritmos e lógica","Algoritmo é uma sequência finita e organizada de passos para resolver um problema. Todo raciocínio algorítmico precisa de entradas, processamento e saídas, e pode usar decisões e repetições. Em fluxogramas, símbolos representam operações, decisões e direção do fluxo; em pseudocódigo, o objetivo é explicitar a lógica sem depender da sintaxe completa de uma linguagem. Para resolver questões, acompanhe a execução passo a passo e mantenha o valor atual de cada variável.","• entrada → processamento → saída\n• decisão cria caminhos; repetição executa blocos novamente\n• acompanhe variáveis em cada etapa"],
["Programação estruturada","Programação estruturada organiza um algoritmo por sequência, seleção e repetição. Variáveis armazenam valores que podem mudar; operadores aritméticos, relacionais e lógicos produzem resultados usados nas condições. Em Python ou JavaScript, a sintaxe muda, mas conceitos como if/else, loops e atribuições permanecem. Em questões de rastreamento, cuidado com a diferença entre atribuir um valor e comparar dois valores.","• sequência, seleção e repetição são estruturas centrais\n• atribuição muda o estado de uma variável\n• comparação produz valor lógico"],
["Sistemas operacionais","O sistema operacional administra recursos do computador e fornece serviços para programas e usuários. Arquivos são organizados em pastas/diretórios; processos representam programas em execução; permissões determinam ações permitidas sobre recursos. É útil separar o papel do sistema operacional do papel de aplicativos: o editor de texto é um programa, enquanto o sistema operacional coordena memória, armazenamento, dispositivos e execução.","• SO gerencia recursos\n• arquivo ≠ programa ≠ processo\n• permissões controlam acesso e ações"],
["Windows 11","No Windows, conceitos de arquivo, pasta, extensão, atalho, busca e configurações são recorrentes. A extensão costuma indicar o formato associado ao arquivo, enquanto um atalho é uma referência para acessar outro recurso. Gerenciar arquivos inclui copiar, mover, renomear, excluir e restaurar. Em prova, atalhos de teclado e diferenças entre funções de janelas podem aparecer, assim como noções de contas, permissões e configurações do sistema.","• conheça operações básicas de arquivos e pastas\n• diferencie atalho de cópia do arquivo\n• revise atalhos e recursos de gerenciamento"],
["Ubuntu Linux","Linux organiza recursos em uma árvore de diretórios que começa em /. Diretórios como /home, /etc e /var têm funções diferentes. Permissões determinam leitura, escrita e execução para classes de usuários; processos representam programas em execução. Comandos básicos devem ser compreendidos pelo efeito, não apenas decorados. A ideia central é que o Linux permite administrar arquivos, processos e recursos por interface gráfica e por terminal.","• / é a raiz\n• permissões envolvem leitura, escrita e execução\n• entenda o efeito dos comandos mais comuns"],
["Hardware e entrada/saída","CPU executa instruções e participa do processamento. RAM oferece memória de trabalho volátil; armazenamento como SSD ou HDD guarda dados de forma persistente. Dispositivos de entrada enviam dados ao computador e dispositivos de saída apresentam resultados; alguns são de entrada e saída. Placa-mãe, barramentos e controladores permitem a comunicação entre componentes. A banca pode explorar a função de cada peça, não apenas o nome.","• CPU processa; RAM é volátil; armazenamento é persistente\n• entrada envia dados; saída apresenta dados\n• componentes trabalham em conjunto"],
["Backup e recuperação","Backup é uma cópia planejada para possibilitar recuperação de dados ou operação. É importante distinguir backup de sincronização: sincronizar pode reproduzir uma exclusão em vários lugares, enquanto uma estratégia de backup busca manter versões recuperáveis. Redundância ajuda disponibilidade, mas não substitui política de cópias e restauração testada. A prova pode abordar versões, mídias, periodicidade e recuperação após falha ou incidente.","• backup precisa ser recuperável\n• versões reduzem impacto de alterações indevidas\n• testar restauração faz parte da estratégia"],
["Office e Google Workspace","Aplicativos de escritório resolvem tarefas diferentes: editores de texto tratam documentos, planilhas trabalham com células, fórmulas e dados tabulares, apresentações organizam informação em slides e ferramentas de colaboração permitem edição e compartilhamento. A prova pode cobrar funções conceituais, referências, formatação, filtros, gráficos e permissões. O importante é reconhecer qual ferramenta e qual recurso atendem a cada problema.","• texto, planilha e apresentação têm funções distintas\n• planilhas usam células, fórmulas e referências\n• colaboração depende de compartilhamento e permissões"],
["Formatos e intercâmbio de dados","Formatos de arquivo influenciam compatibilidade, edição, tamanho e preservação de recursos. Exportar significa gerar uma representação em outro formato; importar significa trazer dados de um formato para um aplicativo; converter pode alterar estrutura ou recursos. Exemplos como PDF, CSV, PNG, JPEG e formatos editáveis precisam ser reconhecidos pelo uso típico. A extensão é um indício, mas compatibilidade depende do conteúdo e do software.","• formato define como dados são representados\n• exportar e importar são operações diferentes\n• formato final e formato editável atendem objetivos diferentes"],
["Redes e Internet","Uma rede permite troca de dados entre dispositivos por meios de comunicação e protocolos. Em uma arquitetura cliente-servidor, um cliente solicita e um servidor fornece recursos ou serviços. A Internet é uma rede mundial de redes que usa protocolos comuns; uma Intranet é uma rede ou ambiente interno controlado por uma organização. Endereço, roteamento, DNS e protocolos ajudam a localizar e transportar dados.","• cliente pede; servidor responde\n• Internet ≠ Intranet\n• protocolos organizam comunicação"],
["Navegadores e pesquisa","Navegadores interpretam páginas e intermediam a interação do usuário com serviços web. Abas, histórico, favoritos, cache e cookies são recursos diferentes. Cache guarda cópias temporárias para acelerar carregamento; cookies armazenam informações relacionadas a sessões, preferências e outros usos definidos pelo site. Pesquisa eficiente exige formular termos, avaliar resultados e conferir a fonte, e não apenas abrir o primeiro link.","• cache ≠ cookies ≠ histórico\n• navegador é diferente de mecanismo de busca\n• pesquise, verifique contexto e fonte"],
["Correio e mensageria","E-mail trabalha com remetente, destinatário, assunto, corpo, anexos e campos de cópia. CC envia uma cópia visível aos destinatários; CCO oculta os demais destinatários. Responder mantém o contexto de uma conversa, enquanto encaminhar cria uma nova transmissão do conteúdo. Em ambiente institucional, cuidados com anexos, destinatários e informações sensíveis são parte da segurança.","• CC é visível; CCO oculta destinatários entre si\n• anexo pode ser vetor de risco\n• confira destinatário antes do envio"],
["Cloud computing","Computação em nuvem oferece recursos computacionais sob demanda. Em IaaS, o cliente administra mais componentes da infraestrutura; em PaaS, o provedor entrega uma plataforma para desenvolvimento; em SaaS, o usuário utiliza um software pronto. Nuvem pública, privada e híbrida descrevem modelos de implantação. Segurança e responsabilidade são compartilhadas: nem tudo fica automaticamente sob responsabilidade exclusiva do provedor.","• IaaS = mais infraestrutura para o cliente gerir\n• PaaS = plataforma\n• SaaS = software pronto"],
["Segurança da informação","Os objetivos clássicos da segurança da informação podem ser resumidos pela tríade confidencialidade, integridade e disponibilidade. Autenticação verifica quem é o usuário; autorização define o que ele pode fazer. Senhas fortes, múltiplos fatores, atualização, backup e princípio do menor privilégio reduzem risco. Não existe ferramenta isolada que elimine todos os ataques; segurança é um conjunto de controles.","• confidencialidade = acesso autorizado\n• integridade = dados corretos e não alterados indevidamente\n• disponibilidade = acesso quando necessário"],
["Malware e defesa","Malware é software criado para realizar ações maliciosas. Vírus dependem de formas específicas de propagação; worms conseguem se espalhar automaticamente entre sistemas vulneráveis; trojans se apresentam como algo legítimo; spyware busca monitorar ou coletar informações. Phishing explora engenharia social para induzir a vítima a revelar dados ou executar ações. Antivírus, firewall, atualização, autenticação e conscientização atuam em camadas.","• malware é categoria ampla\n• phishing explora comportamento humano\n• defesa em camadas é mais robusta que uma medida única"],
["Ambiente corporativo","Em um ambiente corporativo, domínio, contas, grupos e permissões ajudam a administrar acesso centralizado. Autenticação responde “quem é?”; autorização responde “pode fazer o quê?”. Compartilhamento de pastas deve seguir necessidade e princípio do menor privilégio. Auditoria e rastreabilidade ajudam a identificar mudanças e incidentes. Em prova, não confunda pertencer a uma rede com possuir autorização para todos os recursos dela.","• domínio organiza identidade e recursos\n• grupos facilitam administração de permissões\n• acesso deve ser compatível com a função do usuário"]
],
math:[
["Números e operações","Conjuntos numéricos organizam diferentes tipos de números usados nos cálculos: naturais, inteiros e racionais, entre outros. Sinais, prioridade de operações, frações e propriedades como distributividade aparecem em problemas cotidianos. Uma boa resolução mantém unidades e sinais visíveis e evita “pular” etapas. Em expressões, parênteses alteram a ordem de cálculo e a divisão por zero não é permitida.","• respeite ordem das operações\n• atenção aos sinais\n• frações e decimais podem representar a mesma quantidade"],
["Razão e proporção","Razão compara duas grandezas por uma relação multiplicativa. Proporção afirma que duas razões são equivalentes. Em problemas, procure a unidade implícita: quilômetros por hora, reais por item, pixels por medida, pessoas por equipe. Proporcionalidade direta mantém uma razão constante; na inversa, o produto pode permanecer constante. Antes da regra de três, identifique o tipo de relação.","• razão é comparação\n• proporcionalidade direta: quociente constante\n• inversa: produto constante em modelos simples"],
["Regra de três","Regra de três é uma forma organizada de resolver relações proporcionais. Primeiro identifique as grandezas, monte a tabela e verifique se a relação é direta ou inversa. Na composta, pode haver várias grandezas que influenciam o resultado. Um erro comum é cruzar números sem interpretar o enunciado. Sempre faça uma estimativa: o resultado deveria aumentar ou diminuir? Isso pega erros de montagem.","• organize grandezas em linhas/colunas\n• defina direta ou inversa antes de cruzar\n• estime o sentido do resultado"],
["Porcentagem","Porcentagem representa uma razão em base 100. Aumentar 20% significa multiplicar o valor por 1,20; reduzir 20% significa multiplicar por 0,80. Variações sucessivas não devem ser somadas automaticamente: cada percentual incide sobre uma base que pode ter mudado. Em prova, diferencie “20% de 50” de “50 representa quantos por cento de 20”.","• percentual é relativo a uma base\n• aumento e desconto usam fatores diferentes\n• variações sucessivas são multiplicativas"],
["Juros simples","Nos juros simples, os juros de cada período são calculados sobre o capital inicial. A fórmula J = C·i·t relaciona juros, capital, taxa e tempo em unidades compatíveis; o montante é M = C + J. Antes de calcular, transforme a taxa e o tempo para a mesma unidade, quando necessário. Problemas podem pedir qualquer uma das quatro grandezas.","• juros simples usam o capital como base\n• confira unidade de taxa e tempo\n• montante = capital + juros"],
["Álgebra básica","Expressões algébricas usam letras para representar valores e fórmulas. Resolver uma equação significa encontrar valores que tornam a igualdade verdadeira. Operações realizadas de um lado devem ser compensadas do outro, preservando o equilíbrio da igualdade. Produtos notáveis e fatoração podem simplificar expressões, mas em problemas de concurso o mais importante é organizar termos semelhantes, isolar a incógnita e conferir o resultado.","• igualdade precisa ser preservada\n• reduza termos semelhantes\n• substitua o resultado na equação para conferir"],
["Sistemas lineares","Um sistema de duas equações reúne duas condições sobre as mesmas incógnitas. Métodos como substituição e adição eliminam uma variável até encontrar outra; depois a solução completa deve satisfazer as duas equações. Visualmente, cada equação pode ser vista como uma reta e a solução como o ponto de interseção, quando existe uma solução única.","• solução deve satisfazer todas as equações\n• substituição e eliminação são métodos básicos\n• interprete o resultado no contexto"],
["Geometria plana","Perímetro mede o contorno; área mede a superfície interna de uma figura. Para retângulo, A = base·altura; para triângulo, A = base·altura/2; para círculo, A = πr². Unidades de área são quadradas. Em problemas, desenhe a figura e marque medidas antes de substituir números na fórmula. Não confunda diâmetro com raio.","• perímetro ≠ área\n• raio é metade do diâmetro\n• área usa unidade ao quadrado"],
["Geometria espacial","Volume mede o espaço ocupado por um sólido. Para um bloco retangular, V = comprimento·largura·altura; para um cilindro, V = πr²h. Unidades de volume são cúbicas. Questões podem exigir conversões entre cm³ e mL ou entre diferentes unidades de comprimento. Visualizar as três dimensões evita usar fórmulas de área quando o problema pede volume.","• volume usa três dimensões\n• unidades cúbicas importam\n• 1 cm³ corresponde a 1 mL"],
["Medidas e sistema monetário","Unidades precisam ser compatíveis antes de operar. Comprimento, área, volume, massa, capacidade e tempo usam escalas diferentes. Também é necessário distinguir uma transformação linear de uma transformação de área ou volume: converter metros quadrados não é simplesmente multiplicar pelo mesmo fator usado para metros. Em valores monetários, centavos e reais devem ser tratados de forma consistente.","• converta antes de combinar medidas\n• área e volume mudam o fator de conversão\n• confira casas decimais em dinheiro"],
["PA e PG","Progressão aritmética possui diferença constante entre termos consecutivos; progressão geométrica possui razão multiplicativa constante. Na PA, cada termo pode ser obtido somando a diferença d; na PG, multiplicando pela razão q. A identificação correta vem antes da fórmula do termo geral. Questões podem mostrar sequências e pedir reconhecimento, termo específico ou comportamento de crescimento.","• PA: soma d\n• PG: multiplica por q\n• procure a diferença ou razão constante"],
["Combinatória","O princípio multiplicativo diz que, se uma escolha pode ser feita de a maneiras e outra de b maneiras, e ambas devem ocorrer, temos a·b possibilidades, sob as condições adequadas. Permutação considera reordenações; arranjos consideram escolha ordenada. A palavra “ordem” é decisiva: ABC e BAC representam resultados diferentes quando a ordem importa.","• pergunte se ordem importa\n• use árvore ou etapas para organizar escolhas\n• não confunda escolha com reordenação"],
["Probabilidade","Probabilidade mede a chance de um evento. Em casos equiprováveis, P(A) = casos favoráveis/casos possíveis. O espaço amostral reúne todos os resultados possíveis e o evento é o subconjunto de interesse. Probabilidade condicional muda o conjunto de referência quando uma informação é conhecida. Diagramas e tabelas ajudam a evitar dupla contagem.","• defina espaço amostral\n• casos favoráveis precisam estar dentro dos possíveis\n• condição muda a referência"],
["Estatística","Média soma os valores e divide pelo número de observações. Mediana é o valor central após ordenar os dados; moda é o valor que mais se repete. A escolha da medida depende da distribuição: a mediana pode ser mais representativa quando há valores extremos. Em prova, gráficos, tabelas e conjuntos pequenos costumam exigir leitura e interpretação, não só conta.","• ordene os dados para achar mediana\n• moda depende de frequência\n• escolha a medida de acordo com o contexto"],
["Lógica e sequências","Questões de lógica podem cobrar relações, equivalências, negações, padrões e sequências. Para uma sequência numérica, compare diferenças, razões ou alternâncias. Para proposições, identifique o valor lógico e o efeito de conectivos como e, ou, se... então. Não tente adivinhar um padrão sem testar nos primeiros termos e contraexemplos.","• procure a regra mais simples que explica os termos\n• diferencie e/or/implicação\n• teste a regra em toda a sequência"]
],
direito:[
["Princípios da Administração Pública","O art. 37 da Constituição consagra princípios básicos da Administração Pública, tradicionalmente lembrados pela sigla LIMPE: legalidade, impessoalidade, moralidade, publicidade e eficiência. Legalidade exige atuação conforme a lei; impessoalidade afasta favorecimento pessoal; moralidade exige padrões éticos; publicidade favorece transparência; eficiência exige boa utilização dos recursos e qualidade da atuação. Em prova, um caso concreto pode misturar dois ou mais princípios.","• memorize LIMPE e o sentido de cada princípio\n• impessoalidade não é anonimato: é atuação institucional sem favorecimento pessoal\n• publicidade tem relação com transparência, mas admite limites legais"],
["Poderes administrativos","Os poderes administrativos são instrumentos para a Administração cumprir suas funções. O poder hierárquico organiza a estrutura e distribui atribuições; o disciplinar permite apurar e punir infrações funcionais nos termos da lei; o regulamentar permite detalhar a execução da lei dentro dos limites legais; o poder de polícia restringe ou condiciona direitos individuais em favor do interesse coletivo. Não confunda poder administrativo com poder político.","• hierárquico = organização interna\n• disciplinar = infrações e sanções administrativas\n• polícia = condicionamento do exercício de direitos"],
["Atos administrativos","Ato administrativo pode ser estudado por elementos como competência, finalidade, forma, motivo e objeto. Seus atributos tradicionalmente incluem presunção de legitimidade, imperatividade e, em certos casos, autoexecutoriedade. Anulação está ligada à ilegalidade; revogação decorre de avaliação de conveniência e oportunidade de ato válido, respeitados seus limites. Convalidação pode sanar certos vícios. A pegadinha costuma ser tratar anulação e revogação como sinônimos.","• elementos: competência, finalidade, forma, motivo e objeto\n• ilegalidade → anulação\n• mérito administrativo, dentro dos limites legais, relaciona-se à revogação"],
["Serviços públicos","Serviço público corresponde a atividade destinada ao atendimento de necessidades coletivas sob responsabilidade do Estado, diretamente ou por formas admitidas pelo ordenamento. Princípios como continuidade, adequação, segurança e atendimento ao usuário podem aparecer em diferentes contextos normativos. Em questões, diferencie serviço público de atividade puramente privada e observe quem possui responsabilidade pela prestação e quais regras a disciplinam.","• há finalidade pública e responsabilidade estatal\n• continuidade e adequação são ideias recorrentes\n• prestação direta e formas delegadas não eliminam a natureza pública da atividade"],
["Servidores e agentes públicos","Agente público é expressão ampla para quem exerce função pública, em caráter permanente ou temporário e por diferentes vínculos. Cargo, emprego e função não são equivalentes. Cargo público é criado por lei e integra a estrutura administrativa; emprego público possui vínculo contratual; função descreve atribuições exercidas em determinada situação. Em prova, foque nas diferenças conceituais e no regime jurídico aplicável ao caso.","• agente público é gênero amplo\n• cargo, emprego e função são categorias distintas\n• vínculo e regime devem ser identificados pelo enunciado"],
["Órgãos públicos","Órgão público é unidade de atuação integrante da estrutura administrativa, sem personalidade jurídica própria. Entidades, ao contrário, possuem personalidade jurídica própria. Essa distinção ajuda a compreender a organização administrativa e a distribuição de competências. Em prova, não trate todo “órgão” como se fosse uma empresa pública ou autarquia; o fato de possuir estrutura e competência não significa possuir personalidade jurídica independente.","• órgão não possui personalidade jurídica própria\n• entidade possui personalidade\n• competência é distribuída pela estrutura administrativa"],
["Improbidade administrativa","Improbidade administrativa está relacionada a condutas que atentem contra deveres jurídicos da Administração e que se enquadrem nas hipóteses legais. A Lei de Improbidade sofreu alterações importantes, por isso o estudo deve seguir a legislação vigente e não apenas resumos antigos. Em prova, diferencie ilegalidade comum de uma conduta que preencha os requisitos legais da improbidade e observe elementos subjetivos e consequências previstas.","• estude pela legislação vigente\n• nem toda ilegalidade é automaticamente improbidade\n• observe requisitos e consequências do tipo legal"],
["Processo administrativo","Processo administrativo organiza a formação de uma decisão da Administração e deve respeitar garantias, princípios e regras aplicáveis. Etapas podem envolver instauração, instrução, manifestação dos interessados, produção de provas, motivação e decisão. Motivação significa explicitar as razões de fato e de direito que sustentam a decisão. Em questões, observe contraditório, finalidade, competência e necessidade de fundamentação.","• processo organiza decisão administrativa\n• motivação explica fatos e fundamentos jurídicos\n• instrução reúne elementos necessários à decisão"],
["Licitações — fundamentos","A Lei 14.133/2021 estabelece regras gerais para licitações e contratos administrativos. O planejamento é parte importante do processo: definir necessidade, solução, estimativas e requisitos antes da disputa reduz improvisação. Princípios como planejamento, transparência, igualdade, julgamento objetivo e segregação de funções aparecem no regime. A prova pode cobrar a sequência geral e a finalidade das etapas, além das diferenças entre institutos.","• planejamento vem antes da disputa\n• conheça princípios da Lei 14.133\n• licitação busca proposta adequada ao interesse público dentro das regras legais"],
["Lei 14.133 — modalidades","A Lei 14.133 prevê pregão, concorrência, concurso, leilão e diálogo competitivo. A modalidade não deve ser escolhida apenas pelo valor: o objeto e as características da contratação são relevantes. Pregão é voltado a bens e serviços comuns; concurso, à escolha de trabalho técnico, científico ou artístico mediante prêmio ou remuneração; leilão, à alienação nas hipóteses legais; concorrência possui aplicação ampla; diálogo competitivo atende situações complexas nos termos da lei.","• modalidades são diferentes de critérios de julgamento\n• pregão está ligado a bens e serviços comuns\n• concurso e leilão têm finalidades próprias"],
["Lei 14.133 — contratação direta","Contratação direta reúne hipóteses em que a Administração não realiza uma disputa nos moldes de uma licitação. Dispensa ocorre quando a lei autoriza contratar diretamente apesar de a competição ser possível; inexigibilidade ocorre quando a competição é inviável. A classificação importa porque os fundamentos e requisitos jurídicos são diferentes. Não confunda contratação direta com contratação sem processo ou sem justificativa.","• dispensa ≠ inexigibilidade\n• contratação direta continua sujeita aos requisitos legais\n• a ausência de disputa não significa ausência de controle"],
["CF — princípios fundamentais","Os arts. 1º a 4º da Constituição apresentam fundamentos e objetivos centrais da República. O art. 1º traz fundamentos como soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político. O art. 2º trata da separação dos Poderes; o art. 3º lista objetivos fundamentais; o art. 4º estabelece princípios que regem as relações internacionais. A banca pode pedir associação entre artigo e conteúdo.","• art. 1º = fundamentos\n• art. 3º = objetivos fundamentais\n• art. 4º = relações internacionais"],
["CF — direitos e garantias","O art. 5º reúne direitos e garantias fundamentais e apresenta temas como vida, liberdade, igualdade, segurança, propriedade, intimidade, devido processo, contraditório e ampla defesa. A leitura deve ser cuidadosa porque muitos incisos estabelecem condições, exceções e garantias específicas. Não memorize apenas palavras isoladas; entenda qual direito está sendo protegido e em que situação a Constituição estabelece limites ou procedimentos.","• direito e garantia não são sinônimos perfeitos\n• leia o inciso completo quando estudar\n• igualdade, liberdade e devido processo aparecem em diferentes relações"],
["CF — direitos sociais e nacionalidade","Os arts. 6º a 11 concentram direitos sociais e disposições relacionadas ao trabalho, enquanto os arts. 12 e 13 tratam de nacionalidade e símbolos/idioma da República. A banca pode cobrar a identificação dos direitos sociais, regras gerais de nacionalidade e diferenças entre brasileiro nato e naturalizado. Como a Constituição possui detalhes e hipóteses específicas, estude a redação vigente dos dispositivos e não confie em listas antigas.","• art. 6º abre o bloco de direitos sociais\n• arts. 12–13 tratam de nacionalidade e símbolos\n• diferencie nato e naturalizado pelas hipóteses constitucionais"],
["CF — direitos políticos e municípios","Os arts. 14 a 16 tratam de direitos políticos, como sufrágio, voto, condições de elegibilidade e hipóteses constitucionais relacionadas ao processo eleitoral. Os arts. 29 a 31 concentram normas sobre Municípios, incluindo organização por Lei Orgânica, eleição, competências e fiscalização. Para o concurso da Câmara, associe esse bloco constitucional à estrutura municipal e ao papel fiscalizador do Legislativo.","• direitos políticos: arts. 14–16\n• organização municipal: art. 29 em diante\n• fiscalização municipal envolve Câmara e controle previsto constitucionalmente"],
["CF — Administração Pública","Os arts. 37 a 41 formam um bloco essencial para concursos públicos. O art. 37 concentra princípios, regras sobre cargos, concurso, acumulação e outras disposições; os arts. 38 a 41 tratam de situações envolvendo servidores, regimes, estabilidade e perda do cargo segundo os requisitos constitucionais. Questões podem combinar mais de um dispositivo, então estude o bloco como sistema e não como frases isoladas.","• art. 37 é o núcleo de princípios e regras administrativas\n• estabilidade não é sinônimo de impossibilidade absoluta de perda do cargo\n• requisitos constitucionais precisam ser lidos com atenção"]
],
municipio:[
["Origem e ferrovia","O histórico oficial do IBGE relaciona a formação do núcleo que deu origem a Senador Canedo à estrada de ferro e à Fazenda Vargem Bonita. A ferrovia favoreceu circulação de pessoas, trabalho e crescimento do povoado. Para prova local, o ponto não é transformar a história em narrativa romântica: é reconhecer a relação entre infraestrutura ferroviária, ocupação do território e formação do núcleo que depois passaria por mudanças administrativas.","• ferrovia é eixo da formação histórica\n• Fazenda Vargem Bonita aparece no histórico do IBGE\n• estude relações de causa e sequência, não só nomes"],
["Esplanada e homenagem","O histórico oficial registra a denominação Esplanada e a homenagem a Antônio Amaro da Silva Canedo como parte do processo de formação municipal. O estudo deve ligar nome, período e contexto, evitando a ideia de que a cidade nasceu de um único fundador. A história administrativa é construída por sucessivas transformações do núcleo, e nomes anteriores ajudam a localizar essas etapas.","• Esplanada é marco histórico da denominação\n• Antônio Amaro da Silva Canedo é a pessoa homenageada\n• não reduza a formação municipal a um único agente"],
["Distrito e Goiânia","Senador Canedo foi criado como distrito em 1953 e esteve vinculado administrativamente a Goiânia. Ser distrito significa integrar administrativamente outro município e não possuir a autonomia política de um município emancipado. Essa diferença é uma das principais pegadinhas cronológicas: o ano de criação do distrito não corresponde ao ano da emancipação nem ao da instalação do Município.","• 1953 = criação do distrito\n• distrito ≠ município autônomo\n• vínculo com Goiânia pertence à fase anterior à emancipação"],
["Emancipação e instalação","A emancipação política de Senador Canedo ocorreu em 1988 por lei estadual, enquanto a instalação do Município ocorreu em 1º de junho de 1989, conforme o histórico oficial. São marcos diferentes: a emancipação cria a condição política do novo município; a instalação marca o início efetivo da estrutura municipal. Em questões, a troca entre 1988 e 1989 é uma pegadinha direta.","• 1988 = emancipação\n• 01/06/1989 = instalação\n• não trate os dois termos como sinônimos"],
["Formação administrativa","A formação administrativa acompanha mudanças de vínculo, distrito, desmembramento e autonomia. Uma relação territorial pode ser administrativa em um período e apenas geográfica em outro. Por isso, quando a questão cita outro município, pergunte qual é a relação: distrito, desmembramento, vizinhança ou inserção regional. Esse raciocínio evita misturar história administrativa com simples localização no mapa.","• distrito, desmembramento e vizinhança são relações diferentes\n• cronologia importa\n• use o histórico do IBGE como referência-base"],
["Geografia local","Para estudar geografia local, pense em três camadas: Estado de Goiás, Região Metropolitana de Goiânia e município de Senador Canedo. Relacione localização, municípios próximos, características físicas e dinâmica demográfica/econômica. Dados numéricos mudam ao longo do tempo, então verifique o ano da fonte indicada no edital ou no material oficial. Uma questão pode pedir interpretação de dados, não só memorização de um número.","• localização regional + posição no Estado\n• observe o ano de qualquer dado estatístico\n• geografia pode aparecer em mapas, tabelas e comparação"],
["Municípios circunvizinhos","Conhecer os municípios vizinhos exige orientação espacial. Uma forma eficiente é montar um mapa mental com Senador Canedo no centro e os municípios limítrofes ao redor, confirmando a informação em fonte oficial. Na prova, a banca pode trocar um vizinho por outro município da região metropolitana, explorando a diferença entre “estar na mesma região” e “fazer divisa”.","• vizinhança = divisa territorial\n• Região Metropolitana é conceito mais amplo\n• estude a posição relativa, não apenas uma lista"],
["Economia e dinâmica urbana","A dinâmica urbana de Senador Canedo deve ser estudada por atividade econômica, ocupação e relação com o entorno metropolitano. Indústria, comércio, serviços, circulação de pessoas e expansão urbana se relacionam. Em vez de decorar um único setor, entenda como crescimento populacional, localização e infraestrutura alteram a organização da cidade. Dados econômicos precisam ser associados ao período da fonte.","• economia e urbanização são interdependentes\n• dados devem vir com o ano\n• a posição metropolitana ajuda a explicar dinâmica urbana"],
["Lei Orgânica — competência legislativa","A Lei Orgânica organiza a autonomia municipal e distribui competências entre Câmara e Executivo. Em matérias legislativas, uma questão pode exigir saber quando a Câmara atua na produção de normas e quando existe participação ou sanção do Prefeito. A chave é distinguir iniciativa, discussão/votação, sanção ou veto e promulgação conforme o procedimento aplicável, sem transformar toda lei em ato exclusivo de um só Poder.","• competência depende da matéria e do procedimento\n• Câmara legisla e fiscaliza dentro das regras locais\n• sanção/veto pertencem ao processo legislativo quando previstos"],
["Lei Orgânica — competências privativas","Competência privativa da Câmara significa que determinada matéria pertence à atuação do Legislativo municipal segundo a Lei Orgânica. Isso não é sinônimo de dizer que tudo que envolve o Município é decisão exclusiva da Câmara. O estudo deve separar funções legislativas, fiscalizadoras, administrativas internas e relações com o Executivo.","• “privativa” precisa ser lida no contexto da Lei Orgânica\n• Legislativo não substitui todas as funções do Executivo\n• memorize os núcleos de competência indicados pelo texto legal"],
["Administração Municipal","A Administração Municipal reúne estruturas responsáveis pela execução de políticas, serviços e atos administrativos. O Prefeito chefia o Executivo municipal; a Câmara integra o Legislativo e exerce funções legislativas e fiscalizadoras. O Município possui autonomia para organizar assuntos de interesse local, dentro da Constituição e das normas aplicáveis. Em prova, diferenças entre Poderes e competências costumam ser mais importantes que nomes de pessoas.","• Executivo administra; Legislativo legisla e fiscaliza\n• autonomia municipal tem limites constitucionais\n• competência deve ser ligada ao órgão correto"],
["Poder Legislativo municipal","A Câmara Municipal é composta por vereadores e possui organização interna com Mesa, sessões e comissões. Sua atuação envolve elaboração legislativa, fiscalização do Executivo e outras competências previstas na Constituição e na Lei Orgânica. Questões podem explorar o papel das comissões, do plenário, da Mesa e dos mecanismos de fiscalização. Não confunda Câmara com Prefeitura: são Poderes municipais distintos.","• vereadores integram o Legislativo\n• Mesa organiza a Câmara\n• plenário, comissões e sessões cumprem funções diferentes"],
["Transparência e comunicação pública","Comunicação pública deve priorizar informação de interesse coletivo, clareza, acesso e impessoalidade. Transparência significa permitir que o cidadão conheça atos, dados e decisões dentro das regras de publicidade e das hipóteses legais de restrição. Comunicação institucional não deve se transformar em promoção pessoal de autoridade. Em Design, isso se conecta diretamente a hierarquia, acessibilidade, legibilidade e linguagem objetiva.","• informar ≠ promover pessoa\n• clareza e acessibilidade ampliam acesso\n• transparência depende de publicidade e das regras legais aplicáveis"],
["Estatuto do servidor","O Estatuto municipal deve ser estudado pelos blocos de direitos, deveres, proibições, responsabilidades, vantagens e formas de ingresso ou desligamento previstas na lei local. Para o concurso, leia a redação específica do estatuto indicado no edital e não substitua o texto legal por um resumo genérico. Organize o estudo em “o servidor pode”, “deve”, “não pode” e “responde por”.","• estudar a lei local indicada no edital\n• separar direitos, deveres, proibições e responsabilidades\n• atenção a prazos, sanções e requisitos específicos do texto legal"]
],
design:[
["Fundamentos e elementos visuais","Todo projeto visual parte de elementos básicos: ponto, linha, forma, espaço, cor e textura. Esses elementos não têm efeito isolado; suas relações produzem direção, ritmo, contraste, escala e foco. Um ponto pode marcar uma posição; uma linha pode conduzir o olhar; formas podem criar silhuetas e massas; o espaço pode gerar respiro ou tensão. Antes de estudar estilos, entenda como decisões elementares constroem uma composição.","• elementos = matéria-prima\n• princípios = relação entre elementos\n• observe escala, posição, repetição e contraste"],
["Gestalt — proximidade e semelhança","A Gestalt estuda como a percepção organiza estímulos em padrões. Pela proximidade, elementos próximos tendem a ser percebidos como grupo; pela semelhança, elementos com cor, forma ou tamanho compartilhado tendem a ser agrupados. Em interfaces, isso ajuda a fazer o usuário entender quais rótulos pertencem a quais controles. O designer pode usar esses princípios para criar agrupamento sem precisar desenhar uma borda em torno de cada grupo.","• proximidade = distância entre elementos\n• semelhança = características compartilhadas\n• percepção pode criar grupos sem contornos explícitos"],
["Gestalt — fechamento e continuidade","Fechamento ocorre quando percebemos uma forma completa mesmo com partes ausentes; continuidade faz o olhar acompanhar trajetórias e alinhamentos. Esses princípios são úteis em marcas, ícones, diagramas e composições em que a forma não precisa estar totalmente desenhada para ser reconhecida. Em prova, observe o mecanismo perceptual, não apenas a aparência final da figura.","• fechamento completa lacunas percebidas\n• continuidade favorece trajetórias coerentes\n• o cérebro organiza informação incompleta"],
["Gestalt — figura/fundo e pregnância","Figura/fundo trata da separação perceptual entre aquilo que recebe destaque e o campo que o sustenta. Uma composição pode permitir alternância entre figura e fundo, especialmente quando contornos e contrastes são ambíguos. Pregnância, ou boa forma, relaciona-se à tendência de organizar a percepção de maneira simples, estável e regular. Use esses conceitos para explicar por que certas formas são percebidas imediatamente e outras exigem esforço.","• figura = foco; fundo = campo de suporte\n• contraste e contorno influenciam segregação\n• pregnância favorece organização simples e estável"],
["Hierarquia e composição","Hierarquia visual determina a ordem de atenção. Escala, peso tipográfico, cor, contraste, posição e espaço podem fazer um título chamar atenção antes do corpo do texto. Composição também envolve equilíbrio, alinhamento, ritmo e focalização. Não existe uma fórmula única: uma peça pode ter assimetria e continuar equilibrada. O importante é que o sistema visual torne clara a prioridade da informação.","• hierarquia = ordem de leitura\n• equilíbrio não significa simetria obrigatória\n• contraste é um dos principais motores de prioridade"],
["Grid e layout","Grid é uma estrutura invisível de margens, colunas, módulos, linhas e alinhamentos que ajuda a organizar conteúdo. Ele reduz decisões arbitrárias e cria consistência entre páginas ou peças de uma mesma série. Grid não precisa aparecer visualmente; serve como ferramenta de organização. Em layout editorial, alinhar imagens, títulos, legendas e texto produz ritmo e facilita a leitura.","• grid organiza, não enfeita\n• margens + colunas + módulos criam alinhamento\n• consistência não impede variação controlada"],
["Tipografia — anatomia e famílias","Tipografia possui características estruturais que afetam reconhecimento e personalidade. Serifa, altura-x, largura, peso e proporções alteram a leitura. Famílias podem incluir variações de peso, largura e estilo; categorias como serifada, sem serifa, display, script e monoespaçada ajudam a pensar em uso, mas não substituem a análise da fonte. Em prova, relacione anatomia e aplicação.","• altura-x influencia aparência do corpo de texto\n• serifa é apenas uma característica, não “qualidade” universal\n• família inclui variações relacionadas"],
["Tipografia — legibilidade","Legibilidade depende do desenho das letras e também de como o texto é composto. Tamanho, contraste, entrelinha, comprimento das linhas, peso e espaçamento interferem no esforço de leitura. Texto corrido em linhas excessivamente longas pode aumentar a dificuldade; contraste insuficiente reduz percepção. Em tela, responsividade muda o espaço disponível, então a tipografia precisa ser testada em diferentes larguras.","• fonte + composição formam legibilidade\n• entrelinha e comprimento de linha importam\n• contraste precisa ser suficiente para o meio"],
["Cor — modelos","RGB trabalha com luz e usa canais vermelho, verde e azul; é típico de telas e outros meios emissivos. CMYK trabalha com ciano, magenta, amarelo e preto e está associado a processos de impressão. Como os meios de reprodução possuem gamuts diferentes, uma cor exibida na tela pode não ser reproduzida exatamente no impresso. O designer deve considerar perfil de cor, dispositivo e destino do arquivo.","• RGB = luz/tela\n• CMYK = tinta/impressão\n• conversão pode alterar a aparência da cor"],
["Cor — harmonia e contraste","Harmonia descreve relações entre cores na composição. Esquemas análogos usam cores vizinhas; complementares aproximam opostos do círculo cromático; triádicos distribuem três relações equilibradas. Contraste também pode vir de valor, saturação, temperatura, tamanho e quantidade, não apenas de matiz. A escolha deve considerar função, legibilidade e mensagem, e não apenas gosto pessoal.","• análoga = vizinhas\n• complementar = relação de oposição\n• contraste pode ser cromático ou estrutural"],
["Psicologia da cor e contexto","Associações de cor podem influenciar interpretação, mas não são significados universais e imutáveis. Cultura, público, contexto, combinação cromática e histórico da instituição alteram a leitura. Azul pode sugerir confiança em um contexto e representar uma convenção cultural diferente em outro. Em comunicação pública, a cor deve reforçar função e identificação sem substituir informação textual.","• significado depende de contexto\n• cultura e público importam\n• cor não deve ser o único veículo da informação"],
["Comunicação institucional","Comunicação institucional informa sobre serviços, ações, direitos, procedimentos e funcionamento da organização. O design precisa priorizar clareza, objetividade, hierarquia, acessibilidade e consistência. No setor público, a peça deve servir ao interesse institucional e coletivo, evitando personalização indevida. Uma boa solução não é a mais ornamentada: é a que torna a informação compreensível para o público correto.","• finalidade vem antes da ornamentação\n• clareza + hierarquia + acessibilidade\n• comunicação pública não deve virar promoção pessoal"],
["Identidade visual","Identidade visual é um sistema de elementos que permite reconhecer uma instituição ou marca com consistência. Símbolo, logotipo, assinatura, cores, tipografia e aplicações formam partes de um sistema. Um logo isolado não garante identidade: é necessário definir como os elementos funcionam juntos. A consistência aparece em diferentes materiais, tamanhos, fundos e situações de uso.","• identidade = sistema\n• logo é parte, não o sistema inteiro\n• consistência precisa sobreviver a diferentes aplicações"],
["Manual de identidade","O manual registra regras que permitem reproduzir a identidade sem depender da memória do designer. Pode especificar versões positiva e negativa, área de proteção, tamanho mínimo, cores, tipografia, fundos permitidos e usos incorretos. O objetivo não é burocratizar; é reduzir variações e preservar reconhecimento. Em ambientes institucionais, o manual também ajuda equipes diferentes a manter o mesmo padrão.","• área de proteção = respiro ao redor\n• tamanho mínimo evita perda de reconhecimento\n• regras de aplicação devem ser reproduzíveis"],
["Símbolos públicos","Brasões, selos, marcas oficiais e outros símbolos públicos cumprem função institucional e têm regras próprias de uso. Ao criar ou aplicar um símbolo público, o designer precisa preservar integridade, reconhecimento e contexto institucional. O uso não deve sugerir que patrimônio simbólico da instituição seja propriedade pessoal de um agente público. Em prova, atenção à distinção entre identidade institucional e autopromoção.","• símbolo público representa instituição\n• integridade da marca/símbolo importa\n• não confundir comunicação institucional com promoção pessoal"],
["Diagramação de publicações","Diagramação organiza conteúdo editorial em páginas. Texto, imagem, título, legenda, chamada e elementos auxiliares precisam estabelecer hierarquia e ritmo. Grid, margens e alinhamentos ajudam a criar consistência, enquanto respiro evita uma página visualmente saturada. Uma boa composição também considera ordem de leitura, tamanho de blocos e relação entre imagem e texto.","• hierarquia orienta leitura\n• grid organiza repetição e alinhamento\n• respiro é recurso de composição, não espaço desperdiçado"],
["Produção gráfica","Produção gráfica transforma um arquivo digital em uma peça física. O processo pode envolver escolha de papel, formato, impressão, prova, acabamento e controle de qualidade. Offset e impressão digital possuem características e usos diferentes. Corte, dobra, laminação, verniz e outros acabamentos precisam aparecer no planejamento. O arquivo correto depende do processo e do material escolhidos.","• projeto precisa considerar material e processo\n• acabamento altera custo e resultado\n• prova permite conferir antes da produção final"],
["Fechamento de arquivo","Fechar um arquivo significa prepará-lo para produção. Sangria estende elementos além da linha de corte; marcas de corte ajudam a orientar o acabamento; perfis de cor precisam ser compatíveis com o processo; fontes e imagens devem estar corretamente incorporadas ou tratadas. Antes de enviar, faça uma conferência sistemática. Muitos problemas de impressão vêm de arquivos visualmente corretos na tela, mas tecnicamente incompletos.","• sangria evita filetes brancos após corte\n• área segura protege informações essenciais\n• confira fontes, links, resolução e perfil de cor"],
["Tratamento de imagens","Tratamento de imagem envolve ajustes de recorte, cor, contraste, composição e qualidade. Raster é formado por pixels e depende de resolução; ampliações excessivas podem produzir pixelização. Vetor descreve formas matematicamente e costuma ser mais adequado para logos e elementos que precisam escalar. O tratamento deve preservar intenção, qualidade e contexto, evitando alterações que distorçam informação relevante.","• raster = pixels\n• vetor = formas escaláveis\n• tratamento deve considerar destino e tamanho de saída"],
["Design para web","Na web, uma composição precisa funcionar em diferentes larguras e formas de interação. Responsividade pode mudar colunas, tamanhos, espaçamentos e ordem de elementos; não é simplesmente “diminuir tudo”. Hierarquia precisa continuar clara em telas pequenas. Tipografia, imagens e controles devem se adaptar sem perder função. A avaliação deve considerar diferentes dispositivos e condições de uso.","• responsividade reorganiza\n• mantenha hierarquia em diferentes larguras\n• teste interação e leitura, não só aparência"],
["Redes sociais institucionais","Cada canal possui proporções, ritmo e contexto de consumo diferentes. Feed, story, carrossel e vídeo exigem adaptações de composição. Em comunicação institucional, uma identidade consistente deve conviver com formatos variados. Títulos precisam ser legíveis rapidamente e informações críticas não podem depender de áreas que serão cortadas ou sobrepostas por elementos da plataforma.","• adapte formato sem perder sistema visual\n• leitura em poucos segundos importa\n• respeite zonas seguras e acessibilidade"],
["UX/UI no setor público","UX trata a experiência de realizar uma tarefa; UI trata a interface visual e interativa que materializa essa experiência. Um bom fluxo exige clareza de tarefa, affordance, feedback, consistência e prevenção de erro. Um botão bonito que não comunica o que acontecerá falha em UX mesmo que a aparência seja excelente. No setor público, a experiência deve facilitar o acesso a serviços e informações.","• UX = experiência/fluxo/tarefa\n• UI = apresentação/interação visual\n• feedback mostra o resultado de uma ação"],
["Acessibilidade visual","Acessibilidade busca reduzir barreiras para pessoas com diferentes capacidades, contextos e dispositivos. Contraste, tamanho, espaçamento, estrutura, foco visível, alternativas textuais e uso redundante de sinais são exemplos de estratégias. Cor não deve ser o único meio de transmitir uma distinção: combine cor com rótulo, ícone, texto ou padrão quando necessário. A acessibilidade deve ser pensada desde o início do projeto.","• contraste é necessário, mas não suficiente\n• não dependa só de cor\n• estrutura e foco também importam"],
["WCAG — visão conceitual","WCAG organiza acessibilidade da web em quatro princípios: Perceptível, Operável, Compreensível e Robusto, conhecidos pela sigla POUR. Os critérios possuem níveis de conformidade e técnicas associadas. Para estudo, não memorize apenas números: entenda o tipo de barreira que cada requisito procura reduzir. Exemplo: texto alternativo trata conteúdo não textual; contraste trata percepção visual do texto.","• POUR = Perceptível, Operável, Compreensível, Robusto\n• critérios atacam barreiras específicas\n• WCAG não é simplesmente uma paleta ou checklist de cores"],
["Comunicação inclusiva","Comunicação inclusiva procura reduzir barreiras linguísticas e visuais sem cair em estereótipos ou generalizações. Representação visual deve considerar diversidade de públicos e contexto; texto deve buscar clareza e respeito. Em materiais públicos, inclusão não é apenas trocar palavras: envolve acessibilidade, escolha de exemplos, representação e facilidade de acesso à informação.","• inclusão envolve texto e imagem\n• evite estereótipos e generalizações\n• clareza e acessibilidade caminham junto da representação"],
["Direitos autorais","Direitos autorais protegem obras e estabelecem condições relacionadas ao uso. Encontrar uma imagem na Internet não significa receber autorização para usá-la em qualquer contexto. É preciso verificar autoria, licença, domínio público quando aplicável e eventuais requisitos de atribuição. Para prova, diferencie autoria, licença e simples acesso ao arquivo. Uma obra acessível não se torna automaticamente livre de direitos.","• Internet não é sinônimo de domínio público\n• licença define condições de uso\n• autoria e autorização são conceitos diferentes"],
["Fontes e licenças","Fontes digitais também estão sujeitas a condições de licença. “Grátis” pode significar sem custo financeiro e ainda possuir restrições específicas. Antes de usar uma fonte, verifique se a licença permite o projeto, distribuição, incorporação em software, modificação ou uso comercial conforme o caso. Manter registro do arquivo e da licença melhora a rastreabilidade dos ativos do projeto.","• grátis ≠ sem condições\n• leia a licença da fonte\n• registre origem e permissões relevantes"],
["Ética profissional","Ética no design envolve precisão, responsabilidade, autoria, confidencialidade e impacto social. Um gráfico pode induzir interpretação errada; uma imagem pode violar direitos; um arquivo sigiloso pode ser exposto; uma alteração pode apagar autoria. Em contexto público, decisões visuais têm efeitos sobre confiança e compreensão do cidadão. Ética não é apenas “ser educado”: também é escolher tecnicamente de forma responsável.","• precisão e transparência importam\n• respeite autoria e sigilo\n• decisões visuais podem gerar consequências reais"],
["Design e serviço público","Design de serviço olha a experiência como um conjunto de etapas e pontos de contato. No setor público, a pergunta inicial é qual necessidade do cidadão precisa ser resolvida e não qual peça gráfica deve ser produzida. Mapear jornada, conteúdo, canais, barreiras e resultados ajuda a transformar informação em serviço utilizável. O designer pode atuar em formulários, sinalização, cartilhas, sistemas, campanhas e fluxos.","• comece pela necessidade\n• visualize jornada e pontos de contato\n• resultado de serviço é mais amplo que aparência"],
["Organização técnica","Organização de projeto reduz retrabalho e erro. Pastas por etapa, nomenclatura consistente, versões, arquivos editáveis, provas e backups facilitam colaboração e rastreabilidade. Uma estrutura do tipo “01_briefing / 02_fontes / 03_editavel / 04_provas / 05_final” é mais segura que dezenas de arquivos chamados “final”. Em equipe, organização também ajuda outras pessoas a entenderem o histórico da peça.","• nomeação consistente\n• controle de versões\n• backup e rastreabilidade fazem parte da entrega"],
["Atribuições práticas do cargo","As atribuições de um designer gráfico em ambiente público podem envolver peças institucionais, templates, infográficos, cartilhas, sinalização, ordens de serviço, produção gráfica e apoio audiovisual. A ferramenta é apenas o meio: o trabalho começa pela interpretação do briefing, passa por solução visual, revisão e fechamento técnico. Uma demanda acessível, por exemplo, exige hierarquia, contraste, tipografia, conteúdo e teste, não apenas domínio de um software.","• briefing → produção → revisão → entrega\n• combine competência visual e técnica\n• pense na demanda, não só na ferramenta"]
]
};

function renderText(text){
  return String(text||'').split('\n\n').map(p=>'<p>'+p.replace(/\n/g,'<br>')+'</p>').join('');
}
function inject(s,i){
  const item=D[s]?.[i];
  const lesson=document.querySelector('.lesson');
  if(!item||!lesson)return;
  const existing=document.querySelector('.study-depth-card');
  if(existing)existing.remove();
  const h=document.createElement('section');
  h.className='study-depth-card';
  h.innerHTML='<div class="eyebrow">📚 LEITURA PRINCIPAL · '+String(item[0]).replace(/</g,'&lt;')+'</div>'+
    '<h2>Agora leia para estudar de verdade</h2>'+
    '<div class="study-depth-text">'+renderText(item[1])+'</div>'+
    '<div class="study-depth-memorize"><h3>🎯 O que você precisa saber para a prova</h3>'+
    '<ul>'+item[2].split('\n').filter(Boolean).map(x=>'<li>'+x.replace(/</g,'&lt;')+'</li>').join('')+'</ul></div>'+
    '<div class="study-depth-rule"><strong>Como usar esta parte:</strong> leia primeiro sem tentar decorar. Depois feche a aula mentalmente e explique o conceito com suas próprias palavras antes de partir para as questões.</div>';
  const body=lesson.querySelector('.lesson-body');
  if(body)body.after(h); else lesson.prepend(h);
}

const prev=window.lesson;
if(typeof prev==='function'){
  window.lesson=function(s,i){
    prev(s,i);
    setTimeout(function(){inject(s,i);},0);
  };
}
})();