'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.join(__dirname,'..'),shots='/tmp/canedo-guided-qa';fs.mkdirSync(shots,{recursive:true});
const types={'.js':'application/javascript','.css':'text/css','.html':'text/html','.jpg':'image/jpeg','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0])==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{const buf=fs.readFileSync(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'text/plain'});res.end(buf)}catch{res.writeHead(404);res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});const context=await browser.newContext({viewport:{width:1365,height:900}}),page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.getByRole('heading',{name:'Um passo. Depois, o próximo.'}).waitFor();
 await page.screenshot({path:shots+'/home.png',timeout:30000});
 // All modules have a guided path, and every custom visual ID resolves.
 const counts=await page.evaluate(()=>{const all=Object.entries(MODULES).flatMap(([s,mods])=>mods.map((m,i)=>({s,i})));for(const {s,i} of all){const p=CQGuide.pack(s,i);if(!p.steps.length)throw Error('empty '+s+i);for(const st of p.steps){if(st.visual&&!CQGuideVisual.has(st.visual))throw Error('missing '+st.visual);if(st.type==='choice'&&(!st.options[st.answer]||st.explain.length!==st.options.length))throw Error('bad question '+s+i);}}return {all:all.length,curated:Object.keys(CQGuideContent).length}});assert.equal(counts.all,113);assert.ok(counts.curated>=30);
 // A genuine wrong click: completion stays locked and explanation is shown, then retry after later cards.
 await page.evaluate(()=>CQGuide.open('design',1,true));await page.evaluate(()=>CQGuide.startPractice());assert.ok(await page.getByRole('button',{name:'Continuar →',exact:true}).isDisabled());
 await page.getByRole('button',{name:/Os dois blocos têm cores diferentes/}).click();assert.ok(await page.locator('.g-feedback.again').isVisible());assert.equal(await page.evaluate(()=>Boolean(state.lessonDone['design:1'])),false);
 await page.getByRole('button',{name:'Entendi. Continuar →',exact:true}).click();const saved=await page.locator('h1').innerText();await page.reload();assert.equal(await page.locator('h1').innerText(),saved);assert.equal(await page.evaluate(()=>state.guided.pos),3);
 await page.evaluate(()=>CQGuide.pause());assert.equal(await page.locator('.guide-focus').count(),0);await page.getByRole('button',{name:'Continuar →',exact:true}).click();assert.equal(await page.locator('h1').innerText(),saved);
 // Run the remaining cards with correct answers; the original error must appear again.
 await page.evaluate(()=>{let guard=0;while(state.guided.phase!=='done'&&guard++<60){const g=state.guided,p=CQGuide.pack(g.s,g.i),j=g.phase==='retry'?g.retry[0]:g.pos,st=p.steps[j];if(st.type==='choice'&&!g.answers[j])CQGuide.answer(st.answer);else if(st.type==='input'&&!g.answers[j])CQGuide.answer(st.accepted[0]);CQGuide.advance();}if(guard>=60)throw Error('retry loop');});
 assert.equal(await page.evaluate(()=>state.guidedProgress['design:1'].firstRight),2);assert.equal(await page.evaluate(()=>state.guidedProgress['design:1'].firstTotal),3);assert.equal(await page.evaluate(()=>state.guided.phase),'done');const xp=await page.evaluate(()=>state.xp);await page.reload();assert.equal(await page.evaluate(()=>state.xp),xp);assert.ok(await page.locator('.g-done').isVisible());
 // Every curated lesson is completable with explanations and all its transfer activities.
 const keys=await page.evaluate(()=>Object.keys(CQGuideContent));for(const key of keys){await page.evaluate(key=>{const [s,i]=key.split(':');CQGuide.open(s,Number(i),true);CQGuide.startPractice();let guard=0;while(state.guided.phase!=='done'&&guard++<70){const g=state.guided,p=CQGuide.pack(s,Number(i)),j=g.phase==='retry'?g.retry[0]:g.pos,st=p.steps[j];if(st.type==='choice')CQGuide.answer(st.answer);if(st.type==='input')CQGuide.answer(st.accepted[0]);CQGuide.advance();}if(guard>=70)throw Error('did not complete '+key);},key);}
 console.log('Guided content and scoring passed',counts);
 // Repeating a completed lesson cannot farm completion XP; due retrieval has its own saved schedule.
 await page.evaluate(()=>{CQGuide.open('design',1,true);CQGuide.startPractice()} );const previousXP=await page.evaluate(()=>state.xp);await page.evaluate(()=>{for(let k=0;k<40&&state.guided.phase!=='done';k++){const g=state.guided,st=CQGuide.pack(g.s,g.i).steps[g.pos];if(st.type==='choice')CQGuide.answer(st.answer);CQGuide.advance();}});assert.equal(await page.evaluate(()=>state.xp),previousXP);
 await page.evaluate(()=>{state.guidedProgress['design:1'].nextReview=1;CQGuide.pause();CQGuide.begin()});assert.equal(await page.evaluate(()=>state.guided.reviewOnly),true);assert.equal(await page.evaluate(()=>state.guided.phase),'retry');
 // Exact mobile bounds on every card of every curated lesson, including feedback.
 await page.setViewportSize({width:390,height:844});for(const key of keys){const num=await page.evaluate(key=>{const [s,i]=key.split(':');CQGuide.open(s,Number(i),true);return CQGuide.pack(s,Number(i)).steps.length},key);for(let j=0;j<num;j++){await page.evaluate(j=>{state.guided.pos=j;CQGuide.render()},j);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${key}:${j} overflow`);}}
 // All other modules open safely in the new default mode.
 const modules=await page.evaluate(()=>Object.entries(MODULES).flatMap(([s,ms])=>ms.map((_,i)=>({s,i}))));for(const m of modules){await page.evaluate(({s,i})=>CQGuide.open(s,i,true),m);assert.equal(await page.locator('.ch-heading h1').count(),1);}
 for(const [s,i,pos,name] of [['design',1,0,'gestalt'],['design',3,0,'figure-ground'],['design',4,0,'posters'],['design',6,0,'anatomy'],['math',3,0,'percent'],['pt',7,0,'syntax'],['info',0,0,'code'],['municipio',3,0,'timeline']]){await page.evaluate(({s,i,pos})=>{CQGuide.open(s,i,true);state.guided.pos=pos;CQGuide.render()},{s,i,pos});await page.screenshot({path:shots+'/'+name+'-mobile.png',fullPage:true,timeout:30000});}
 await page.evaluate(()=>CQGuide.open('design',8,true));await page.locator('#g-rgb-G').fill('255');assert.equal(await page.locator('#g-rgb-out').innerText(),'RGB(255, 255, 0)');
 await page.evaluate(()=>CQGuide.open('design',18,true));await page.waitForFunction(()=>{const c=document.getElementById('g-pixel-canvas');return c&&c.getContext('2d').getImageData(0,0,1,1).data[3]>0});
 // Chapters allow direct navigation, persistence, and return from reference.
 await page.evaluate(()=>{CQGuide.open('pt',5,true);CQChapter.select(2)});await page.reload();assert.equal(await page.evaluate(()=>state.guided.chapter),2);
 await page.getByRole('button',{name:'Material de apoio ↗'}).click();assert.ok(await page.locator('.lesson').isVisible());await page.getByRole('button',{name:'Voltar aos capítulos →'}).click();assert.equal(await page.evaluate(()=>state.guided.chapter),2);
 const deep=await page.evaluate(()=>Object.keys(CQChapterContent));assert.equal(deep.length,20);
 for(const key of deep){for(let chapter=0;chapter<4;chapter++){await page.evaluate(({key,chapter})=>{const [s,i]=key.split(':');CQGuide.open(s,+i,true);CQChapter.select(chapter)},{key,chapter});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),key+' chapter '+chapter);}}
 await page.evaluate(()=>CQGuide.open('pt',5,true));
 // State import validation and the offline image/application assets.
 assert.equal(await page.evaluate(()=>{const copy=validateProgress(JSON.parse(JSON.stringify(state)));return copy.guided.pos}),0);
 assert.equal(await page.evaluate(()=>{const bad=JSON.parse(JSON.stringify(state));bad.guided.orders={'0':[0,0]};try{validateProgress(bad);return false}catch{return true}}),true);
 await page.evaluate(async()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();assert.equal(await page.evaluate(()=>state.guided.pos),0);await page.evaluate(()=>CQGuide.open('design',4,true));await page.waitForFunction(()=>[...document.querySelectorAll('.g-poster img')].every(im=>im.complete&&im.naturalWidth>0));await context.setOffline(false);
 assert.deepEqual(errors,[]);console.log('PASS: 113 guided modules, '+counts.curated+' authored mini-lessons; retry, resume, XP, source/reference, mobile bounds, images, import, offline. Screenshots '+shots);
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
